### ISSUE TITLE
[Docs RFC] Add information about ReadOnly mode and `default_transaction_read_only` postgres parameter

### ISSUE THREAD

**Issue by itroot** [timescale/docs#100]
I think we need to add to our docs the fact that user can get out (or get into :smile: ) "read-only" mode by changing `default_transaction_read_only` postgres parameter.

**Comment by Loquacity** [comment]
This exists in the new disk management section here: https://docs.timescale.com/timescale-forge/latest/disk-management/#procedure-enabling-read-write-access-on-an-individual-session
