### ISSUE TITLE
[RFE] Improve Compression documentation

### ISSUE THREAD

**Issue by markandpathak** [timescale/docs#1005]
# Describe the bug

Decompression and compression documentation lacks many important details. Like:
1. Once we manually decompress chunks, and do not turn off compression policy do they get compressed again when job runs next time?
2. The documentation should contain a script to easily decompress all the chunks for a table.

The method using `show_chunks` is useful only when user knows that all the chunks are compressed in the time range in which chunks should be decompressed otherwise script throws error if even a single chunk is present in uncompressed state in the given time range. 

## What do the docs say now?
Documentation does not provide any clarification on what happens once we manually decompress the chunks given compression policy is enabled. Do they stay as it is or do they get compressed again?

Documentation also lacks a clear method to decompress all the compressed chunks for a hypertable in case the user wants to disable compression entirely.

## What should the docs say?
Implications and effects after manually decompressing chunks should be described in detail.

Following is a suggested script which can be added to the documentation which enables user to decompress all the chunks of a hypertable if needed: 
```
SELECT decompress_chunk(i.chunk) from (select concat(chunk_schema, '.', chunk_name) as chunk from chunk_compression_stats(<hypertable>) where compression_status = 'Compressed') i;
```
# Page affected

[https://docs.timescale.com/api/latest/compression/decompress_chunk/#decompress-chunk](https://docs.timescale.com/api/latest/compression/decompress_chunk/#decompress-chunk)

# SME

@gayyappan

**Comment by markandpathak** [comment]
Until documentation is updated, Can you please provide some clarification on what happens once we manually decompress the chunk but compression policy is still enabled? One of our scnarios require us to backfill data. Do we need compress chunks manually or compression policy takes care of that?

**Comment by svenklemm** [comment]
If you decompress manually the next run of the policy will recompress it.

**Comment by JLockerman** [comment]
For decompressing all and only the chunks that are compressed, I think [this code](https://github.com/timescale/timescaledb/blob/332dffeebc72cf16afbde802e2f19aead9bd7836/tsl/test/sql/include/compression_test_hypertable.sql#L44-L47) is the best I know of:
```SQL
SELECT count(decompress_chunk(chunk.schema_name|| '.' || chunk.table_name)) as count_decompressed
FROM _timescaledb_catalog.chunk chunk
INNER JOIN _timescaledb_catalog.hypertable hypertable ON (chunk.hypertable_id = hypertable.id)
WHERE hypertable.table_name = '$HYPERTABLE_NAME' and chunk.compressed_chunk_id IS NOT NULL;
```

**Comment by svenklemm** [comment]
An easier query for decompressing all chunks of a hypertable is this:
```
select decompress_chunk(c,true) from show_chunks('metrics') c;
```
