### ISSUE TITLE
[Content Bug] Update default value of `timescaledb.max_background_workers` to 16

### ISSUE THREAD

**Issue by konskov** [timescale/docs#1099]
# Describe the bug

I think we need to update the default value of `timescaledb.max_background_workers` to 16. 

## What do the docs say now?
Default value is 8.

## What should the docs say?
Default value is 16.

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-config/#policies

# Version affected

Not sure where I can see that info?

# Subject matter expert (SME)

# Screenshots

# Any further info

[Relevant location in timescaledb source code](https://github.com/timescale/timescaledb/blob/92f7e5d36164c1fd955c8b9ef5ed5cd4837ae026/src/loader/bgw_counter.c#L22)

**Comment by Rajakavitha1** [comment]
@konskov thank you for raising the issue. This has now been addressed in https://github.com/timescale/docs/pull/1111. Please review the changes and let us know if any other changes need to be made.
