### ISSUE TITLE
Promscale CLI flags are not up-to-date

### ISSUE THREAD

**Issue by ramonguiu** [timescale/docs#1105]
# Describe the bug

Promscale CLI flags are missing new flags added in 0.11.0 and possible other flags too. 

## What do the docs say now?

What's in https://github.com/timescale/promscale/blob/master/docs/configuration.md#metrics-specific-flags

## What should the docs say?

https://docs.timescale.com/promscale/latest/cli/

For example the flags for alerts and recording rules are missing as well as some of the Telemetry flags.
Some flags like logs.* have been renamed to telemetry.logs.* but they show their old name in the docs.

# Page affected
https://docs.timescale.com/promscale/latest/cli/

# Version affected

# Subject matter expert (SME)
@VineethReddy02

**Comment by hardikm10** [comment]
Not sure if the above PR takes care of the below:

A similar thing around flags at : https://docs.timescale.com/promscale/latest/installation/docker/#install-promscale-with-docker, 
![Uploading Install Promscale with Docker  Timescale Docs 2022-05-31 at 9.38.29 AM.jpg…]()
 
The latest version i.e 0.11.0, at the moment, has removed certain flags that fails this `docker run` command 
https://github.com/timescale/promscale/blob/master/docs/configuration.md#old-flag-removal-in-version-0110

They should be replaced, for example, -db-password => -db.password and so on.

**Comment by Rajakavitha1** [comment]
> Not sure if the above PR takes care of the below:
> 
> A similar thing around flags at : https://docs.timescale.com/promscale/latest/installation/docker/#install-promscale-with-docker, ![Install Promscale with Docker Timescale Docs 2022-05-31 at 9 38 29 AM](https://user-images.githubusercontent.com/8678005/171091262-9629bc61-3e95-4511-b6fd-7da2a9b81fe9.jpg)
> 
> The latest version i.e[ 0.11.0,](https://github.com/timescale/promscale/blob/master/docs/configuration.md#old-flag-removal-in-version-0110) at the moment, has removed certain flags that fails to run promscale after the `docker run` is executed, results in the error like :
> 
> ```
> flag provided but not defined: -db-password
> Usage of /promscale:
> ```
> 
> They should be replaced, for example, -db-password => -db.password and so on.

Thanks for mentioning the deprecated flags @hardikm10 .  This has been updated in https://github.com/timescale/docs/pull/1132. and the we also validated the updates that you made in https://github.com/timescale/docs/pull/1124
