### ISSUE TITLE
Add UDA examples in other languages

### ISSUE THREAD

**Issue by charislam** [timescale/docs#1128]
# Describe change in content, appearance, or functionality

You can create UDAs in other languages, but our docs currently show only plpgsql examples. Add examples in other commonly used languages.

[Relevant Slack thread](https://timescaledb.slack.com/archives/C4GT3N90X/p1653308360323139?thread_ts=1653308360.323139&cid=C4GT3N90X)

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
This will probably require some assistance from the Developer Advocate team. @ryanbooz who would you suggest we work with on this?

**Comment by Loquacity** [comment]
@jamessewell Perhaps you can suggest some SMEs for us here?
