### ISSUE TITLE
[Docs RFC] Update recommended constraint_exclusion setting

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#1134]
# Describe change in content, appearance, or functionality

> I have a hypertable with daily chunks and compression policy “older than 3 days”.
> I regularly make DELETE request for data that is newer then 24 hours.
> But when compression kicks in for 4-day-old chunk, it blocks my DELETEs for today’s data.
> I even rewritten my DELETE requests to show Timescale, that I don’t want to touch old data:
> 
> DELETE FROM “my_table” WHERE (time >= ‘2022-05-23 09:43:00’) AND “my_tabe”.“user_id” = 123 AND “my_table”.“time” = ‘2022-05-23 09:43:00’
> 
> But with no success. And this DELETE is blocked by compression of the chunk 2022-05-17 00:00:00+00 → 2022-05-18 00:00:00+00
> 
> Is it a known bug? Is there a workaround for this?

> After some research we found that issue fixed by change constraint_exclusion postgresql setting from default value partition to more generic value ‘on’
> see [PostgreSQL: Documentation: 14: 20.7. Query Planning](https://www.postgresql.org/docs/14/runtime-config-query.html#RUNTIME-CONFIG-QUERY-OTHER)
> 
> I can’t find any mention of recommended constraint_exclusion setting in timescaledb docs though.

# Subject matter expert (SME)
Sven Klemm

# Deadline

[When does this need to be addressed]

# Any further info

Link to community Forum post: https://www.timescale.com/forum/t/unable-to-delete-data-when-chunk-compression-is-undergoing/537

**Comment by svenklemm** [comment]
The default value for constraint exclusion should be sufficient and users don't need to change this. There have been improvements to this area of code in recent version so i would definitely recommend upgrading to PG14 and latest timescaledb version (2.7.0).

**Comment by Rajakavitha1** [comment]
Marking this issue as closed because no changes are required in the documentation.

**Comment by wrona100** [comment]
Hello, I am using Postgres 14.7 and Timescaledb 2.11.1 and I still have the same problem. During compression, the possibility of deleting data from the table that is not subject to compression is blocked.
Tabele:
CREATE TABLE IF NOT EXISTS public.sec
(
    tagno integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    value real,
    confidence smallint DEFAULT 100
)
interval_length=24h

Manually invoked compression:
SELECT compress_chunk(i, if_not_compressed => true) FROM show_chunks('sec','2023-09-03 00:00:00+00','2023-09-02 00:00:00+00')i;

Bloked query:
delete from sec where (timestamp > '2023-09-07')  and tagno=1000000000 and timestamp = '2023-09-07 12:00:00+00';

I haven't changed the constraint exclusion parameter yet
Anyone have an idea why?
Does anyone have an idea why? Any suggestions ?

**Comment by wrona100** [comment]
Maybe a bug in the compression settings. Below is the view from the query:
SELECT * FROM timescaledb_information.compression_settings WHERE hypertable_name = 'sec';

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hg021906/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hg021906/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>



hypertable_schema | hypertable_name | attname | segmentby_column_index | orderby_column_index | orderby_asc | orderby_nullsfirst
-- | -- | -- | -- | -- | -- | --
public | sec | tagno | 1 |   |   |  
public | sec | timestamp |   | 1 | false | true



</body>

</html>

**Comment by Loquacity** [comment]
Hi @wrona100 This repo is for tracking changes in the documentation. If you need support, I suggest you start with the [Timescale Community](https://www.timescale.com/community).
