### ISSUE TITLE
[Update] Explain -infinity of next_start in jobs.

### ISSUE THREAD

**Issue by k-rus** [timescale/docs#1143]
Users asks what `-infintiy` for `next_start` means in jobs. E.g., on newly created continuous aggregate policy. I don't find if it is explained in the documentation so it will be great to explain.

**Comment by Loquacity** [comment]
@NunoFilipeSantos Can you help here?

**Comment by NunoFilipeSantos** [comment]
This is the [only hit](https://docs.timescale.com/api/latest/actions/alter_job/#alter-job) I read on docs: `The next time at which to run the job. The job can be paused by setting this value to infinity, and restarted with a value of now()`.

@mkindahl or @erimatnor might know more.

**Comment by mkindahl** [comment]
When the job starts execution, it seems to set the `next_start` value to `-infinity`. Once the job completes, it will set the value to the actual computed next start time. Look in `bgw_job_stat_tuple_mark_start` and you will se that it is set to `DT_NOBEGIN`, which is a constant representing `-infinity`.

**Comment by mindrunner** [comment]
So if a running Job gets killed or segfaults or similar, this stays `-Inf` forever and never gets rescheduled?

**Comment by mkindahl** [comment]
@mindrunner The scheduler will notice that the state is incorrect and correct the next start so that it is rescheduled.

**Comment by mindrunner** [comment]
Cool, yea I noticed that as well. However, sometimes it seems like nothing is happening at all. Is there some sort of frequency for the scheduler being active? e.g. how long am I supposed to wait after a job failed for it to be re-scheduled?
