### ISSUE TITLE
Documentation about `tsdb_admin.allowed_databases`

### ISSUE THREAD

**Issue by brianjychan** [timescale/docs#1148]
# Describe the bug

Looking for info about `tsdb_admin.allowed_databases` after this error occurring when trying to create a database:

```
ERROR:  tsdb_admin: database anotherdb is not an allowed database name
HINT:  Contact your administrator to configure the "tsdb_admin.allowed_databases"
```

## What do the docs say now?

Nothing about this error

## What should the docs say?

Something about this error

**Comment by NunoFilipeSantos** [comment]
One of the Architects should be able to help here. (cc: @erimatnor or @mkindahl)

**Comment by mkindahl** [comment]
@brianjychan Could you show the full command that you used to create the database?

**Comment by mkindahl** [comment]
To give a summary: Cloud is configured to only have one database for each running instance. To ensure this, there is an extension `tsdb_admin` that blocks creating databases that are not in the list `tsdb_admin.allowed_databases`. If you want to have a second database, you need to create a second instance.
