### ISSUE TITLE
[Site Bug] Typo on page: /timescaledb/latest/how-to-guides/schema-management/about-schemas/

### ISSUE THREAD

**Issue by niconosenzo** [timescale/docs#1156]
# Describe the bug

Another small typo.

## What do the docs say now?

"This section explains how to design your schema, how indexing and tablespaces work, and how to use PostreSQL contraint types."

## What should the docs say?

"This section explains how to design your schema, how indexing and tablespaces work, and how to use PostreSQL **constraint** types."

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/about-schemas/#table-management

# Version affected

`latest`

# Subject matter expert (SME)

N/A

# Screenshots

![image](https://user-images.githubusercontent.com/10870596/171838101-d25ff8f4-953e-4cbe-9705-3bcf015a3e76.png)

# Any further info

N/A

**Comment by niconosenzo** [comment]
@Loquacity thanks for fixing the issue tittle, will use the same on the future.

**Comment by Loquacity** [comment]
All good, just trying to make the automated title a little more informative for when we pick this off the backlog 😉
