### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/

### ISSUE THREAD

**Issue by knrt10** [timescale/docs#1171]
# Describe the bug

Getting [started link](https://docs.timescale.com/timescaledb/latest/#getting-started) tutorial link gives 404.

## What do the docs say now?

Gives 404

## What should the docs say?

I think it should point to [Tutorials](https://docs.timescale.com/timescaledb/latest/tutorials/)

# Page affected

[Getting started](https://docs.timescale.com/timescaledb/latest/#getting-started)

# Version affected

On the `latest` version

# Any further info

If the link I provided should be the same, I guess I can make a PR for it.

**Comment by charislam** [comment]
fixed though I can't remember when ... 😅
