### ISSUE TITLE
[Docs RFC] Self-hosted macos installation page is out of date

### ISSUE THREAD

**Issue by mathisve** [timescale/docs#1175]
# Describe change in content, appearance, or functionality

I was trying to install TimescaleDB on my M1 Mac and the [install guide](https://docs.timescale.com/install/latest/self-hosted/installation-macos/) is very out of date. In particular the paths. I'm not sure if brew uses a different path on M1 macs but `/usr/local/bin/timescaledb_move.sh` is nowhere to be found. Instead it lives in `/opt/homebrew/Cellar/timescaledb/2.7.0/bin`. Along with some other issues mainly originating from what I'm guessing are path differences between linux and mac. 

# Subject matter expert (SME)

Having had this issue I went on quite a deep-dive and now know how to install it correctly.
I tried answering a discussion in timescale/timescaledb where someone was having the same [issue](https://github.com/timescale/timescaledb/discussions/4201) and roughly outlined the steps. If needed I could update the docs.

**Comment by charislam** [comment]
Thanks for this @mathisve! It would be great if you could do an initial draft of the write-up since you're familiar with the resolution! Even just the commands you used with very rough notes on why, and then the docs team can help polish it up

I did a little research around the topic, and it seems:
- Brew does indeed use a different install path on M1 Macs (https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location) so it may be worthwhile documenting both Intel/Silicon for some time. We'd need to get someone to test Intel
- I went spelunking in the timescaledb-tune code base and it does look like the intent is to look for the M1 postgresq.conf path (`fileNameMacM1     = "/opt/homebrew/var/postgres/postgresql.conf"`), so I'm not sure why it doesn't. Is it worth bringing up with the engineering team?

**Comment by Rajakavitha1** [comment]
Validated the installation on Mac1:Pruned 1 symbolic links and 4 directories from /opt/homebrew
==> Caveats
==> timescaledb
RECOMMENDED: Run 'timescaledb-tune' to update your config settings for TimescaleDB.

  timescaledb-tune --quiet --yes

IF NOT, you'll need to make sure to update /opt/homebrew/var/postgres/postgresql.conf
to include the extension:

  shared_preload_libraries = 'timescaledb'

To finish the installation, you will need to run:

  timescaledb_move.sh

If PostgreSQL is installed via Homebrew, restart it:

  brew services restart postgresql

rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % timescaledb-tune --quiet --yes
exit: could not find postgresql.conf at any of these locations:
/usr/local/var/postgres/postgresql.conf
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % nano /opt/homebrew/var/postgres/postgresql.conf
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % cd /opt/hombrew/Cellar/
cd: no such file or directory: /opt/hombrew/Cellar/
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % cd /opt
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 /opt % cd homebrew
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 homebrew % cd Cellar
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 Cellar % ls
ca-certificates		krb5			postgresql
cmake			kubernetes-cli		readline
docbook			lz4			timescaledb
docbook-xsl		nvm			timescaledb-tools
fop			openjdk			xz
helm			openssl@1.1
icu4c			openssl@3
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 Cellar % cd timescaledb
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 timescaledb % ls
2.7.0
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 timescaledb % cd 2.7.0
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 2.7.0 % ls
CHANGELOG.md		LICENSE-APACHE		bin
INSTALL_RECEIPT.json	NOTICE			lib
LICENSE			README.md		share
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 2.7.0 % cd bin
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % ls
timescaledb_move.sh
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % cd /opt/homebrew/Cellar/timescaledb-tools
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 timescaledb-tools % ls
0.12.0
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 timescaledb-tools % cd 0.12.0
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 0.12.0 % ls
INSTALL_RECEIPT.json	bin
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 0.12.0 % cd bin
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % ls
timescaledb-parallel-copy	ts-dump
timescaledb-tune		ts-restore
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % timescaledb-tune --quiet --yes
exit: could not find postgresql.conf at any of these locations:
/usr/local/var/postgres/postgresql.conf
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % nano timescaledb-tune
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % timescaledb-tune --conf-path=/opt/homebrew/postgres/postgresql.conf
exit: could not open config file for reading: open /opt/homebrew/postgres/postgresql.conf: no such file or directory
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % timescaledb-tune --conf-path=/opt/homebrew/var/postgres/postgresql.conf
Using postgresql.conf at this path:
/opt/homebrew/var/postgres/postgresql.conf

Writing backup to:
/var/folders/6d/5c405z253n35bqph1mh4bdp00000gn/T/timescaledb_tune.backup202206171221

shared_preload_libraries needs to be updated
Current:
#shared_preload_libraries = ''
Recommended:
shared_preload_libraries = 'timescaledb'
Is this okay? [(y)es/(n)o]: yes
success: shared_preload_libraries will be updated

Tune memory/parallelism/WAL and other settings? [(y)es/(n)o]: yes
Recommendations based on 8.00 GB of available memory and 8 CPUs for PostgreSQL 14

Memory settings recommendations
Current:
shared_buffers = 128MB
#effective_cache_size = 4GB
#maintenance_work_mem = 64MB
#work_mem = 4MB
Recommended:
shared_buffers = 2GB
effective_cache_size = 6GB
maintenance_work_mem = 1GB
work_mem = 2621kB
Is this okay? [(y)es/(s)kip/(q)uit]: yes
success: memory settings will be updated

Parallelism settings recommendations
Current:
missing: timescaledb.max_background_workers
#max_worker_processes = 8
#max_parallel_workers_per_gather = 2
#max_parallel_workers = 8
Recommended:
timescaledb.max_background_workers = 8
max_worker_processes = 19
max_parallel_workers_per_gather = 4
max_parallel_workers = 8
Is this okay? [(y)es/(s)kip/(q)uit]: yes
success: parallelism settings will be updated

WAL settings recommendations
Current:
#wal_buffers = -1
min_wal_size = 80MB
Recommended:
wal_buffers = 16MB
min_wal_size = 512MB
Is this okay? [(y)es/(s)kip/(q)uit]: yes
success: WAL settings will be updated

Miscellaneous settings recommendations
Current:
#default_statistics_target = 100
#random_page_cost = 4.0
#checkpoint_completion_target = 0.9
#max_locks_per_transaction = 64
#autovacuum_max_workers = 3
#autovacuum_naptime = 1min
Recommended:
default_statistics_target = 500
random_page_cost = 1.1
checkpoint_completion_target = 0.9
max_locks_per_transaction = 128
autovacuum_max_workers = 10
autovacuum_naptime = 10
Is this okay? [(y)es/(s)kip/(q)uit]: yes
success: miscellaneous settings will be updated
Saving changes to: /opt/homebrew/var/postgres/postgresql.conf
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % cd /opt/homebrew/Cellar/timescaledd/
cd: no such file or directory: /opt/homebrew/Cellar/timescaledd/
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % cd /opt/homebrew/Cellar/timescaledb
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 timescaledb % ls
2.7.0
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 timescaledb % cd 2.7.0
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 2.7.0 % ls
CHANGELOG.md		LICENSE-APACHE		bin
INSTALL_RECEIPT.json	NOTICE			lib
LICENSE			README.md		share
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 2.7.0 % cd bin
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % ls
timescaledb_move.sh
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin % timescaledb_move.sh
Moving files into place...
Success.
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 bin %

**Comment by Rajakavitha1** [comment]
I also logged an issue in the timescaledb-tune repo:[98 ](https://github.com/timescale/timescaledb-tune/issues/98)
