### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/tutorials/analyze-intraday-stocks/fetch-and-ingest/

### ISSUE THREAD

**Issue by eposse** [timescale/docs#1193]
_Use this template for reporting bugs in the docs._

# Describe the bug

The fetch_stock_data function uses 'pd' but it is undefined.

## What should the docs say?

# Page affected

[Provide the URL to the page you noticed the bug on]

# Version affected

[Which version of the site you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
@zseta are you able to help here?

**Comment by eposse** [comment]
The 'pd' in the code turns out to be the `pandas` package, which is not mentioned in the page. The page needs to add instructions on how to install pandas:

```bash
pip install pandas
```

 and the code needs to import it:

```python
import pandas as pd
```

Furthermore, the code in the last snippet will fail, first with the variable `symbols` undefined, unless the first code snippet (below) is included in the same python file:

```python
import csv
with open('symbols.csv') as f:
    reader = csv.reader(f)
    symbols = [row[0] for row in reader]
```

but the documentation doesn't indicate that all the code snippets should be in the same file.

Furthermore, even after these fixes, the code will still fail with a `ValueError` exception because the columns are listed in the wrong order. Currently the code shows

```python
COLUMNS = ('time', 'symbol', 'price_open', 'price_close',
           'price_low', 'price_high', 'trading_volume')
```

but the previous code snippet (i.e. the `fetch_stock_data` function) adds the `symbol` column last, so when `pgcopy` tries to parse the rows, it gets a float when expecting a string (the 'symbol'). Hence, the correct order is:

```python
COLUMNS = ('time', 'price_open', 'price_close',
           'price_low', 'price_high', 'trading_volume', 'symbol')
```



```

**Comment by Rajakavitha1** [comment]
Thank you @eposse for validating and providing all the information about the issue that you faced and the workaround as well. This certainly helps us create good documentation.

**Comment by greenweeds** [comment]
@eposse we'd love to show our appreciation! 
If you wear tech tees and would like to choose a Timescaled tee, please drop me an email to lorraine at timescale dot com or if you use our community Slack you can find me there, you can DM. I couldn't find a reliable contact detail for you!
