### ISSUE TITLE
[Content Bug] Debian installation instructions for specific version require update

### ISSUE THREAD

**Issue by konskov** [timescale/docs#1195]
_Use this template for reporting bugs in the docs._

# Describe the bug

Our documentation on how to install a specific version on debian is 

## What do the docs say now?
```
apt-get install timescaledb-2-2.6.0-postgresql-12
```

## What should the docs say?
```
apt-get install timescaledb-2-postgresql-12='2.6.0*' timescaledb-2-loader-postgresql-12='2.6.0*'
```

# Page affected

https://docs.timescale.com/install/latest/self-hosted/installation-debian/#install-self-hosted-timescaledb-on-debian-based-systems

# Version affected

latest

# Subject matter expert (SME)

# Screenshots
![Screenshot 2022-06-16 at 6 04 12 PM](https://user-images.githubusercontent.com/44239391/174100543-adee52cb-13da-4e26-9ce4-c8c8ad46b6e3.png)

# Any further info

**Comment by Rajakavitha1** [comment]
Hi @konskov I just checked our release page and apt-get install command listed is :
<img width="1316" alt="Screenshot 2022-06-17 at 8 39 16 AM" src="https://user-images.githubusercontent.com/37059749/174217286-977387ad-06de-49ff-8ecc-4471475d1bae.png">

**Comment by charislam** [comment]
@konskov tried to validate the install instructions as you've written them and ran into this error. What do we need to be doing differently?

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package timescaledb-2-loader-postgresql-12 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package timescaledb-2-postgresql-12 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '2.6.0*' for 'timescaledb-2-postgresql-12' was not found
E: Version '2.6.0*' for 'timescaledb-2-loader-postgresql-12' was not found
```

**Comment by konskov** [comment]
Apologies for the delay, let me check this now and I'll respond here

**Comment by charislam** [comment]
Ahhh I got it! Thanks so much for trying @konskov, took a look at your screenshot and realized what my error was.

I was running on Ubuntu Jammy (which the latest version supports), but I guess older versions do not. Downgraded to Focal and it worked fine. I'll make the necessary change and add a note that newer OS versions may not be supported if you choose to install an older TimescaleDB version.
