### ISSUE TITLE
List of latest version

### ISSUE THREAD

**Issue by benneharli** [timescale/docs#1200]
Refer to #725. We still need a page where it's listed what the latest released version is.

**Comment by Loquacity** [comment]
Let's add a link to [the releases page](https://github.com/timescale/timescaledb/releases) from the main installation page. We can also add a link to [the release notes](https://docs.timescale.com/timescaledb/latest/overview/release-notes/).

**Comment by benneharli** [comment]
I didn't know about those pages. Thanks! They cover the information. Yes, a link from the download page would also be great.
