### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/data-retention/about-data-retention/

### ISSUE THREAD

**Issue by vshev4enko** [timescale/docs#1221]
# Describe the bug

Typo in the text `fire` -> `file`

## What do the docs say now?
deletes an entire fire from disk

## What should the docs say?
deletes an entire file from disk

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/data-retention/about-data-retention/#drop-data-by-chunk

# Version affected

v2.X

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by Rajakavitha1** [comment]
PR merged.
