### ISSUE TITLE
[Content Bug] Unreleased section in docs release notes is confusing

### ISSUE THREAD

**Issue by mfreed** [timescale/docs#123]
https://docs.timescale.com/timescaledb/latest/overview/release-notes/

The "Unreleased" section is confusing.  Should it just be removed?

![image](https://user-images.githubusercontent.com/205086/121462582-d2862100-c97e-11eb-93b4-f18aa2df4b3f.png)

**Comment by Loquacity** [comment]
Is it supposed to be something like a backlog?

**Comment by ryanbooz** [comment]
There has been ongoing discussion in multiple teams about having a public roadmap that's very high-level, not unlike the bullet points that we seem to put here. I think it would be enough to simply point to that when it's available.

**Comment by Loquacity** [comment]
cc @NunoFilipeSantos Do you want to do these updates, or should I?

**Comment by NunoFilipeSantos** [comment]
Unreleased usually means it didn't make the cut in time of the release.
The Database team are the ones that historically have chose to use that.

@mkindahl @erimatnor and @svenklemm WDYT?

**Comment by mkindahl** [comment]
@NunoFilipeSantos This seems like a mistake. We have an "Unreleased" section in our changelog where we add items that have been pushed but not yet released. The changelog should typically be edited for the actual release to not include this section.

I note that there is no "Unreleased" section in the page referenced above, so we can probably close this.

**Comment by NunoFilipeSantos** [comment]
Just noticed how old the ticket is. There is no Unreleased section now. :)
Please close it.

**Comment by svenklemm** [comment]
I think its probably copy/paste error because we have unreleased section in the CHANGELOG.md in repo but that should not make it into any official documentation
