### ISSUE TITLE
[Docs RFC] Find the detailed size of a distributed hypertable

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#1235]
# Describe change in content, appearance, or functionality

Add information to https://docs.timescale.com/api/latest/hypertable/hypertable_detailed_size/ about using on distributed hypertables.

# Subject matter expert (SME)

@gayyappan 

# Deadline

[When does this need to be addressed]

# Any further info

[Link to community Slack thread](https://timescaledb.slack.com/archives/C5XABBWV7/p1653956964387569)

**Comment by charislam** [comment]
@gayyappan this is what the docs currently say on the topic:

> All sizes are reported in bytes. If the function is executed on a distributed hypertable, it returns size information as a separate row per node, including the access node.

Do you think this is sufficient, or do we need to add something else?

**Comment by Loquacity** [comment]
I think we can consider that the existing content covers it.
