### ISSUE TITLE
[Docs RFC] Document need to restart when updating `max_worker_processes`

### ISSUE THREAD

**Issue by charislam** [timescale/docs#1236]
# Describe change in content, appearance, or functionality

In order for the `max_worker_processes` to automatically adjust as documented, the PostgreSQL service must be restarted.

[Slack thread](https://iobeam.slack.com/archives/C0J94TE4F/p1656089350536189)

Update: see #1343 

# Subject matter expert (SME)

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by ortyb9488** [comment]
hı

**Comment by ortyb9488** [comment]
you can account number
