### ISSUE TITLE
The functionality does not work when changing the type of license

### ISSUE THREAD

**Issue by Aleksey-10081967** [timescale/docs#1255]
Hello.
The developers have installed timescaledb 2.5.2 of the Apache license for PostgreSQL 13. The Zabbix 5.4 database has been converted.
When switching to Zabbix 6.0, some of the functionality does not work in TimeScaleDB(compression, jobs).
Next, the installation of timeslakedv 2.7 was performed with the required license and ALTER EXTENSION timescaledb UPDATE was performed on the database Zabbix.
After updating Zabbix to version 6.0, it turned out that at least jobs did not appear.
Tell me how to solve the problem with non-working functionality of timescaledb.

**Comment by Loquacity** [comment]
Hi @Aleksey-10081967 I recommend you jump into our [Community forum or Slack channel](https://www.timescale.com/community) with help on this. All the best!
