### ISSUE TITLE
[Docs RFC] Promscale How-to Guides

### ISSUE THREAD

**Issue by Rajakavitha1** [timescale/docs#1276]
# Describe change in content, appearance, or functionality
Rewrite the existing guides using the how-to template.

How-to Guides
* Migrate existing data
* Backup and Restore
* Upgrade Promscale
* Monitor Promscale

# Subject matter expert (SME)

@ramonguiu 

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
Closing this for now, we can revisit at a later date.
