### ISSUE TITLE
[Content Bug] Mention that creating a unique index with "transaction per chunk" isn't supported

### ISSUE THREAD

**Issue by janko** [timescale/docs#1293]
# Describe the bug

Trying to create a unique index with "transaction per chunk" option fails as not being supported.

## What do the docs say now?

The docs say that this option works for `CREATE INDEX` command.

## What should the docs say?

They should mention that it doesn't work for unique indices, and possibly explain why, given that this is meant to be a replacement for `CONCURRENTLY`, which does support unique indices AFAIK. I'm not sure what are my options now for safely creating a unique index to a live production hypertable.

# Page affected

https://docs.timescale.com/api/latest/hypertable/create_index/

# Version affected

2.7.0

**Comment by Loquacity** [comment]
@jfjoly Are you able to help here? Or point me to someone who can?

**Comment by jfjoly** [comment]
@janko have you tried with `USING BRIN` ?
This other issue suggests that it's working. We can make it clearer in the doc. 
https://github.com/timescale/docs/issues/1319

**Comment by Loquacity** [comment]
I have verified both of the create index commands given in the docs, and they both appear to work as expected.
