### ISSUE TITLE
[Docs RFC] Update Tobs docs by replacing CLI with Helm (as part of CLI deprecation)

### ISSUE THREAD

**Issue by Rajakavitha1** [timescale/docs#1299]
# Describe change in content, appearance, or functionality

https://github.com/timescale/tobs/issues/476

Advocate helm-based installation in all our docs.

Below are the docs pages that need refactoring:
[Tobs installation guide](https://docs.timescale.com/promscale/latest/installation/tobs/#configure-tobs-for-your-kubernetes-cluster)
[Tobs CLI configuration options](https://docs.timescale.com/promscale/latest/tobs/use/#primary-tobs-commands)
Tobs docs in Github
# Subject matter expert (SME)

@onprem 

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
@ramonguiu Is there a deadline for this content? Just trying to plan work over the next couple of weeks, we have a fair bit coming down the pipe and an offsite to deal with.

**Comment by VineethReddy02** [comment]
@Rajakavitha1 The assignee should be @onprem, for him to track down this work.

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 The assignee should be @onprem, for him to track down this work.

Just assigned it to @onprem. However, for tracking, I have also assigned him as a reviewer for the related PR.

**Comment by Rajakavitha1** [comment]
Closing this issue because the Tobs CLI deprecation and Tobs Helm installation are now live on the website.
