### ISSUE TITLE
[Docs RFC] Backup and restore: add example how to backup from a remote server (eg. Timescale Cloud)

### ISSUE THREAD

**Issue by zseta** [timescale/docs#1313]
# Describe change in content, appearance, or functionality

On this page: https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore/ we describe how to back up a database. It'd be helpful for users if we also add an example where the database server is a remote server (eg.: in the case of Timescale Cloud).

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
This is probably a good use of our new Cloud admonition - make sure we sprinkle a couple around to move people over to the Cloud docs.

**Comment by Rajakavitha1** [comment]
Hi @zseta and @Loquacity !!! the backups on Timescale Cloud are done automatically and are already have a Cloud admonition in that lets the users know about not having to do a manual backup. Although, one could create a backup from a remote Timescale Cloud we would be sending two contradicting messages in the page.

What might be worth adding  as an example maybe how to backup a TimescleDB that is hosted on Digital Ocean, AWS or other cloud providers. Would love to hear your thoughts!!!

**Comment by zseta** [comment]
Hi @Rajakavitha1 

> just a note that reads to backup from a remote server use: "pg_dump -h <remote_host> -p -U -f mydb.bak mydb "

Yes this is exactly what I meant :)

**Comment by Rajakavitha1** [comment]
Closing this issue because the related PR has been merged
