### ISSUE TITLE
[Feedback] Check Docker container name

### ISSUE THREAD

**Issue by sunny-r** [timescale/docs#1314]
# Feedback

## What are we doing well and not well?

- [X] It's easy to find information I need.
- [ ] It's _not_ easy to find information I need.

- [X] Instructions are clear.
- [] Instructions are unclear.

## How could we improve the Timescale documentation site?

The docs are quite good, it's just that the docker container listed is 

timescale/timescaledb-ha:pg14-latest

but i think it should be:

timescale/timescaledb-ha:latest-pg14

**Comment by Loquacity** [comment]
Thanks for the feedback @sunny-r! We'll put this into our backlog to get it checked out for you 👍
