### ISSUE TITLE
[Site Bug] Prometheus/Promscale confusion on page: /promscale/latest/scale-ha/high-availability/

### ISSUE THREAD

**Issue by paulfantom** [timescale/docs#1322]
_Use this template for reporting bugs in the docs._

# Describe the bug

There are multiple bugs here:

1) Mixing "prometheus HA" and "promscale HA" concepts across the whole doc which can lead to confusion at times.
2) Docs don't specify how to run promscale in HA with 1 prometheus that sends data to the promscale cluster. Such a scenario shouldn't be uncommon for larger edge deployments.
3) Requirement of "To run Promscale in HA mode, you need multiple Prometheus instances running as a cluster." is unclear and most likely incorrect as "prometheus HA" has little to do with "promscale HA".
4) Showing 3 prometheus replicas as "prometheus HA" IMHO shouldn't be encouraged as it is not a a recommended way to run prometheus in HA. It would be much better to show how a promscale cluster can ingest data from a cluster A with 1 prometheus replica and from cluster B with 2 prometheus replicas at the same time.
5) Sentence below should specify which "cluster" prometheus should send data to. Especially since prometheus can nowadays receive data from other prometheus servers.

> To process data from Prometheus running in HA mode, Prometheus must be configured to communicate which cluster it belongs to.

6) This is factually not correct:

> If you are using the [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator#prometheus-operator), you can set it with these configuration parameters:
>
> ```
> replicaExternalLabelName: "__replica__"
>   prometheusExternalLabelName: "cluster"
>```

Those options are for kube-prometheus-stack helm chart, not prometheus-operator. In case of the prometheus-operator usage, those parameters are very different and are part of `Prometheus` Custom Resource specified as:
```
prometheusSpec:
  replicaExternalLabelName: "__replica__"
  externalLabels:
    cluster: "SOME_NAME"
```
Note: prometheus-operator does not set the `cluster` label by default.

Nits:

1) It would be nice to clarify what happens if `__replica__` label is the same.

> Two Prometheus instances running as part of a HA cluster must send the same cluster label and different __replica__ labels.

2) It would be good to clarify which replica, "prometheus" or "promscale" in:

> Promscale automatically elects a single replica in each cluster as the current leader. Only data sent from that replica is ingested. If that leader replica stops sending data, then a new replica is elected as the leader.

IMHO it would be best to rewrite this doc and split it in two. One handling issue of ingesting data from "prometheus HA" deployments (which this doc is mostly about) and the other treating about actual "promscale HA" deployment.

## What should the docs say?

# Page affected

https://docs.timescale.com/promscale/latest/scale-ha/high-availability/#leader-election-using-external-labels

# Version affected

latest

# Subject matter expert (SME)

@paulfantom @VineethReddy02 

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

cc @ramonguiu

**Comment by Rajakavitha1** [comment]
HI @VineethReddy02 could you please provide the technical inputs and the changes that need to be made in a PR. The docs team can work on the language, grammar, and style guide edits.
