### ISSUE TITLE
[Site Bug] Problem with replication instructions on page: /timescaledb/latest/how-to-guides/replication-and-ha/configure-replication/

### ISSUE THREAD

**Issue by Andi2405** [timescale/docs#1323]
_Use this template for reporting bugs in the docs._

# Describe the bug

The example master configuration says that only one replication slot is allowed and only one wal sender. The next step is to create the single allowed replication slot. Then pg_basebackup is used which implicitly creates a temporary replication slot on the master but since the single allowed slot is already used, this will fail.

## What do the docs say now?

So to wrap up:

1. allow just a single wal sender and replication slot
2. create a replication slot
3. use pg_basebackup (which implicitly creates another slot)

## What should the docs say?

I think there are three ways to solve this:

1. just change the order of the steps: if you set the config on the master as described you could then use pg_basebackup and as the last step create the replication slot on the master
2. change the example master config to allow at least 2 slots and wal senders
3. I guess one could also use the pg_basebackup flags and parameters to use the just created replication slot instead of a temporary one (see --slot parameter on [pg_basebackup man page](https://www.postgresql.org/docs/current/app-pgbasebackup.html) )

# Page affected

[https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/configure-replication/](https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/configure-replication/)

# Version affected

current version as of 15.07.2022

# Subject matter expert (SME)

not known

**Comment by Loquacity** [comment]
@jfjoly Can you recommend an SME for me here, please?
