### ISSUE TITLE
[Docs RFC] lttb()

### ISSUE THREAD

**Issue by Rajakavitha1** [timescale/docs#1328]
# Describe the change in content, appearance, or functionality
Document sample usage to fetch multiple downsampled time series in a single query. Here's the
[Slack Message](https://timescaledb.slack.com/archives/C02Q1LWMG3W/p1658138949803199)
# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
We don't seem to be able to get a good example here. I'm killing this for now.
