### ISSUE TITLE
[Feedback] Documentation: apt-key is deprecated

### ISSUE THREAD

**Issue by antylama** [timescale/docs#1329]
# apt-key is deprecated

## How could we improve the Timescale documentation site?

The ```apt-key``` is deprecated in Ubuntu 22.04. Please update documentation (https://docs.timescale.com/install/latest/self-hosted/installation-debian/#install-self-hosted-timescaledb-on-debian-based-systems), maybe like this:

```bash
wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo sh -c "gpg --dearmor > /etc/apt/trusted.gpg.d/timescaledb.gpg"
```

**Comment by Rajakavitha1** [comment]
Thank you @antylama  for raising the issue. It has now been addressed in https://github.com/timescale/docs/pull/1335
