### ISSUE TITLE
defining procedure docs confusing

### ISSUE THREAD

**Issue by davidkohn88** [timescale/docs#1331]
# Feedback
On the page: https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/create-and-register/#defining-a-procedure

The text doesn't really help me understand what a procedure or function is, or why I'm doing this. It gives no context and both is confusing in terms of the order of operations and in terms of the language that we use to describe things. Specifically: 

> To create an action, first write the commands you want your [function](https://www.postgresql.org/docs/current/sql-createfunction.html) or [procedure](https://www.postgresql.org/docs/current/sql-createprocedure.html) to execute. Then wrap your commands in a CREATE OR REPLACE statement. You can also define the language of your commands in this statement. The example below uses PLPGSQL.
> 
> The outer statement contains the action signature: (job_id INT, config JSONB). Include the signature literally. Don't replace with an actual job ID or config object. You define config when you register your job. job_id is also automatically generated then.

Some specifics:

1) Wrapping commands in `CREATE OR REPLACE` is a very confusing way of describing this. It's also not entirely true for many PLPGSQL functions and is just confusing generally. 
2) Action signature is a term we introduce here without defining. And I'm not sure if it's used anywhere else in the docs. I don't mind it as a term, but I think we should note where it comes from, and what a function signature is. 
3) We don't describe what the action signature allows you to do, ie it allows you to pass arguments to the function. We just say we should include it. This is a *very* common pattern in all sorts of programming languages in terms of defining a function with its signature that tells you the arguments it takes and then you pass the values during execution. I think we can lean on those concepts. 

There are a few other things that I would suggest here, I'm happy to take a stab at rewriting if you'd like.

**Comment by Loquacity** [comment]
@davidkohn88 It could take us a little while to get to this, if you want to make a start, please go ahead 👍
