### ISSUE TITLE
[Feedback] minor typo

### ISSUE THREAD

**Issue by jansichermann** [timescale/docs#1334]
# Feedback

## What are we doing well and not well?

- [x] It's easy to find information I need.
- [ ] It's _not_ easy to find information I need.

- [x] Instructions are clear.
- [ ] Instructions are unclear.

## How could we improve the Timescale documentation site?

Just a minor typo on https://docs.timescale.com/api/latest/continuous-aggregates/drop_materialized_view/#drop-materialized-view-continuous-aggregate 
The description of the `<view_name>` parameter should read "... to be dropped" not "... to be created."

**Comment by Rajakavitha1** [comment]
Thank you for raising the issue. It has now been addressed in https://github.com/timescale/docs/pull/1335

**Comment by Rajakavitha1** [comment]
HI @jansichermann !!!Closing this issue for now. Please feel free to open other issues that you may find in the documentation.
