### ISSUE TITLE
Update compression docs to mention automated decompress when ingesting older data.

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#135]
Oh, I'm sorry for not being on time here @Loquacity.
 I mean "seamless" that the latest version can automatically decompress the chunk in real-time to insert data into some compressed chunk and backfill it as "compressed" while in previous versions we need to: "decompress manually, insert data, compress manually".

_Originally posted by @jonatas in https://github.com/timescale/docs/pull/104#discussion_r651373606_

**Comment by Loquacity** [comment]
Demo'd in all-hands on 2021-06-17

**Comment by jonatas** [comment]
@gayyappan confirmed this issue is no longer valid as we do not have automated decompress.
