### ISSUE TITLE
[Site Bug] Add more detail to Python Quick Start /timescaledb/latest/quick-start/python/

### ISSUE THREAD

**Issue by barbodSN** [timescale/docs#1350]
# Describe the bug

In the Python Quick Start, give more explanation. Include the result, including how to see the table, and how to print it?

(Edited by Lana for clarity)

## What should the docs say?

# Page affected

[Provide the URL to the page you noticed the bug on]

# Version affected

[Which version of the site you noticed the bug on]

# Subject matter expert (SME)

@zseta @ryanbooz 

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
@zseta @ryanbooz Can you provide some additional info here please?
