### ISSUE TITLE
[Feedback]

### ISSUE THREAD

**Issue by barbodSN** [timescale/docs#1351]
# Feedback

## What are we doing well and not well?

- [ ] It's _not_ easy to find information I need.

- [ ] Instructions are unclear.

## How could we improve the Timescale documentation site?

Explain better and have a final code all together and screenshots of the result and how the table will change

**Comment by Rajakavitha1** [comment]
Thank you @barbodSN  for providing the feedback. Closing this issue for now. Because it is a duplicate of https://github.com/timescale/docs/issues/1350.
