### ISSUE TITLE
[Site Bug] Issue with the page: /getting-started/latest/add-data/

### ISSUE THREAD

**Issue by khalidabuhakmeh** [timescale/docs#1354]
_Use this template for reporting bugs in the docs._

# Describe the bug

The `day_volume` column in the dataset is empty.

## What do the docs say now?

There should be data in the CSV for the `day_volume` column.

## What should the docs say?

The docs themselves are "fine", but they don't make sense when the column is empty. 
The lack of `day_volume` data breaks the rest of the guide. 

# Page affected

[Provide the URL to the page you noticed the bug on]

https://docs.timescale.com/getting-started/latest/add-data/#next-steps

# Version affected

[Which version of the site you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

![Screenshot 2022-07-26 at 09 34 44](https://user-images.githubusercontent.com/228256/181019099-5fda9297-820d-47a3-beb9-e3aa8c3801bc.png)

# Any further info

🆒 🫘 (Cool beans)

**Comment by ryanbooz** [comment]
@khalidabuhakmeh - thanks for submitting the issue. As we mention in the [docs for this column](https://docs.timescale.com/getting-started/latest/add-data/#table-details), this data is only populated by our trading data provider during trading hours. In our case this data is for U.S. markets, which means 9:30am - 4:00pm Monday-Friday.

Any volume after hours is not provided. While I can't speak to why this is the case for Twelve Data, they're allowing us to provide the limited, real-time data to users for free which is a great tool for everyone!

Feel free to look at the [websocket API ](https://twelvedata.com/docs#real-time-price-websocket)that we're using, or the rest of the Twelve Data API for more info.
