### ISSUE TITLE
[Feedback]

### ISSUE THREAD

**Issue by barbodSN** [timescale/docs#1355]
# Feedback

## What are we doing well and not well?

- [ ] It's _not_ easy to find information I need.

- [ ] Instructions are unclear.

## How could we improve the Timescale documentation site?
Please provide an email address for whenever we have a question we can ask 😭

**Comment by charislam** [comment]
Thanks for your feedback, @barbodSN! We'll definitely keep it in mind as we work on improving our docs site!

If you have a question for our subject matter experts, perhaps our [community Slack](https://slack.timescale.com/) may be useful?
