### ISSUE TITLE
[STANDING ISSUE] Style and Word Usage updates 

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#1369]
_Add comments to this issue as you come across things that should be noted in the style guide, WUG, or in our linter. This issue will be groomed regularly and the updates made in bulk._

**Comment by Loquacity** [comment]
Add `above` and `below` to `next` and previous` directional entries.

**Comment by Loquacity** [comment]
Declare if procedure titles go inside or outside procedure tags.

**Comment by Loquacity** [comment]
Add `tobs` (all lower case)

**Comment by Loquacity** [comment]
Add `once` ("Once you have ..." etc). Recommend `when`.

**Comment by Loquacity** [comment]
`superuser` or `super user` ?

**Comment by Loquacity** [comment]
Bare metal (noun)
bare-metal (adjective)

**Comment by Loquacity** [comment]
Cybersecurity. One word.

**Comment by Loquacity** [comment]
Appears

**Comment by charislam** [comment]
Add DNS and REST to the list of accepted acronyms

**Comment by Loquacity** [comment]
Log in: Verb
Login: Adjective

**Comment by Loquacity** [comment]
Fix the bare-metal/baremetal entry

![image](https://user-images.githubusercontent.com/3914967/186341609-b7a9b50f-646c-4872-b5b1-78f6a1ba3f87.png)

**Comment by Loquacity** [comment]
We don't use `$`, `#`, or `sudo` in command blocks.

**Comment by Loquacity** [comment]
When referring to plain-old boring PostgreSQL, in order to differentiate it from Timescale, don't use `vanilla`. Instead, use `standard PostgreSQL`.

Additionally, if we don't already have it: `PostgreSQL`, never Postgres.

**Comment by Loquacity** [comment]
fail over (verb), failover (noun, adjective)

**Comment by Loquacity** [comment]
Frontend/Backend, per https://iobeam.slack.com/archives/C0J94TE4F/p1669229105071679

**Comment by Loquacity** [comment]
Determine which of AWS and GCP need to be expanded: https://github.com/timescale/docs/pull/1816#discussion_r1035763064

**Comment by Loquacity** [comment]
Add linting for "via" (I thought we already did this?)

**Comment by Loquacity** [comment]
Data set, or dataset? https://www.zumolabs.ai/post/2020/11/09/is-it-data-set-or-dataset

**Comment by Loquacity** [comment]
Add hypershift to the accepted words list

**Comment by Loquacity** [comment]
Add guidance about using bullets vs numbered lists ("is order important")
