### ISSUE TITLE
[Site Bug] Bad link on page: /timescaledb/latest/how-to-guides/hypertables/change-chunk-intervals/

### ISSUE THREAD

**Issue by thedanielhanke** [timescale/docs#1372]
# Describe the bug

wrong anchor linking. the anchor `#best-practices` does not exist on target site.

## What do the docs say now?

```
For more information, see [best practices for time partitioning](https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/about-hypertables#best-practices).
```

## What should the docs say?

`#best-practices` should be updated to `#best-practices-for-time-partitioning`

```
For more information, see [best practices for time partitioning](https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/about-hypertables#best-practices-for-time-partitioning).
```

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/change-chunk-intervals/

# Version affected

latest

-----

btw: i`d rather conrtibute a linter/script preventing/finding these kind of issues. would that help? if so, what are the requirements to care for? language of choice?

cheers

**Comment by Loquacity** [comment]
Hi @thedanielhanke Thanks for raising this issue! As for the linting, while I really appreciate the thought, we already run a bunch of linting over our internal tools repo, which we are constantly updating and tweaking. You'll see it in action if you contribute a PR.
