### ISSUE TITLE
[Bug/Typo] Broken Link in Ingesting Data Page

### ISSUE THREAD

**Issue by blueelvis** [timescale/docs#139]
**Add the appropriate label(s) -->**

**Describe the bug**
There is a broken link on the Ingesting Data page. Broken link - [https://docs.timescale.com/timescaledb/latest/how-to-guides/writing-data/](url)

**Location**

https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data

The `Writing Data` link in the first paragraph is broken.

**Screenshots**

![image](https://user-images.githubusercontent.com/6985763/122554337-78f4b500-d056-11eb-94d6-231520a4075b.png)

**Device and browser**

Desktop

**Comment by Loquacity** [comment]
Thanks for the report!
