### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/upgrades/upgrade-docker/

### ISSUE THREAD

**Issue by g8rpal** [timescale/docs#1399]
_Use this template for reporting bugs in the docs._

# Describe the bug

An error occurred when executing the SQL command:
CREATE EXTENSION IF NOT EXISTS timescaledb-toolkit

ERROR: syntax error at or near "-"
  Position: 43

## What should the docs say?

# Page affected

[Provide the URL to the page you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by charislam** [comment]
Thanks for the report!
