### ISSUE TITLE
[Bug/Typo] Broken Link in Enable node communication Page

### ISSUE THREAD

**Issue by ffutop** [timescale/docs#140]
# Describe the bug

This link is broken. https://docs.timescale.com/timescaledb/latest/getting-started/setup-multi-node-basic/ 

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/multi-node-setup/node-communication/#setting-up-additional-roles

# Version affected

latest

# Screenshots

![image](https://user-images.githubusercontent.com/16443058/122703531-619b0f00-d284-11eb-8c3c-357c31b6d384.png)

**Comment by Loquacity** [comment]
Thanks for the report!
