### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/ami/installation-ubuntu-ami/

### ISSUE THREAD

**Issue by lchiriac-biophy** [timescale/docs#145]
_Use this template for reporting bugs in the docs._

# Describe the bug

Link not working
![image](https://user-images.githubusercontent.com/83968015/123686567-eefad800-d81d-11eb-8db2-28dfba1614f8.png)

**Comment by Loquacity** [comment]
Duplicate of https://github.com/timescale/docs/issues/148
