### ISSUE TITLE
[Docs RFC] Update an edge case around using Continuous-Aggregate and troubleshooting 

### ISSUE THREAD

**Issue by hardikm10** [timescale/docs#1451]
# Describe change in content, appearance, or functionality

(Initiated w.r.t https://github.com/timescale/Support-Dev-Collab/issues/528#issuecomment-1212964540)

When you create a C-Agg, the initial value for the watermark might actually be in the future, depending on the size of the bucket, and the current time, and the data in the hypertable. Any inserts/updates to the hypertable before the watermark doesn’t land in the C-Agg even with the realtime aggregation turned ON. A user can perceive this a C-aggs not working.

The issue is described at with reproducible example and workaround at https://github.com/timescale/Support-Dev-Collab/issues/528

# Subject matter expert (SME)

@mfundul 

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by charislam** [comment]
Thanks for bringing this to our attention, @hardikm10! We can certainly document the workaround.

Just so I can provide the most helpful information:
Under what circumstances is the initial watermark in the future? Does this occur whenever there is data within the last hypothetical bucket (the bucket that includes `now()`)?

**Comment by mfundul** [comment]
> Does this occur whenever there is data within the last hypothetical bucket (the bucket that includes `now()`)?

I think this is an accurate description of the issue, under the assumption that we're using `now()` as our time dimension when inserting new data. In theory there could also be integer time dimensions, or historical timestamps such that `now()` is not relevant, if the actual "now" of the newly inserted data is e.g. 2000 years in the past.
