### ISSUE TITLE
[Feedback] Page: /install/latest/installation-docker/

### ISSUE THREAD

**Issue by FireHelmet** [timescale/docs#1452]
Dear timescale team,

I'm a new uer of timescaledb and I see a typo in your documentation about docker install. The tag indicated in each code block is not equal to the tags in the hub.docker.com repo.

as an example in doc page : pg14-latest
as an example in hub.docker.com page: latest-pg14

Thanks!

**Comment by charislam** [comment]
Hi @FireHelmet, thanks for the report! It can get pretty confusing as we have two TimescaleDB images with two different Docker tag formats. With TimescaleDB HA (recommended), it is `pg14-latest`, and with the lightweight TimescaleDB, it is `latest-pg14`.

If you could be kind enough to point me to where the error is, I can make sure we don't "fix" the wrong thing! :)

**Comment by FireHelmet** [comment]
Hi @charislam sure ! Please look the code block 
`docker run -d --name timescaledb -p 5432:5432 \
-v /your/data/dir:/var/lib/postgresql/data \
-e POSTGRES_PASSWORD=password timescale/timescaledb:pg14-latest `

in page https://docs.timescale.com/install/latest/installation-docker/

so that should be:

`docker run -d --name timescaledb -p 5432:5432 \
-v /your/data/dir:/var/lib/postgresql/data \
-e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg14`

**Comment by charislam** [comment]
Thanks so much! That one must have escaped us :) we'll fix it right away

**Comment by FireHelmet** [comment]
You’re welcome!
