### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/continuous-aggregates/drop-raw-data/

### ISSUE THREAD

**Issue by eaddingtonwhite** [timescale/docs#146]
_Use this template for reporting bugs in the docs._

# Describe the bug
Link to Data retention doc is broken
Links to:
https://docs.timescale.com/timescaledb/latest/how-to-guides/data-retention-with-continuous-aggregates/

## What do the docs say now?

<img width="750" alt="Screen Shot 2021-06-28 at 8 51 14 PM" src="https://user-images.githubusercontent.com/5491827/123734667-972a9400-d852-11eb-9003-408b216aab65.png">

## What should the docs say?

'data retention documentation' should link to proper page

# Page affected
https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/drop-raw-data/

# Version affected

[Which version of the site you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
This will be fixed when PR #138 merges. Any fix we do before that will cause conflicts.
