### ISSUE TITLE
Add documentation for 1-step policy management for CAggs

### ISSUE THREAD

**Issue by RafiaSabih** [timescale/docs#1476]
Please add the documentation for the newly added feature of 1-step policy for CAggs. Commit details for the same is as follows,
https://github.com/timescale/timescaledb/commit/bca65f46975f61e36e2ce57dc1ae7d80d6cccf05
https://github.com/timescale/timescaledb/commit/16fdb6ca5e3a42c120a45c7dc635e03c12f4b2e9

**Comment by charislam** [comment]
To-do list for this:

Document API functions:
- [ ] **Changed** `remove_continuous_aggregate_policy`
- [ ] **New** `timescaledb_experimental.add_policies`
- [ ] **New** `timescaledb_experimental.remove_policies`
- [ ] **New** `timescaledb_experimental.remove_all_policies`
- [ ] **New** `timescaledb_experimental.alter_policies`
- [ ] **New** `timescaledb_experimental.show_policies`

Update how-to guides:
- [ ] Continuous aggregates
- [ ] Compression
- [ ] Retention

Possible points of confusion:
Refresh creates a cagg, but compression and retention work on the original hypertable.
