### ISSUE TITLE
[Feedback] Add content about time_bucket_range on page: /timescaledb/latest/how-to-guides/hyperfunctions/counter-aggregation/counter-aggs/

### ISSUE THREAD

**Issue by nagaem** [timescale/docs#1480]
Attempting to run exactly the commands in the example to set up a counter aggregate resulted in the following error message:

```
ERROR:  function time_bucket_range(interval, timestamp with time zone) does not exist
LINE 4:         counter_agg(ts, val, time_bucket_range('15 min'::int...
                                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
I can't find any documentation on the `time_bucket_range` function in the hyperfunctions documentation. 

I am using the `timescaledb-ha` docker image, which I believe comes with toolkit enabled.

**Comment by Loquacity** [comment]
@davidkohn88 Can you act as SME on this one?

**Comment by Loquacity** [comment]
This has since been updated.

**Comment by davetapley** [comment]
@Loquacity I just ran in to this as `time_bucket_range` is [still mentioned in the docs](https://github.com/timescale/docs/search?q=time_bucket_range) but per https://github.com/timescale/timescaledb-toolkit/issues/49 and [this Slack thread](https://timescaledb.slack.com/archives/C63MYDZ35/p1642118640034300) it's in the `toolkit_experimental` schema.

**Comment by Loquacity** [comment]
All the hyperfunction API docs are in the process of being reworked now. This discrepancy will be fixed in due course as that progresses.
