### ISSUE TITLE
[Site Bug] Clarify backup content on page: /timescaledb/latest/how-to-guides/backup-and-restore/troubleshooting/

### ISSUE THREAD

**Issue by jlsevillano** [timescale/docs#1484]
_Use this template for reporting bugs in the docs._

# Describe the bug

I have created a hypertable and added a compression policy. All works fine. After that i try to test the backup and restore process following the Guide from TimescaleDB Docs.
pg_dump display the errors and did the .bak
But when I try to restore, it done but only the data outsite of the compression (not in chunks). I'm using Ubuntu 22.04 + Postgres 14 + TimescaleDB 2.7.2

**Comment by Loquacity** [comment]
Confirmed with @svenklemm and @noctarius that you can dump compressed chunks without decompression.
