### ISSUE TITLE
[Content Bug] Minimum required version is wrong

### ISSUE THREAD

**Issue by kohenkatz** [timescale/docs#152]
# Describe the bug

The documentation lists PostgreSQL version requirements that are too low.

[This commit](https://github.com/timescale/timescaledb/commit/9b5b2dc67a97af96ebdfe800289ef787fd8ae00b) changes the minimum required version when using 13.x to 13.2, but the documentation does not say that 13.0 and 13.1 cannot be used.

## What do the docs say now?

> TimescaleDB requires PostgreSQL 12 or 13.

## What should the docs say?

> TimescaleDB requires PostgreSQL 12.0+ or 13.2+.

# Pages affected

All pages in https://github.com/timescale/docs/tree/latest/timescaledb/how-to-guides/install-timescaledb *except* the Docker, AMI, Cloud, and Forge pages.

# Version affected

2.x

# Related links

- https://github.com/timescale/timescaledb/issues/3379

**Comment by Loquacity** [comment]
Ping @ryanbooz

**Comment by kohenkatz** [comment]
@Loquacity @ryanbooz I didn't want to have two PRs open at once, but I'd be happy to do a PR for this now that #151 is done.

**Comment by Loquacity** [comment]
Sure, go right ahead :)
