### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/ingest-data/ingest-kafka/

### ISSUE THREAD

**Issue by jiyeonseo** [timescale/docs#1528]
# Describe the bug

the link of JDBC Connector documentation is old version one.

## What do the docs say now?

https://docs.confluent.io/5.4.1/connect/kafka-connect-jdbc/index.html
(in the doc, `brew cask` command is no longer used) 

## What should the docs say?

https://docs.confluent.io/kafka-connectors/jdbc/current/index.html

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/ingest-kafka/

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
We don't have any control over what's written on third-party sites, and there doesn't appear to be an updated version of this document. I'm not sure we can help here.
