### ISSUE TITLE
MST Maintenance needs instructions to ALTER EXTENSION ... UPDATE

### ISSUE THREAD

**Issue by spaceshipoperator** [timescale/docs#1530]
# MST Maintenance page needs instructions for users to ALTER EXTENSION ... UPDATE following install of new version

[MST Maintenance](https://github.com/timescale/docs/blob/latest/mst/maintenance.md) documentation does not include any indication that it is necessary for users to explicitly update timescaledb extension (and/or others) _after_ maintenance updates install newer versions of binaries; specifically users must run (via psql):

`ALTER EXTENSION timescaledb UPDATE;`

## What do the docs say now?

Currently docs do not indicate need for "ALTER EXTENSION .." following maintenance, install and availability of new versions

## What should the docs say?

(see above, also) refer to [MST KB Article: Upgrading TimescaleDB version](https://kb-managed.timescale.com/en/articles/3660857-upgrading-your-timescaledb-database-version) 

# Page affected

[MST Maintenance](https://docs.timescale.com/mst/latest/maintenance/)

# Subject matter expert (SME)

Technical Services

# Screenshots

n/a

# Any further info

existing MST customers affected by lack of this information; currently need to know or search for KB

**Comment by Loquacity** [comment]
This Kbase article is due to be migrated to docs as part of the larger Kbase migration. That migration is being tracked in GDocs. Ping me if you want perms 👍

**Comment by spaceshipoperator** [comment]
I see that the KB docs have been migrated to their new home, but I think this page still needs a note that the users must run:
```ALTER EXTENSION timescaledb UPDATE;```
_after_ maintenance updates have installed a newer version
