### ISSUE TITLE
[Content Bug] incorrect time_bucket information

### ISSUE THREAD

**Issue by svenklemm** [timescale/docs#1543]
# Describe the bug
Incorrect information about time_bucket

Seems like quite a few things are incorrect about in the time_bucket documentation

## What do the docs say now?
- states that month/year/century is not supported 
- talks about interval time inputs
- does not mention timezone variant of time_bucket
## What should the docs say?
- time_bucket support month/year/century
- should mention timezone variant of time_bucket
- interval time input should probably be date/timestamp/timestamptz/integer instead

# Page affected
https://docs.timescale.com/api/latest/hyperfunctions/time_bucket/#optional-arguments-for-interval-time-inputs

# Subject matter expert (SME)

@svenklemm 

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by charislam** [comment]
Thanks for the issue @svenklemm! I think most of these issues are addressed in the TimescaleDB 2.8 PR, right? I temporarily reverted as a result of a discussion about docs updates not being in sync with Timescale Cloud updates, but it's back now: https://github.com/timescale/docs/pull/1553

I think we just need to fix the time input data type
