### ISSUE TITLE
[Feedback] Page: /api/latest/hyperfunctions/time_bucket_ng/

### ISSUE THREAD

**Issue by psztoch** [timescale/docs#1544]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

time_bucket_ng_range function should be added.

**Comment by Loquacity** [comment]
Thanks for the feedback! Looks like we got two issues to update the time_bucket function content, so we'll continue tracking this here: https://github.com/timescale/docs/issues/1543
