### ISSUE TITLE
[Site Bug] Update compression page to mention limitations: /timescaledb/latest/how-to-guides/compression/

### ISSUE THREAD

**Issue by mkindahl** [timescale/docs#1584]
_Use this template for reporting bugs in the docs._

# Describe the bug

No information about limitations regarding compression, especially around inserts, updates, and related things.

## What do the docs say now?

Nothing

## What should the docs say?

There should be a description of limitations with regard to compression and using compressed data. In particular:

- There is (currently) no support for deletes or updates of compressed tables
- There is (currently) no support for `ON CONFLICT DO NOTHING`
- There is currently no support for `INSERT` clauses with `RETURNING`

# Page affected

No such reference, since it's missing

# Subject matter expert (SME)

@mkindahl @svenklemm @gayyappan  

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
I think the core concepts page covers most of this, as of today.
