### ISSUE TITLE
[Site Bug] Mention multiple databases on page: /timescaledb/latest/how-to-guides/upgrades/upgrade-docker/ 

### ISSUE THREAD

**Issue by Dzeri96** [timescale/docs#1589]
# Describe the bug

This page has no mention of multiple databases.
Since PostgreSQL manages plugins per-database, the user has to update the Timescale extension in every single one, especially template1/0, which are used as bases for newly created DBs.

On the topic of the template DBs, I'm not sure how we should proceed with template0. In the 1.7.4 image, I see that it has no TS extension installed, while it does have it in the 2.8 image.
If we want to add the extension there also, connections have to be enabled temporarily.

## What do the docs say now?
There are no mentions of multiple databases.

## What should the docs say?

Perhaps we should change the last 3 steps into something like this:

```shell
for DB in $(psql -t -c "SELECT datname FROM pg_database WHERE datname != 'template0'"); do
  psql -d $DB -c "ALTER EXTENSION timescaledb UPDATE;"
done
```
_Taken from [stackoverflow](https://stackoverflow.com/questions/42139274/postgres-create-extension-all-databases)_

Additionally, it should be mentioned that the update has to be performed for each DB individually.
# Page affected

/timescaledb/latest/how-to-guides/upgrades/upgrade-docker/

**Comment by Loquacity** [comment]
This will need an SME. Perhaps @vineethapai could help us out here?
