### ISSUE TITLE
[Feedback] Page: /timescaledb/latest/how-to-guides/replication-and-ha/configure-replication/

### ISSUE THREAD

**Issue by inselbuch** [timescale/docs#1596]
### How could we improve the Timescale documentation site?

you reference a parameter in the configuration file

Set the listen_address parameter to the address of the primary database. Do not leave this parameter as the local loopback address, because the remote replicas must be able to connect to the primary to stream the WAL.

That should be

listen_addresses

-Frank

**Comment by Rajakavitha1** [comment]
Thank you @inselbuch !!! for spotting the typo. PR with the fix on the way.
