### ISSUE TITLE
[Docs RFC] Add signed certificate information, ssl connection options, and root cert bundle steps

### ISSUE THREAD

**Issue by clarkbw** [timescale/docs#1597]
Currently Timescale services in Cloud contain a self-signed certificate within the certificate chain. This situation means that you cannot connect certain services to a Timescale Cloud db service like a BI tool (PowerBI, Apache Superset) which require a fully signed certificate chain. Essentially if your web browser could connect to a Cloud postgres service right now it would complain like it does when it "doesn't trust the connection".  

We have a new system that fixes this issue. Every new Cloud service initially launches very quickly with a self-signed certificate. In the background (asynchronously) a signed certificate is requested for the service and then the service is updated with very little interruption. Connections to the service will be reset when the service is updated to a fully signed certificate chain but a simple reconnect will fix that and most connection services do this automatically. 

Beyond enabling more services to seamlessly connect to Cloud db services this also allows customers to user more secure connection configurations via the `sslmode` connection string flag.

Step 1.

```shell
openssl s_client -showcerts -partial_chain -starttls postgres \
                 -connect $SERVICE_URL_WITH_PORT < /dev/null 2>/dev/null | \
                 awk '/BEGIN CERTIFICATE/,/END CERTIFICATE/{ print }' > bundle.crt
# macos
pbcopy < bundle.crt
```

Step 2.
Paste the bundle (`bundle.crt`) which should be in your clipboard now into the large text area for https://whatsmychaincert.com/ to generate a correct chain. Make sure check the box below the text area for “Include Root Certificate”

<img width="916" alt="whatsmychaincert create bundle" src="https://user-images.githubusercontent.com/2134/190225287-1a47089c-1ceb-402c-89fb-8e80e3bde0bc.png">

Step 3.
Save the bundle which downloaded from https://whatsmychaincert.com/ into `~/.postgresql/root.crt`

Step 4.
Connect to your Timescale Cloud instance using a more strict SSL connection modes (`sslmode`) such as: `verify-ca` or the highest level `verify-full` (see all options in the [SSL Support docs](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS).

For example:
`psql "postgres://tsdbadmin@$SERVICE_URL_WITH_PORT/tsdb?sslmode=verify-full"`

Or:
`psql "postgres://tsdbadmin@$SERVICE_URL_WITH_PORT/tsdb?sslmode=verify-ca"`

☝🏼 both of with require the `~/.postgresql/root.crt` file correctly generated as described

Instead of:
`psql "postgres://tsdbadmin@$SERVICE_URL_WITH_PORT/tsdb?sslmode=require"`

Which does not require these steps listed above.

# Subject matter expert (SME)

@minkimipt 

# Deadline

ASAP 😬 

# Any further info

Timescale Internal Tracking link https://github.com/timescale/product/issues/132

**Comment by minkimipt** [comment]
@charislam just noticed. We have a typo in the section name. SLL instead of SSL:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/16339898/192335448-7b12a49f-452a-4251-977d-d67fcfc85997.png">

**Comment by charislam** [comment]
Just fixed!
