### ISSUE TITLE
Timescale DB 2.3.1

### ISSUE THREAD

**Issue by NunoFilipeSantos** [timescale/docs#160]
Updating AMIs:

- eu-central-1: ami-01149ee2f1589f9e4
- eu-north-1: ami-001b590df85e1b07d
- eu-west-1: ami-03aeb656eaa7b3e88
- eu-west-2: ami-036001e38f1774a9a
- eu-west-3: ami-034a707417a64712f
- us-east-1: ami-08caf7e46604e1195
- us-east-2: ami-063deccec7d552047
- us-west-1: ami-02e3e3080de31f4fb
- us-west-2: ami-0a8a1ee905dca7075

- [ ] PR: https://github.com/timescale/docs/pull/161

**Comment by mkindahl** [comment]
@NunoFilipeSantos This seems to be done. Do you want to close it?
