### ISSUE TITLE
[Docs RFC] Services operations - General

### ISSUE THREAD

**Issue by Rajakavitha1** [timescale/docs#1639]
# Describe change in content, appearance, or functionality

[Slack message](https://iobeam.slack.com/archives/C042G92KXHR/p1663755956525429)
The document reads: Pause service
You can pause a service if you want to stop it running temporarily. This stops your service from costing you, but the service is still available and ready to be restarted at any time.

Feedback from the customer:  I remember being told that even when a user pauses their instance they get charged for storage on Cloud but the docs don't mention this so wanted to clarify.

Page to be updated: https://docs.timescale.com/cloud/latest/service-operations/general/

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
We're going to need an SME to confirm this. Perhaps @ggodeke can help?

**Comment by jamessewell** [comment]
Fixed with docs reorg [here](https://docs.timescale.com/use-timescale/latest/services/service-management/#pause-service):

> You can pause a service if you want to stop it running temporarily. When you pause a service, you are no longer billed for compute services. However, you do need to continue paying for any storage you are using. Pausing a service ensures that it is still available, and is ready to be restarted at any time.
