### ISSUE TITLE
[Feedback] Add more examples for the Filter Clause

### ISSUE THREAD

**Issue by Rajakavitha1** [timescale/docs#1640]
May be more example about using the Filter Clause:[slack message
](https://timescaledb.slack.com/archives/C4GT3N90X/p1663256446409059?thread_ts=1663241431.053239&cid=C4GT3N90X)
```SELECT first(value,time) FILTER(WHERE value IS NOT NULL), last(value,time) FILTER(WHERE value IS NOT NULL) FROM fl;```

**Comment by Loquacity** [comment]
This is a dupe of #1620
