### ISSUE TITLE
Update Timescale Cloud / MST description in "Deployment options

### ISSUE THREAD

**Issue by carlotas19** [timescale/docs#1643]
# Describe change in content, appearance, or functionality

[Provide as much detail as you can]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
@carlotas19 Can you give us some more info here please?
