### ISSUE TITLE
[404 page Error] page resources for /timescaledb/latest/how-to-guides/backup-and-restore/timescaledb-backup not found.

### ISSUE THREAD

**Issue by Billmike** [timescale/docs#1650]
**Steps to reproduce:**

1. Visit the production site [here](https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/timescaledb-backup)

**Expected behaviour**
The user sees the relevant page for the Backup and restore guides

**Actual behaviour**
The user sees a 404 page

![Image](https://user-images.githubusercontent.com/24798364/192450235-c0e740f5-4f69-4434-a157-77bf08b570b2.png)

**Comment by Loquacity** [comment]
This probably requires a redirect. Where are you seeing this URL?

**Comment by Billmike** [comment]
This is happening in production. We setup Sentry to catch 404 errors, and this is one of the errors that was caught

**Comment by Loquacity** [comment]
> This is happening in production. We setup Sentry to catch 404 errors, and this is one of the errors that was caught

It's not a lot of use if I don't know where the dead links are being seen, though ...

**Comment by Rajakavitha1** [comment]
> > This is happening in production. We setup Sentry to catch 404 errors, and this is one of the errors that was caught
> 
> It's not a lot of use if I don't know where the dead links are being seen, though ...

@Billmike  we also searched for all references to ```/timescaledb/latest/how-to-guides/backup-and-restore/timescaledb-backup``` in our docs repo and there are no references.
