### ISSUE TITLE
[404 page error] page resources for /api/:currentVersion:/hypertable/move_chunk not found.

### ISSUE THREAD

**Issue by Billmike** [timescale/docs#1651]
**Steps to reproduce:**

1. Visit the production site [here](https://docs.timescale.com/api/:currentVersion:/hypertable/move_chunk)

**Expected behaviour**
The user sees the relevant page for the current version

**Actual behaviour**
The user sees a 404 page

![Image](https://user-images.githubusercontent.com/24798364/192451053-4ef5c9d6-5c08-4f09-8ba1-6886c32c9c11.png)

**Comment by Loquacity** [comment]
This looks like a transform problem. In the URL, `:currentVersion:` should become `latest`. https://docs.timescale.com/api/latest/hypertable/move_chunk/ Works as expected. Where are you seeing this URL?

**Comment by Billmike** [comment]
This is happening in production. We setup Sentry to catch 404 errors, and this is one of the errors that was caught

**Comment by Loquacity** [comment]
> This is happening in production. We setup Sentry to catch 404 errors, and this is one of the errors that was caught

I'm not sure why any page would be trying to load a URL that contained `:currentVersion:`. Unless @charislam has some ideas?

**Comment by charislam** [comment]
> > This is happening in production. We setup Sentry to catch 404 errors, and this is one of the errors that was caught
> 
> I'm not sure why any page would be trying to load a URL that contained `:currentVersion:`. Unless @charislam has some ideas?

The link is in a highlight, and links in highlights don't get transformed :(

**Comment by Loquacity** [comment]
> > > This is happening in production. We setup Sentry to catch 404 errors, and this is one of the errors that was caught
> > 
> > 
> > I'm not sure why any page would be trying to load a URL that contained `:currentVersion:`. Unless @charislam has some ideas?
> 
> The link is in a highlight, and links in highlights don't get transformed :(

You found it! Well done :)
