### ISSUE TITLE
[Docs RFC] Consistency with titles - sentence case vs Initial Case

### ISSUE THREAD

**Issue by jproman1** [timescale/docs#166]
**Issue:** Bottom links are half issue with consistency (Sentence case vs Initial Case).  

## What do the docs say now?

Time Series Forecasting using TimescaleDB, R, Apache MADlib and Python
Continuous Aggregates
Try Other Sample Datasets
Migrate your own Data

## What should the docs say?
Time-series forecasting using TimescaleDB, R, Apache MADlib and Python
Continuous aggregates
Try other sample datasets
Migrate your own data

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/

# Version affected

latest

# Screenshots
![Screen Shot 2021-07-09 at 12 45 48 PM](https://user-images.githubusercontent.com/80284941/125111630-21c18d80-e0b4-11eb-9bcd-1ae8e261e2a1.png)
![Screen Shot 2021-07-09 at 12 45 48 PM](https://user-images.githubusercontent.com/80284941/125115454-584dd700-e0b9-11eb-8c88-70455b57cd73.png)

**Comment by Loquacity** [comment]
Thanks! I've changed the page titles, but hadn't done the indexes.
