### ISSUE TITLE
[Content Bug]

### ISSUE THREAD

**Issue by thehatami** [timescale/docs#1667]
commands in step not loaded completely.

for ex, in steps 4-6 for self-hosted, command not shown.
[[check this page]](https://docs.timescale.com/install/latest/self-hosted/installation-source/)

**Comment by Loquacity** [comment]
Thanks for the report. This appears to be working fine now. These steps have a switcher on them so you can see commands for different operating systems. Perhaps you have a plugin or something that is blocking this functionality?

Linux:

![image](https://user-images.githubusercontent.com/3914967/193713513-820b4b73-e62c-4a67-a870-83966f41065b.png)

Windows:

![image](https://user-images.githubusercontent.com/3914967/193713543-d206c169-f05b-4ebd-a77c-0d33eb30ef95.png)
