### ISSUE TITLE
Failing link check ({{ date | date('dddd, MMMM Do') }})

### ISSUE THREAD

**Issue by thehatami** [timescale/docs#1668]
The repository 'https://ppa.launchpadcontent.net/timescale/timescaledb-ppa/ubuntu focal Release' does not have a Release file.

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

**Comment by thehatami** [comment]
im already get this error:
`Ign:8 https://ppa.launchpadcontent.net/timescale/timescaledb-ppa/ubuntu focal InRelease
Err:9 https://ppa.launchpadcontent.net/timescale/timescaledb-ppa/ubuntu focal Release
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 185.125.190.52 443]`

**Comment by Loquacity** [comment]
I'm sorry to hear you're still seeing errors. If you need help getting started, you can try asking our community: https://www.timescale.com/community/
