### ISSUE TITLE
[Site Bug] Update Telegraf tutorial now that the plugin exists. Page: /timescaledb/latest/tutorials/telegraf-output-plugin/

### ISSUE THREAD

**Issue by brun0c1ntra** [timescale/docs#1669]
_Use this template for reporting bugs in the docs._

# Describe the bug

Documentation must be updated, according to what has been described here (https://www.timescale.com/forum/t/telegraf-plugin/118/4)

## What do the docs say now?
It **is** deprecated

## What should the docs say?
It **is not** deprecated

# Page affected

[Provide the URL to the page you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Rajakavitha1** [comment]
Updated in https://github.com/timescale/docs/pull/1835. Closing this issue for now.
