### ISSUE TITLE
[Site Bug] docs say compressed chunks are immutable

### ISSUE THREAD

**Issue by abolognino** [timescale/docs#168]
_Use this template for reporting bugs in the docs._

# Describe the bug

I believe https://github.com/timescale/timescaledb/pull/3230 adds support for insert into compressed chunks

[Provide as much detail as you can]

## What do the docs say now?

the docs says compressed chunks are immutable

## What should the docs say?

the docs should explain what happens under the hood when inserting in compressed chunks

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/backfill-historical-data/

# Subject matter expert (SME)
# Screenshots
# Any further info

**Comment by Loquacity** [comment]
Closing as per discussion in #238
