### ISSUE TITLE
[Feedback]Provide pdf download of documents

### ISSUE THREAD

**Issue by ChenpiDog** [timescale/docs#1701]
### How could we improve the Timescale documentation site?

It is very slow to open timescale official website here, and sometimes there is no response for a long time. I hope timescaledb can provide pdf download of documents, which can effectively solve the difficulties I now encounter.

**Comment by charislam** [comment]
Hi @ChenpiDog, thanks so much for your feedback! We'll evaluate whether we have the resources to add PDF production to our publishing pipeline. Because Timescale documentation receives updates so frequently, this isn't entirely straightforward, but we'll definitely look into it.

In the meantime, we've just pushed some site performance improvements that should reduce the load time of our docs site. Could you let us know if you're seeing improvements on your end? It would be great to know if we're improving the real user experience.

**Comment by Loquacity** [comment]
Let's discuss at our next meeting.

**Comment by ChenpiDog** [comment]
> Hi @ChenpiDog, thanks so much for your feedback! We'll evaluate whether we have the resources to add PDF production to our publishing pipeline. Because Timescale documentation receives updates so frequently, this isn't entirely straightforward, but we'll definitely look into it.
> 
> In the meantime, we've just pushed some site performance improvements that should reduce the load time of our docs site. Could you let us know if you're seeing improvements on your end? It would be great to know if we're improving the real user experience.

Of course, I'm willing to give feedback. I'm in Chinese Mainland. It's very slow to open the timescaledb official website here.

**Comment by Loquacity** [comment]
Hi @ChenpiDog Thank you so much for bringing this issue up to us! We really appreciate your feedback. Unfortunately, our system is not well suited to PDF, and we don't currently have the ability to create or maintain PDF versions. However, we have recently found and fixed a number of issues that should make the site run a lot faster for you, and I'm hoping that this goes some way to resolving the issues you were having with the site. Are you able to take another look and let us know if you're seeing page load improvements now?

**Comment by ChenpiDog** [comment]
Let me access the website at a normal speed. I just looked at it again. The website response is still very slow. Is there any optimization method for Chinese Mainland?

**Comment by ChenpiDog** [comment]
![image](https://user-images.githubusercontent.com/55483982/198914652-1a35ba73-2dc7-4d0a-b128-e851d5b16a39.png)
I clicked on a menu at random and there was no response.

**Comment by ChenpiDog** [comment]
I tried again, and the website responded much faster than before. Now it seems that sometimes the response is fast and sometimes slow. Well, this can solve my problem.

**Comment by Loquacity** [comment]
> I tried again, and the website responded much faster than before. Now it seems that sometimes the response is fast and sometimes slow. Well, this can solve my problem.

We'll continue working on site responsiveness, I'm glad that you're starting to see some improvements!
