### ISSUE TITLE
[Site Bug] Typo on page: /timescaledb/latest/how-to-guides/query-data/advanced-analytic-queries/

### ISSUE THREAD

**Issue by 0xFFFFtheTokens** [timescale/docs#1711]
_Use this template for reporting bugs in the docs._

# Describe the bug

Title of the page is "Peform" instead of "Perform"

## What do the docs say now?

"Peform advanced analytic queries ..."

## What should the docs say?

"Perform advanced analytic queries ..."

# Page affected

[Advanced Analytic Queries Page](https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/advanced-analytic-queries/)

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
Typo is in the index, not the page itself:

![image](https://user-images.githubusercontent.com/3914967/196863168-bb4477d6-a659-4255-8da3-187ecfa3f847.png)

**Comment by 0xFFFFtheTokens** [comment]
FYI, it's also in the title of the page.
<img width="295" alt="Screen Shot 2022-10-23 at 11 58 16 AM" src="https://user-images.githubusercontent.com/105060863/197405214-e2ebcbfe-05cd-4179-bead-70ab37f83479.png">
