### ISSUE TITLE
[Content Bug]

### ISSUE THREAD

**Issue by greenweeds** [timescale/docs#1722]
# Describe the bug

Link from blog post results in not found

## What do the docs say now?

404 not found

## What should the docs say?

https://docs.timescale.com/timescaledb/latest/getting-started/create-hypertable/#chunks-and-hypertables correct page OR the blog post needs updating OR a redirect link created. Any of these. 

# Page affected

Error found from link in [this section in a blog post](https://www.timescale.com/blog/timescaledb-2-3-improving-columnar-compression-for-time-series-on-postgresql/#inserting-data-into-compressed-hypertables) "hypertable is partitioned into chunks"

**Comment by Loquacity** [comment]
This is probably because we refactored the GSG recently. Correct link is here: https://docs.timescale.com/getting-started/latest/create-hypertable/

@contentana If you can update the blog, we can put in a redirect. That way we'll tackle it from both ends 😉

**Comment by contentana** [comment]
Hi, @Loquacity! The link has been updated! Thanks for flagging it, @greenweeds! 
Updated version here: https://www.timescale.com/blog/timescaledb-2-3-improving-columnar-compression-for-time-series-on-postgresql/
