### ISSUE TITLE
[Docs RFC] Document new feature to roll uncompressed chunks into compressed ones

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#1739]
# Describe change in content, appearance, or functionality

https://github.com/timescale/timescaledb/pull/4718

> From a UX point of view, we simple add a compression with clause option compress_chunk_time_interval. The user should set that according to their needs for constraint exclusion over historical data. Ideally, it should be a multiple of the uncompressed chunk interval and so we throw a warning if it is not.

# Subject matter expert (SME)

@antekresic @mkindahl @svenklemm 

# Deadline

ASAP

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
Hi @antekresic @mkindahl @svenklemm Any update on when this feature is due?

**Comment by svenklemm** [comment]
> Hi @antekresic @mkindahl @svenklemm Any update on when this feature is due?

Will be included in 2.9
