### ISSUE TITLE
[Site Bug] Fix instructions in Lambda Tutorial, page: /timescaledb/latest/tutorials/aws-lambda/continuous-deployment/

### ISSUE THREAD

**Issue by ogauk** [timescale/docs#1744]
_Use this template for reporting bugs in the docs._

# Describe the bug

1. missing command. one can't touch main.yaml until the workflows folder exists
2. missing information - one needs to create an IAM user and give it sufficient permissions

## What do the docs say now?

1. touch .github/workflows/main.yml

## What should the docs say?

1. mkdir -p .github/workflows && touch .github/workflows/main.yml
2. should describe the process of creating an IAM user and what permissions should be attached.

**Comment by Loquacity** [comment]
All the tutorials are in the process of being updated into our new format. This includes fully testing all of the instructions. This will be updated in due course, when that happens.

**Comment by jonatas** [comment]
Thanks for caring and reporting @ogauk! As you looks an advanced user, feel free to also submit a PR with the fix of [the file](https://github.com/timescale/docs/blob/latest/tutorials/aws-lambda/continuous-deployment.md) and start contributing to us! @Rajakavitha1 would be very happy to review your changes as well 🤓

**Comment by Loquacity** [comment]
The new tutorials are live now, this should no longer be a problem.
