### ISSUE TITLE
[Docs RFC] Change Forge "Create Service" Screenshots

### ISSUE THREAD

**Issue by lukas-bernert** [timescale/docs#175]
# Describe change in content, appearance, or functionality

On [this page](https://docs.timescale.com/timescale-forge/latest/create-a-service/#step-create-your-first-service), the file `forge_create-db.png` needs to be replaced.
Going to provide the new file once released on prod.

# Subject matter expert (SME)

@lukas-bernert 

# Deadline

Week of 12th Jul. (After changes have been released to prod. ~Wed or Thu)

# Any further info

**Comment by lukas-bernert** [comment]
<img width="703" alt="Screenshot 2021-07-15 at 14 31 23" src="https://user-images.githubusercontent.com/23032575/125796443-09d190e1-b122-43ff-a31c-1a289fd568be.png">

this is the new file @Loquacity

**Comment by lukas-bernert** [comment]
The changes have been release yesterday so the file can be updated at any time now.

**Comment by Loquacity** [comment]
Edited for SUI, and updated in AWS.
