### ISSUE TITLE
[Site Bug] Bad link on page: /promscale/latest/installation/kubernetes/

### ISSUE THREAD

**Issue by jackwang713** [timescale/docs#1789]
**Incorrect file link address**

![image](https://user-images.githubusercontent.com/54341943/202887697-1844594a-de6b-4e53-9400-a0f30778b01a.png)

Promscale [values.yaml](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.yaml)

**Comment by Rajakavitha1** [comment]
Hi @jackwang713 !! the link on step 5 in https://docs.timescale.com/promscale/latest/installation/kubernetes/ opens to https://github.com/timescale/helm-charts/blob/main/charts/timescaledb-single/values.yaml.
The link that you provided also opens to: https://github.com/timescale/helm-charts/blob/main/charts/timescaledb-single/values.yaml

Closing this issue for now. Please feel free to reopen any other updates that need to be made.

**Comment by jackwang713** [comment]
The correct  link may be https://github.com/timescale/helm-charts/blob/main/charts/promscale/values.yaml

**Comment by Rajakavitha1** [comment]
Thank you @jackwang713 !!! PR on the way
