### ISSUE TITLE
[Feedback] Clarify how Promscale Connector works with Timescale Cloud, on page: /promscale/latest/installation/promscale-with-timescale-cloud/

### ISSUE THREAD

**Issue by stevecalvert** [timescale/docs#1811]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

My problem here is that the documentation is suggesting that Promscale Connector can be installed as part of the Timescale Cloud.  The first para states

"To get started with Promscale on Timescale Cloud"

 It's still not clear to me, but I'm beginning to think that is not possible, and instead it looks like Promscale (and Promscale Connector) need to be run in the customer's own Kubernetes environment whilst TimescaleDB runs in Timescale Cloud.

My confusion is compounded because the Timescale Cloud offers the ability to add a "Service", with the implication that Promscale might be a service I want to add, but the reality is that the only service on offer is the CPU that hosts the TimescaleDB backend

Is this the case?  I hope it isn't since it would be great to just point my devices (running Prometheus Agent Mode) at a scalable Promscale Connector **in the Timescale Cloud**, and not have to worry about supporting my own EKS cluster for this service (especially the worry about scaling the connector to meet the needs of an increasing number of Prometheus devices pushing up analytics)

Anyway, I think the docs need to make this clear 😄 thanks

**Comment by Rajakavitha1** [comment]
Hi @VineethReddy02  Can you please clarify this in the document?

**Comment by VineethReddy02** [comment]
Hi @stevecalvert 

Thanks for reporting this :), I will work on making this page clear from your feedback. 

First, let me explain to you our definition of Promscale: It comprises two components Connector and a Database (Promscale extension + TimescaleDB). 

Today to integrate Promscale with Timescale cloud. We offer an option to offload the Promscale data layer i.e. database to the Timescale cloud. The user has to run only the Promscale Connector (stateless service) on their end for which we will also offer customer support. However, in Q1, 2023 we will be launching the private beta for managed Promscale that offers both Promscale Connector and Database on the Timescale cloud. We can offer you a private beta in early 2023. :)

I want to offer my help with your current evaluation of Promscale as well as answer any questions you may have. We can schedule a call to discuss (https://calendly.com/vineeth97/promscale-user-sync-up) or, if you prefer, we can also continue the conversation over email.

**Comment by stevecalvert** [comment]
Thanks for responding, @VineethReddy02.  I'm hoping to arrange a call with one of your colleagues in connection with another evaluation account that we have been using, but I think I have enough information for now on this topic.
