### ISSUE TITLE
[Feedback] Make it clear that readers should contact support to restore from backup on page: /cloud/latest/backup-restore-cloud/

### ISSUE THREAD

**Issue by c-classen** [timescale/docs#1821]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

This page says that there is no need to perform manual backups and that a restore can happen regardless of a failure occurring.

However, I don't see the part of the docs where it tells me how and where I can initiate a restore and select the point in time to restore to. I think this would be the most important part of this page considering that most other parts are technical details on how the backup and recovery works.

**Comment by Loquacity** [comment]
Hi @c-classen Thanks for raising this. To restore your Cloud database from backup, you need to contact support: https://www.timescale.com/support We will update the documentation to make this clearer.

**Comment by c-classen** [comment]
Thank you for the response, though I would have hoped there would be some other way.

I would feel way more comfortable using timescale for production use cases knowing I wouldn't loose any time in case some data would accidentally be deleted and needed to be restored.

Are you considering offering something like the RDS restore mechanism where you can restore any point in time to a new database for your cloud service?

**Comment by Loquacity** [comment]
Hi @c-classen The best way to get answers to these questions would be using our [contact form](https://www.timescale.com/contact), or engaging in our [Slack or Forum](https://www.timescale.com/community).
