### ISSUE TITLE
[Site Bug] Clarify warning about install on page: /install/latest/self-hosted/installation-debian/

### ISSUE THREAD

**Issue by helix84** [timescale/docs#1828]
## What do the docs say now?

"If you have already installed PostgreSQL using a method other than the apt package manager, you could encounter errors following these instructions."

## What should the docs say?

Please clarify whether this applies only to installation from the Debian/Ubuntu archive or also to the PGDG apt repository maintained by PostgreSQL.

**Comment by Rajakavitha1** [comment]
@svenklemm Can you please clarify if the warning applies to PGDG apt repo as well?

**Comment by Rajakavitha1** [comment]
Closing this issue in lieu of https://github.com/timescale/docs/issues/1905
