### ISSUE TITLE
[Feedback] Page: /timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-auth/

### ISSUE THREAD

**Issue by sweihub** [timescale/docs#1876]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Wrong documented, please fix ! The trust authentication should be configured at the data node.
https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-auth/

`Connect to the access node with psql, and locate the pg_hba.conf file:`

should be 

Connect to the **data node** with psql, and locate the pg_hba.conf file:

**Comment by Rajakavitha1** [comment]
Hi @sweihub !!! Thank you for raising the issue. The details about data node is mentioned in step 4:
 If you have not already done so, add the data nodes to the access node. For instructions, see the [multi-node setup](https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-setup/) section.

**Comment by Rajakavitha1** [comment]
Closing this issue for now. Please feel free to reopen if any other changes need to be made.
