### ISSUE TITLE
[Feedback] Verify password auth steps on page: /timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-auth/

### ISSUE THREAD

**Issue by sweihub** [timescale/docs#1880]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Hi, would you update the "Password authentication" section, the setup steps are confusing 

1. Before calling add_data_node(...), you should instruct the user to setup the authentication
2. Using passfile, if user `postgres` not in the list, the add_data_node(...) will failed with authencation error
3. Using the `testrole` dose not work for add_data_node(...), so basicly, we have to use `postgres`, so why do we create testrole?

**Comment by Loquacity** [comment]
This seems to have been addressed in another PR. I can't see these problems in the current doc.
