### ISSUE TITLE
[Feedback] Page: /install/latest/installation-cloud-image/

### ISSUE THREAD

**Issue by eip-mambo** [timescale/docs#1882]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

![image](https://user-images.githubusercontent.com/77946305/208572078-1322dd0c-0c05-46a0-9798-f55428465e82.png)

I'm not found AMI based ubuntu.
Region : ap-northeast-2 (Asia/Seoul)

A list of supported regions must be listed.

**Comment by Loquacity** [comment]
Hi, thanks for the report! Sadly, we don't have any control over what Amazon AMIs are available for you. If you need some additional help, try checking out our Timescale Community, and hopefully they can help you come up with a solution that works for you: https://www.timescale.com/community/
