### ISSUE TITLE
[Feedback] Page: /timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore/

### ISSUE THREAD

**Issue by ivdok** [timescale/docs#1886]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

No explanation on what to do if "org.postgresql.util.PSQLException: ERROR: invalid INSERT on the root table of hypertable "_hyper_1_10_chunk"" error appears after restoring from file dump outside psql shell. SELECT timescaledb_post_restore(); doesn't work.

**Comment by Loquacity** [comment]
Add troubleshooting section. Will need an SME, though.

**Comment by Rajakavitha1** [comment]
Hi @ivdok !!! Looks like this issue is related to https://github.com/timescale/timescaledb/issues/2304. Can you please confirm if you tried timescaledb_pre_restore() and then timescaledb_post_restore()?

**Comment by Rajakavitha1** [comment]
Closing this issue because there is a TS for this error now in the docs.
