### ISSUE TITLE
Missing documentation on upgrade Postgres within a docker container 

### ISSUE THREAD

**Issue by WalkerWalker** [timescale/docs#1889]
### What type of enhancement is this?

Configuration

### What subsystems and features will be improved?

Configuration

### What does the enhancement do?

It is super nice to have documentation describing how to upgrade timescaledb in docker container https://docs.timescale.com/timescaledb/latest/how-to-guides/upgrades/upgrade-docker/

yet to upgrade postgres, from pg12 to pg13 and from pg13 to pg14, the instructions [here](https://docs.timescale.com/timescaledb/latest/how-to-guides/upgrades/upgrade-pg/) is not so clear to me, with essentially only the following command template
```
pg_upgrade -b <OLD_BIN_DIR> -B <NEW_BIN_DIR> -d <OLD_DATA_DIR> -D <NEW_DATA_DIR>
```

Woud it be possible to improve the documentation on this topic?

**Comment by Loquacity** [comment]
Hi there! I'm happy to help improve the docs, but I'm a little uncertain as to what extra information you're after. Are you able to elaborate?

**Comment by Loquacity** [comment]
Got it, thanks @WalkerWalker 💖

**Comment by Loquacity** [comment]
@svenklemm Are you able to be SME for this one?

**Comment by Rajakavitha1** [comment]
Hi @svenklemm I did explore the options to upgrade Postgres from pg14 to pg15 in Docker container and my understanding is that with [pg_upgrade](https://www.postgresql.org/docs/current/pgupgrade.html) command which automagically upgrades the database storage on disk to be compatible with the new version. Unfortunately however, it does this in a rather strange way: by requiring access to both the new and old server binaries during the upgrade. There’s almost certainly a good reason for this, and it likely massively reduces the complexity of the pg_upgrade application, but in a dockerized environment it’s just not possible - there’s only 1 binary available in the container. Please confirm if my understand is correct.

**Comment by Rajakavitha1** [comment]
Hi @WalkerWalker To upgrade Postgres within a docker container is in the official Postgres Documentation https://www.postgresql.org/docs/current/pgupgrade.html and Timescale DB documentation does provide a link to the official docs [here](https://docs.timescale.com/timescaledb/latest/how-to-guides/upgrades/upgrade-pg/). Closing this issue for now.

**Comment by jsteinm1** [comment]
@Rajakavitha1 - I have been reading through timescale and postgres documentation and it is not clear at all how to do pg_upgrade inside of a docker container. I see the timescaledb-ha:xx-all-oss images that have all the postgres versions to support an upgrade, but how do you successfully execute pg_upgrade inside of the container? It appears you need to stop the running postgres services but doing so immediate shuts down the container. The official postgres documentation you linked makes no mention of docker. Is there any other guides to detail how to do this?
