### ISSUE TITLE
[Feedback] Page: /timescaledb/latest/quick-start/golang/

### ISSUE THREAD

**Issue by PVKonovalov** [timescale/docs#1893]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

I think it's time to update this documentation for Golang  to "github.com/jackc/pgx/v5" version

**Comment by Loquacity** [comment]
@jamessewell Who could we lean on as an SME here?

**Comment by jamessewell** [comment]
@jonatas could you have a go at this?

**Comment by jonatas** [comment]
Upgrade from [version 4x](https://docs.timescale.com/timescaledb/latest/quick-start/golang/).
