### ISSUE TITLE
[Site Bug] Issue with the page: /install/latest/self-hosted/installation-debian/

### ISSUE THREAD

**Issue by malekva** [timescale/docs#1895]
# Describe the bug
Missing `sudo`  in the command to run `psql` . Other commands on the page work without `sudo` but this one does not.

## What do the docs say now?
On your local system, at the command prompt, connect to the PostgreSQL instance as the `postgres` superuser:

```-u postgres psql```

## What should the docs say?
On your local system, at the command prompt, connect to the PostgreSQL instance as the `postgres` superuser:

```sudo -u postgres psql```

# Page affected
https://docs.timescale.com/install/latest/self-hosted/installation-debian/

**Comment by Rajakavitha1** [comment]
Closing this in lieu of https://github.com/timescale/docs/issues/1898
