### ISSUE TITLE
[Feedback] Update function pipelines HowTo to remove experimental tag from `timevector`: /timescaledb/latest/how-to-guides/hyperfunctions/function-pipelines/

### ISSUE THREAD

**Issue by little-arhat** [timescale/docs#1899]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Hello!

Looks like linked page is outdated, `timevector` was stabilized in Aug22: https://github.com/timescale/timescaledb-toolkit/commit/142559e19a87217402de3326824f7a15369fd541 .

PG error message HINT might be confusing in that case: 
```
ERROR:  function toolkit_experimental.timevector(timestamp with time zone, numeric) does not exist
LINE 2:     toolkit_experimental.timevector(time, fill_level)
            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by Loquacity** [comment]
@davidkohn88 can you please help here? Can I just replace `toolkit_experimental.timevector` with `timevector` in this How To? Or do we need to some more substantial rewriting here?

**Comment by little-arhat** [comment]
@Loquacity I don't think so: in my timescale cloud env some functions (`timevector`, `unnest`, etc) are stabilised and available in default namespace, while others (`sort`, `lttb`, etc) are still experimental. 

I couldn't find `time_weight` fn that would work in timevector pipeline.
