### ISSUE TITLE
[Docs RFC] Improve upgrading steps for very old versions (< 2.0) of tsdb

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#1904]
# Describe change in content, appearance, or functionality

For very old installations of tsdb, you need to upgrade in steps to get to most recent.

# Subject matter expert (SME)

@jonatas 

# Deadline

[When does this need to be addressed]

# Any further info

Community Slack thread: https://timescaledb.slack.com/archives/C4GT3N90X/p1671277890427189?thread_ts=1670949711.187029&cid=C4GT3N90X

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by jamessewell** [comment]
Closing due to age.

If you need help with this then please ask in Slack 😀.
