### ISSUE TITLE
[Docs RFC] Mention pgdg ubuntu versioning in Debian install docs

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#1905]
# Describe change in content, appearance, or functionality

Related issue: https://github.com/timescale/docs/issues/1828

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

Community Slack thread: https://timescaledb.slack.com/archives/C5X6UVB24/p1671464135327819

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Rajakavitha1** [comment]
Fixed in https://github.com/timescale/docs/pull/1977. The warning is specific and apt manager maintained by Debian or Ubuntu only has to be used. If PostgreSQL is installed even with apt managed by PGDG it will have errors.
