### ISSUE TITLE
Outdated sections in caggs docs

### ISSUE THREAD

**Issue by charislam** [timescale/docs#1914]
There are outstanding outdated sections in caggs docs (since the launch of finalized caggs in 2.7).

See [this Slack thread](https://iobeam.slack.com/archives/C032AS21X4P/p1671437220580509) for some examples. The cagg docs need to be reviewed so these can be updated.

**Comment by Loquacity** [comment]
@iroussos @fabriziomello When do you want to go through these?

**Comment by iroussos** [comment]
@Loquacity sorry for the late reply, the past week+ has been pretty intense. 

How do you want to do it? If you want to do a sync session, we can schedule a call next week and go through everything together

**Comment by Loquacity** [comment]
> @Loquacity sorry for the late reply, the past week+ has been pretty intense.
> 
> How do you want to do it? If you want to do a sync session, we can schedule a call next week and go through everything together

Sounds good! Feel free to put something on my cal 👍
