### ISSUE TITLE
[Docs RFC] Update PG upgrade matrix to reflect PG15 and newer versions of TSDB

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#1929]
# Describe change in content, appearance, or functionality

The version matrix on the Upgrade PG page is getting out of date: https://docs.timescale.com/timescaledb/latest/how-to-guides/upgrades/upgrade-pg/

The other related issue is : https://github.com/timescale/docs/issues/1927

# Subject matter expert (SME)

@iroussos @svenklemm @jonatas 

# Deadline

[When does this need to be addressed]

# Any further info

Slack thread: https://iobeam.slack.com/archives/C032AS21X4P/p1673378039180329

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by clarkbw** [comment]
Could we add a note about how Cloud has 1 click upgrades?

**Comment by Loquacity** [comment]
> Could we add a note about how Cloud has 1 click upgrades?

Yes, absolutely. We have a Cloud-specific callout we can use.

**Comment by Loquacity** [comment]
From @iroussos 
 
> Other than that, I think that we should keep all the versions in there for the reasons Sven mentioned above. There may be self managed instances on older versions or users that for whatever reason can not go above a certain PG version right now.
> As the table is getting pretty large and some columns reside out of the visible pane, I would only switch the order of the table horizontally so that we can have the latest PG version first. We could similarly switch the order vertically and bring the latest TimescaleDB versions on top, but I am not sure if this is better or not. What do you think?
