### ISSUE TITLE
[Feedback] Installing Timescale Version - what version?

### ISSUE THREAD

**Issue by jonatas** [timescale/docs#1965]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

Today, a community member (David White) shared this request during office hours.

It's tough to find the version that you're downloading as every place it says `latest` and does not expose the version. It would be great if the version for the latest is available in the docs explicitly.

**Comment by jonatas** [comment]
Also, another feedback from David is that we could add some notes for support, like PG15. What is the status of PG15? How much is it supported? What is missing? How can users know the state of the art of the latest version of Postgresql?

**Comment by Loquacity** [comment]
Slack thread: https://iobeam.slack.com/archives/C03H4440ZQC/p1675829608216399
