### ISSUE TITLE
[Site Bug] Issue with the page: /install/latest/installation-kubernetes/

### ISSUE THREAD

**Issue by alexmarshallces** [timescale/docs#1967]
_Use this template for reporting bugs in the docs._

# Describe the bug

The instructions for accessing the Timescale database from within a Kubernetes cluster appear to longer be accurate for Helm release `0.8.0`.

## What do the docs say now?

![image](https://user-images.githubusercontent.com/98354277/213278693-9f7e4cc9-bc7f-4168-8da3-d6dccadb5faa.png)

## What should the docs say?

Unknown. No pods matching the given `kubectl` selector are present after installing Helm chart version `0.8.0` and adapting `kubectl` parameters for actual target namespace where the chart was installed.

# Page affected

https://docs.timescale.com/install/latest/installation-kubernetes/#connect-to-timescaledb

# Subject matter expert (SME)

Unknown

# Screenshots

See above for screenshot.

# Any further info

Multiple pieces of this page seem to be inconsistent with Helm chart v0.8.0 and this whole page probably needs to be reviewed and updated.

**Comment by Rajakavitha1** [comment]
Hi @alexmarshallces Validated and test the steps work as documented.
```
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % kubectl get secret --namespace default timescale-credentials -o jsonpath="{.data.PATRONI_admin_PASSWORD}"
S29Ea3VCTEFQSFNvMVkwRw==%                                                                           rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % MASTERPOD="$(kubectl get pod -o name --namespace default -l release=timescale,role=master)"
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % kubectl exec -i --tty --namespace default ${MASTERPOD} -- psql -U postgres
Defaulted container "timescaledb" out of: timescaledb, tstune (init)
psql (14.6 (Ubuntu 14.6-1.pgdg22.04+1))
Type "help" for help.

postgres=# 
```
closing this issue for now
