### ISSUE TITLE
List of new Forge Docs/KB articles

### ISSUE THREAD

**Issue by alexthinath** [timescale/docs#197]
# Describe change in content, appearance, or functionality

Go through the [MST knowledgebase](https://kb-managed.timescale.com/en/) and trransfer articles into the official [MST documentation](https://docs.timescale.com/mst/latest/).

Additionally, consider adding new content for this topics:

- [ ] - Forge SLA explanation
- [ ] - Automation options explanation
- [ ] - Compliance standards/explanation
- [ ] - Disk full procedures
- [ ] - What should I do when I hit or am approaching my storage limit?
- [ ] - How are backups stored
- [ ] - Recommended backup restore process without a UI for PITR
- [ ] - What happens to Forge services when the trial ends?
- [ ] - Does Forge have HA / “high availability”? What’s the difference between HA on Cloud?
- [x] - Multi-node set up and limitations -https://docs.timescale.com/mst/latest/mst-multi-node/
- [ ] - Metrics and integrations to provide further metrics 
- [x] - Can I use Connection Pooling? - https://docs.timescale.com/mst/latest/connection-pools/
- [ ] - Migration from, e.g. self-managed, Cloud, RDS, etc

# Subject matter expert (SME)
Tyler Fontaine
Alex Thinath

**Comment by alexthinath** [comment]
more...

- What happens to Cloud services which are paused? how does that work?
- How do I receive updates to the TimescaleDB extension?

**Comment by Loquacity** [comment]
From [Community Slack](https://timescaledb.slack.com/archives/C01R6ME0JCS/p1646057029634489?thread_ts=1645739535.156159&cid=C01R6ME0JCS):

> It turns out you can integrate MST services with Loggly, but the information on how to do that lives in the Aiven docs (which is why my initial googling failed...). You can do it all through the TSDB managed portal (first set up the Loggly service integration, then connect each service to that). The important bits (like which host/port to use and how to construct the structured data field) can be found here:

https://help.aiven.io/en/articles/3632695-log-integration-with-loggly
and here:
https://documentation.solarwinds.com/en/success_center/loggly/content/admin/streaming-syslog-without-using-files.htm
Nice!

**Comment by Rajakavitha1** [comment]
Marking this as closed now because all the articles have been moved as per the [tracking sheet](https://docs.google.com/spreadsheets/d/10Qi45aSnLUm-MRO6LBJuq2g9goxCuT4MFSu_FxpZyFc/edit#gid=0)
