### ISSUE TITLE
[Feedback] Page: /mst/latest/billing/

### ISSUE THREAD

**Issue by rm289** [timescale/docs#1972]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

I can find no pricing data anywhere for the managed services for timescaledb.

https://www.timescale.com/cloud-pricing/

https://www.timescale.com/cloud-pricing/?utm_source=timescale-cloud-momentum-announcement&utm_medium=blog&utm_campaign=pr-2020&utm_content=cloud-pricing-calculator-page

this link should take me to a link for managed services cloud pricing, but it takes me to a generic landing page.

Please either A) remove the pricing links, they don't work, or B) put back the pricing information that was likely there in the past and has been removed.

**Comment by Loquacity** [comment]
Hi, thanks for raising this issue. I've spoken to the web team, and they are in the process of adding this information. In the meantime, you can fill out the form at https://www.timescale.com/contact or sign up for free for the product to get pricing info.
