### ISSUE TITLE
[Feedback] Page: /install/latest/self-hosted/installation-debian/

### ISSUE THREAD

**Issue by EricOnGit** [timescale/docs#1975]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

There's a package mismatch in the procedure. We end up installing a mixture of postgresql 15 and postgresql 14 which creates all sorts of errors when creating the extension in tsdb.
Simply running 
apt install postgres postgres-client timescaledb-2-postgresql-**15**
is producing better results. At least the extension gets created as it should.

**Comment by Rajakavitha1** [comment]
Updated in https://github.com/timescale/docs/pull/1977
