### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/overview/core-concepts/hypertables-and-chunks/hypertable-architecture/

### ISSUE THREAD

**Issue by TigerP** [timescale/docs#1976]
# Describe the bug
'To learn about best practices for chunk time intervals, see the documentation on [chunk sizing](https://docs.timescale.com/timescaledb/latest/overview/core-concepts/hypertables-and-chunks/hypertable-architecture/timescaledb/latest/how-to-guides/hypertables/about-hypertables/#best-practices-for-time-partitioning).' contains a broken link, because when you click on 'chunk sizing' it displays page not found.

## What do the docs say now?
See Describe the bug

## What should the docs say?
I have not searched what the correct link should be.

# Page affected
https://docs.timescale.com/timescaledb/latest/overview/core-concepts/hypertables-and-chunks/hypertable-architecture/

**Comment by Loquacity** [comment]
Verified.

**Comment by jamessewell** [comment]
Closed as this is fixed! 🚀
