### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/overview/core-concepts/distributed-hypertables/

### ISSUE THREAD

**Issue by timdemling** [timescale/docs#1985]
_Use this template for reporting bugs in the docs._

# Describe the bug

Page says "as described above" in the first paragraph of a new page

[[Provide the URL to the page you noticed the bug on]](https://docs.timescale.com/timescaledb/latest/overview/core-concepts/distributed-hypertables/)

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

![image](https://user-images.githubusercontent.com/116119901/214319801-486ad8d5-f31e-46f3-a9fc-423e4292492a.png)

**Comment by Loquacity** [comment]
As if we needed another reminder why we don't use directional language (https://docs.timescale.com/timescaledb/latest/contribute-to-docs/#a)! Thanks for the report 😁
