### ISSUE TITLE
[Content Bug] UDA example needs to be updated

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#2010]
# Describe the bug

UDA example for tablespace management isn't correct. 

## What should the docs say?

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/user-defined-actions/example-tiered-storage/

# Subject matter expert (SME)

@noctarius 

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

- Explanation in https://github.com/timescale/docs/issues/323#issuecomment-909193620
- Link to community thread: https://timescaledb.slack.com/archives/C4GT3N90X/p1675132547085259

## Contributing to documentation

We welcome documentation contributions!

* For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
* For information on style and word usage, see the [style guide](https://docs.timescale.com/timescaledb/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
@Rajakavitha1 Is there a PR open somewhere for this?

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 Is there a PR open somewhere for this?

No @Loquacity  not yet!!!

**Comment by Loquacity** [comment]
OK, I'll move it back to the backlog then 👍
