### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/distributed-hypertables/

### ISSUE THREAD

**Issue by ericcoulthard** [timescale/docs#204]
# Describe the bug

Broken Link.
"https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/undefined/"

## What do the docs say now?

Distributed hypertables currently have some limitations when compared to non-distributed hypertables. Before creating a distributed hypertable for production workloads, please review our limitationsdistributed-hypertable-limitations document to ensure that your use case will work as expected. You can also contact uscontact or join the #multinode channel in our community Slackslack.

## What should the docs say?

Should probably say the same thing. The link should be fixed though.

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/#distributed-hypertables

# Version affected

latest v2.X

# Screenshots

![image](https://user-images.githubusercontent.com/46009938/126680741-bb984c61-2b9f-4dae-8dd3-9300539dac5e.png)

**Comment by ericcoulthard** [comment]
I'm afraid that the broken link is still broken.

**Comment by Loquacity** [comment]
> I'm afraid that the broken link is still broken.

Ah, you mean the limitations one? I see it.

**Comment by ericcoulthard** [comment]
Broken link is still there. The limitation documents cannot be found. I would very much like to read it. Broken link below.
https://docs.timescale.com/latest/overview/limitations/#distributed-hypertable-limitations

**Comment by Loquacity** [comment]
This is the correct link: https://docs.timescale.com/timescaledb/latest/overview/limitations/##distributed-hypertable-limitations I'll take another look at the doc shortly. Sorry for the confusion!
