### ISSUE TITLE
[Content Bug] Inaccurate results in time_bucket_gapfill docs

### ISSUE THREAD

**Issue by kgyrtkirk** [timescale/docs#2046]
# Describe the bug

The resultsets of the current [time_bucket_gapfill](https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/time_bucket_gapfill/) is inaccurate; in https://github.com/timescale/timescaledb/issues/5287 this created some confusion.

## What do the docs say now?

The current page lists resultsets with 7 rows; meanwhile it will be 8 in almost all cases (unless the start/end is aligned with the bucket boundary)

## What should the docs say?

* resultsets should be updated
* preferably the queries should be changed to not contain `now()` ; so they can be run and validated by users 
  * possibly add an example that it can be used with `now()` ; but avoid the usage of it during showcasing
* note: the page doesn't have any examples for the usage of the `timezone` feature (`time_bucket` has)

https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/time_bucket_gapfill/

**Comment by Loquacity** [comment]
@charislam Is there a PR open somewhere for this?

**Comment by Loquacity** [comment]
This appears to be fixed in the current version of the docs.
