### ISSUE TITLE
[Feedback] Page: /timescaledb/latest/how-to-guides/upgrades/minor-upgrade/

### ISSUE THREAD

**Issue by Solomon-Hill** [timescale/docs#2047]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

ALTER EXTENSION timescaledb UPDATE; does not work. Your documentation is poor

run locally(local TSDB deployed mac/brew/postgres). returns: 
"NOTICE:  version "2.9.2" of extension "timescaledb" is already installed
ALTER EXTENSION"

run on a managed AWS instance (i was told to do this on support ticket 00012815) it returns:

"SQL Error [0A000]: ERROR: extension "timescaledb" cannot be updated after the old version has already been loaded
  Hint: Start a new session and execute ALTER EXTENSION as the first command. Make sure to pass the "-X" flag to psql."

this is far from a solution to a managed service when critical security updates are hidden in "minor updates"

the above seems to have been an issue for some time:
https://github.com/timescale/timescaledb/issues/1003

**Comment by charislam** [comment]
Hi Solomon,

Thanks for reporting this issue. Just to clarify, when you say you're running this on a managed AWS instance, are you running on Managed Service for TimescaleDB or Timescale Cloud?

And regarding that support ticket number, am I correct in assuming you're already in contact with our Support team about this issue?

Just want to make sure we have the right information to provide the proper help here!

**Comment by pfried** [comment]
This is also an issue when using orm tools like prisma, see https://github.com/prisma/prisma/issues/8325

**Comment by Rajakavitha1** [comment]
Hi @pfried !! Just tested and validated the instructions in the guide and they seem to work as documented.
```rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % docker exec -it timescaledb psql -U postgres -X
psql (14.8)
Type "help" for help.

postgres=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.10.0  | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

postgres=# ALTER EXTENSION timescaledb UPDATE;
ERROR:  extension "timescaledb" cannot be updated after the old version has already been loaded
HINT:  Start a new session and execute ALTER EXTENSION as the first command. Make sure to pass the "-X" flag to psql.
postgres=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.10.0  | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

postgres=# 
Last login: Thu Aug 10 11:02:45 on ttys002
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % docker exec -it timescaledb psql -U postgres -X
psql (14.8)
Type "help" for help.

postgres=# ALTER EXTENSION timescaledb UPDATE;
ALTER EXTENSION
postgres=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.11.1  | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

postgres=# 
```
As recommended in the error message you may want open the upgraded version in a new terminal session and then run the  `ALTER EXTENSION timescaledb UPDATE;` command. Marking this issue as closed for now. Please feel free to reopen if any other changes needs to be made to the documentation.

**Comment by pfried** [comment]
Thanks @Rajakavitha1 , there is one more related thing to this [#5884](https://github.com/timescale/timescaledb/issues/5884)
