### ISSUE TITLE
[Content Bug]Missing page

### ISSUE THREAD

**Issue by solugebefola** [timescale/docs#205]
_Use this template for reporting bugs in the docs._

# Describe the bug

Incorrect sidebar link for https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/real-time-aggregates/

the link from the sidebar is: https://docs.timescale.com/timescaledb/latest/how-to-guides/real-time-aggregates/

## What do the docs say now?

> NOT FOUND
You just hit a route that doesn't exist... the sadness.

## What should the docs say?

The standard page

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/real-time-aggregates/

# Version affected

latest

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

This page was accessed through the sidebar

**Comment by Loquacity** [comment]
This seems to be working OK for me. Can you please reopen with more info if it's still broken for you?
