### ISSUE TITLE
[Feature]: Jupysql integration

### ISSUE THREAD

**Issue by idomic** [timescale/docs#2060]
### What problem does the new feature solve?

It'd be great to see a tutorial or documentation of the 2 frameworks.
Probably a user working locally via a jupyter notebook and [jupysql](https://github.com/ploomber/jupysql) to query and perform EDA/modeling work.

### What does the feature do?

Please provide the following for the desired feature or change:

A detailed explanation on querying via SQL.
Plotting via sql.
Using Jupyter notebooks to query.

### Implementation challenges

Happy to work on the PR!

**Comment by mathisve** [comment]
Hi @idomic,
Thanks for creating this issue! 
Feedback like this helps us discover what our users do with TimescaleDB, which is always welcomed! 
As you can see I've moved this issue from `timescale/timescaledb` to `timescale/docs` as your request suits this repository more.

But, I can happily say that we are currently working on some content about using TimescaleDB in Jupyter notebooks, so stay tuned!

Thanks!

**Comment by idomic** [comment]
Can we collaborate on this, I'm happy to help and we wanted to have a time series example for `jupysql` as well so sounds like a good fit. Let me know how I can be of any help!

**Comment by Rajakavitha1** [comment]
Thank you @mathisve  and @idomic for willing to contribute to Timescale Documentation. The docs team is more than happy to help you both in the contribution. Looking forward to the PR.

**Comment by Loquacity** [comment]
Is this still in progress?

**Comment by Loquacity** [comment]
We can probably poke @avthars as an SME here
