### ISSUE TITLE
[Feedback] Page: /timescaledb/latest/how-to-guides/configuration/timescaledb-tune/

### ISSUE THREAD

**Issue by ericcoulthard** [timescale/docs#2069]
### How could we improve the Timescale documentation site?

The instructions on this page do not work for recent versions of go. I get the following error running the first command on this page.

>> go install github.com/timescale/timescaledb-tune/cmd/timescaledb-tune@latest
package github.com/timescale/timescaledb-tune/cmd/timescaledb-tune@latest: cannot use path@version syntax in GOPATH mode

**Comment by Loquacity** [comment]
@jonatas Are you able to verify this one for me? 💖

**Comment by ericcoulthard** [comment]
Ping

**Comment by Rajakavitha1** [comment]
> @jonatas Are you able to verify this one for me? 💖

Hi @Loquacity !! I validated and it seems to work perfectly fine on the latest version of go:
```rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % go version     
go version go1.20.1 darwin/arm64
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % go install github.com/timescale/timescaledb-tune/cmd/timescaledb-tune@latest
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % go install github.com/timescale/timescaledb-tune/cmd/timescaledb-tune@latest
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 ~ % cd timescale            
rajakavithakodhandapani@Rajakavithas-MacBook-Pro-2 timescale % timescaledb-tune
Using postgresql.conf at this path:
/opt/homebrew/var/postgresql@14/postgresql.conf

Is this correct? [(y)es/(n)o]: 
```

**Comment by Loquacity** [comment]
Thanks @Rajakavitha1 😁 

@ericcoulthard We can't reproduce this error. Perhaps there's something going on in your setup instead?

**Comment by Rajakavitha1** [comment]
> Thanks @Rajakavitha1 😁
> 
> @ericcoulthard We can't reproduce this error. Perhaps there's something going on in your setup instead?

Hi @ericcoulthard  can you please check if you have set the GOPATH? For details, see https://go.dev/doc/gopath_code

**Comment by ericcoulthard** [comment]
Thanks for the help. Looks like I chose the wrong path to installing go. I originally went with sudo app install golang. The golden path seems to be to install from source. After following the instructions on this page it works.
https://golangdocs.com/install-go-linux

**Comment by ericcoulthard** [comment]
It would probably help others if you included a link to the correct way to install go on this page.

**Comment by jonatas** [comment]
I got your point @ericcoulthard, let's try to improve this and create some sentences that can point you out to the website.


We initially assumed that the quickstart is introducing Timescaledb to someone that is already a gopher user, that's why we're not focusing on too many details from golang itself. But we should be able to support all people trying it. As the first message in the content says:

> Timescale Code Quick Start Guides are designed to help you integrate TimescaleDB into your own programs. They use your favorite programming language to explain how to connect to a Timescale database, create and manage hypertables, and ingest and query data.
