### ISSUE TITLE
[Feedback] Improve instructions on importing from CSV on page: /timescaledb/latest/how-to-guides/migrate-data/import-csv/

### ISSUE THREAD

**Issue by Panometric** [timescale/docs#2073]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

The "psql -d <DATABASE_NAME> -c "\COPY <TABLE_NAME> FROM <FILENAME>.csv CSV"" way does not appear to work. 
I just wanted to move some timeseries data between machines.   CSV exports do not have 'timestamp with timezone' datatypes. So they PSQL will not import as stated.

**Comment by Loquacity** [comment]
We might need to add a note about what your CSV needs to contain. I wonder if it's worth also pointing to sqlite or something, too ... 🤔
