### ISSUE TITLE
[Feedback] Extension needs to be preloaded on self-hosted install. Page: /install/latest/self-hosted/installation-linux/

### ISSUE THREAD

**Issue by pmzajaczkowski** [timescale/docs#2077]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

In the step "Add the TimescaleDB third party repository:" the buttons for choosing option Ubuntu/Debian are hardly visible. Which leads to googling how to fix the error (https://github.com/timescale/timescaledb/issues/1852#issuecomment-1022695745). 

When enabling the extension it first needs to be preloaded, which is not mentioned in the docs at all.
```
tsdb=# CREATE EXTENSION IF NOT EXISTS timescaledb;
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: /etc/postgresql/14/main/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
	# Modify postgresql.conf:
	shared_preload_libraries = 'timescaledb'

Another way to do this, if not preloading other libraries, is with the command:
	echo "shared_preload_libraries = 'timescaledb'" >> /etc/postgresql/14/main/postgresql.conf 

(Will require a database restart.)

If you REALLY know what you are doing and would like to load the library without preloading, you can disable this check with: 
	SET timescaledb.allow_install_without_preload = 'on';
SSL connection has been closed unexpectedly
The connection to the server was lost. Attempting reset: Succeeded.
psql (15.2 (Ubuntu 15.2-1.pgdg20.04+1), server 14.7 (Ubuntu 14.7-1.pgdg20.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
```

**Comment by Loquacity** [comment]
Hi! Are you able to send a screenshot of the buttons? They're definitely visible on my screen, and I'm wondering what might be causing them to be less visible on yours. Here's how they look for me:

![image](https://user-images.githubusercontent.com/3914967/221716845-74b851c3-22ac-4d5a-8832-3536f1925948.png)

As for preloading the library, we'll try and replicate that here and update the instructions accordingly 👍

**Comment by pmzajaczkowski** [comment]
Hi, thanks for such a quick response. These are visible on my screen as well (Firefox): 
![obraz](https://user-images.githubusercontent.com/9041884/221722545-e8624f76-8ca9-4cb3-b463-c9a6c64f3072.png)

The case is that this solution seems to be not the most intuitive one and people seem to ignore these buttons existence - like I did, unfortunately (and, apparently, other people who "liked" the linked comment as well). Maybe instead of having this custom solution with buttons you could do the tabs (like for Debian, etc.) or just two separate sections with headers "Ubuntu" & "Debian"? It's not a bug, it rather UX improvement suggestion :)

**Comment by Loquacity** [comment]
Thanks for the screenshot! I'm glad it seems to be (technically) working, anyway 😅 We developed the buttons first, and only implemented the tabs much more recently, so you're right that there are places where tabs instead of buttons would be an improvement, and we are slowly updating those. However, in this particular example, the tabs are already there, and this is a single terminal block that has only a small difference in it. Using a tab for this would mean a lot of repeated content, that would then need to be maintained and updated. For that reason, I can't see this changing in the short term. That said, we are planning some larger scale updates to our installation documentation soon, that will probably see this content change, so we can re-address the button design and UX at that stage.

I'll keep this issue open so that we can work on the preloading instructions.

**Comment by pmzajaczkowski** [comment]
Well, I wasn't thinking about introducing totally new tab for Ubuntu (that would repeat all steps, etc.). I was rather thinking about sub-tabs for this particular installation step, just for this single "code snippet". It would be more visible than these buttons.

Alternatively, a quick fix would be to enhance the sentence above this "code snippet" and mention explicitly that there are two slightly different versions for Ubuntu/Debian, to draw the reader's attention to that detail.

**Comment by Loquacity** [comment]
> Well, I wasn't thinking about introducing totally new tab for Ubuntu (that would repeat all steps, etc.). I was rather thinking about sub-tabs for this particular installation step, just for this single "code snippet". It would be more visible than these buttons.
> 
> Alternatively, a quick fix would be to enhance the sentence above this "code snippet" and mention explicitly that there are two slightly different versions for Ubuntu/Debian, to draw the reader's attention to that detail.

Yes, that's my best idea as well. We'll need to go through and verify the steps anyway, so when we do that we can discuss how to enhance the surrounding text.

**Comment by Rajakavitha1** [comment]
Hi @pmzajaczkowski could you please confirm if you encountered this error after running timescaledb-tune: ```When you have completed the installation, you need to configure your database so that you can use it. The easiest way to do this is to run the timescaledb-tune script, which is included with the timescaledb-tools package. Run the timescaledb-tune script using the sudo timescaledb-tune command. For more information, see the [configuration](https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/) section.``` Because the timescales-tune scripts ensures that the extension is preloaded. as documented here: https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/

**Comment by pmzajaczkowski** [comment]
@Rajakavitha1 Well, because this paragraph was not explicitly mentioned as a "next step" (it differs from the rest of installation points), I thought I will "tune the database" later. It was not clear to me that this is a required step to proceed. In other words, no I haven't used that command. Maybe that caused my problem.

So, I would turn this "free form" paragraph into next bullet point of the installation process guideline, just to visualize that this is something that has to be executed.

**Comment by Rajakavitha1** [comment]
It is now a step in https://github.com/timescale/docs/pull/2100. Closing this issue for now.
