### ISSUE TITLE
[Site Bug] Issue with the page: /api/latest/continuous-aggregates/add_continuous_aggregate_policy/

### ISSUE THREAD

**Issue by vij1ay** [timescale/docs#2093]
_Use this template for reporting bugs in the docs._

# Describe the bug

Not able to add initial_start to [add_continuous_aggregate_policy] (https://docs.timescale.com/api/latest/continuous-aggregates/add_continuous_aggregate_policy/#add_continuous_aggregate_policy-community)

## What do the docs say now?
Should add initial start as timestamtz format
![image](https://user-images.githubusercontent.com/3069381/223102388-84fafa04-2f62-4c01-95e6-69e9663c957b.png)

# Screenshots
Tried various option, getting the error in the screenshot.

![image](https://user-images.githubusercontent.com/3069381/223102593-c378eadc-8a44-4df1-baf1-27837911748a.png)
![image](https://user-images.githubusercontent.com/3069381/223102652-0874f828-a545-4c0a-aee0-e580ee005abb.png)

[Attach images of screenshots showing the bug]

**Comment by Loquacity** [comment]
@jonatas Are you able to help here?

**Comment by jonatas** [comment]
@vij1ay can you help us adding more details here about your environment?

What is your PostgreSQL version?
What is the Timescaledb extension version?

Do you have the extension running?

If you could provide a minimal example in a SQL snippet that we can run, we could probably understand and try to test ourselves.

It seems you're facing an issue with implicit typecast over one of the parameters. Have you tried to cast it?

**Comment by jamessewell** [comment]
This runs on the current version, closing unless there are more updates 😀
