### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/backup-and-restore/troubleshooting/

### ISSUE THREAD

**Issue by fraenku** [timescale/docs#2102]
_Use this template for reporting bugs in the docs._

# Describe the bug
Running the backup-command
sudo pg_dump -h isys-timescale-server -U thingsboard_test -Fc -f thingsboard_test.bak thingsboard_test

gives me the following warnings:
pg_dump: warning: there are circular foreign-key constraints on this table:
pg_dump:   hypertable
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
 
Can this warning be ignored?

**Comment by Loquacity** [comment]
@jfjoly You might have more info here? Do we need to add a new troubleshooting entry for this?

**Comment by Loquacity** [comment]
Looks like we already have a troubleshooting entry for this
