### ISSUE TITLE
[Feedback] Page: /timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-config/

### ISSUE THREAD

**Issue by ioannisNoukakis** [timescale/docs#2133]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

You have a typo under the "jit" section: "succssfully" -> https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-config/#jit

**Comment by Rajakavitha1** [comment]
Fixed in https://github.com/timescale/docs/pull/2141/files.
