### ISSUE TITLE
[Feedback] Backup and Restore unclear command

### ISSUE THREAD

**Issue by abattenb** [timescale/docs#2167]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Link: https://docs.timescale.com/cloud/latest/backup-restore-cloud/#backup-and-restore

Had a customer write into Support:

> Per https://docs.timescale.com/cloud/latest/backup-restore-cloud/#backup-and-restore
> 
> I ran:
> SELECT pg_is_in_backup()::text
> 
> -> "false"
> 
> Shouldn't this return "true"? Just want to make sure we have backups that we can restore with, in case of disaster or data deletion.

After reading it, I kinda agree. Yes, at the top we clearly state we backups on by default, but maybe the line at the bottom:

> If you want to verify that your service is being backed up [...]

could read:

> If you want to verify that your service is the active process of being backed up [...]

or something like it. I'd also like to know _when_ backups are run, but that might be a UI feature thing.

**Comment by Rajakavitha1** [comment]
hi @abattenb in the latest and updated content https://docs.timescale.com/use-timescale/latest/backup-restore-cloud/#backup-and-restore we have no references to ```If you want to verify that your service is being backed up [...]``` Marking this issue as closed now. Please feel free to reopen if any other changes need to be made.
