### ISSUE TITLE
[Feedback] Page: /api/latest/hyperfunctions/ Hi i used your documentation for installing timescale DB . but while installing i faced lot  of issues. you didn't address that. in google also i can't find the resources. and here , "Do you want to run timescaledb-tune.exe now? [(y)es / (n)o]: y Please enter the path to your postgresql.conf: " , you didn't specify which path should be used. and we need clear video tutorials. nowadays all websites starts to give videos with clear Explanation. 

### ISSUE THREAD

**Issue by vimalaathythan** [timescale/docs#2170]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

**Comment by Rajakavitha1** [comment]
Hi @vimalaathythan !!!! 
We checked the install documentation and there is a link to https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-tune/#timescaledb-tuning-tool in all the install sections.
You may want to try [Timescale Cloud](https://docs.timescale.com/cloud/latest/) that is easy to use and free for 30 days to evaluate Timescale. Closing this issue for now.

**Comment by vimalaathythan** [comment]
when i try to convert a table to hypertable. I'm getting this error
ERROR:  function create_hypertable(unknown, unknown) does not exist
LINE 1: SELECT create_hypertable('conditions', 'time');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


SELECT * FROM pg_extension WHERE extname='timescaledb';
CREATE EXTENSION IF NOT EXISTS timescaledb;
I tried the above commands also. 
it throws the another error.
FATAL:  extension "timescaledb" must be preloaded
HINT:  Please preload the timescaledb library via shared_preload_libraries.

This can be done by editing the config file at: C:/Program Files/PostgreSQL/15/data/postgresql.conf
and adding 'timescaledb' to the list in the shared_preload_libraries config.
        # Modify postgresql.conf:
        shared_preload_libraries = 'timescaledb'

So I modifies that postgresql.config file. still facing issues. kindlysomeone help me.

**Comment by Rajakavitha1** [comment]
@vimalaathythan This error occurs typically when you have not specified yes to shared_preload_libraries when running timescaledb-tune 
<img width="502" alt="Screenshot 2023-03-23 at 8 54 43 AM" src="https://user-images.githubusercontent.com/37059749/227094332-08ecab09-e8c2-492c-8a54-a9a08d4c9bc5.png">
You may also want to join our community slack listed in https://docs.timescale.com/timescaledb/latest/overview/faq/faq-community/ . You have access to wider audience who may be able to help you in resolving the issues.
