### ISSUE TITLE
[Feedback] Improve content about creating indexes on page: /timescaledb/latest/how-to-guides/schema-management/indexing/

### ISSUE THREAD

**Issue by gajus** [timescale/docs#2175]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

```sql
CREATE INDEX ON conditions (location, time DESC);
```

Shouldn't this be inverse?, i.e. `(time DESC, location)`

And if no, then it might make sense to add a comment to docs explaining why that isn't the case.

Since partitioning is made using the `time` column, I would expect that it needs to be always first member in the index.

Wouldn't using `location` as the first member of the index be extremely inefficient? The premise of course is that the queries used to pull data always have to include time range (which as far as my familiarity goes with timeseries data is always the case)

**Comment by Loquacity** [comment]
Hypertables are automatically indexed on the time column. This is adding a secondary index, which is optional. This is stated on the page, but we can probably improve the wording a little.

**Comment by gajus** [comment]
> Hypertables are automatically indexed on the time column. This is adding a secondary index, which is optional. This is stated on the page, but we can probably improve the wording a little.

Is `(location, time DESC)` index actually equivalent to `(time, location, time DESC)`? Because if so, that was not obvious from the documentation.

**Comment by Loquacity** [comment]
The best way to get help with these kinds of issues is to jump on to our community Slack or forum: https://www.timescale.com/community

**Comment by gajus** [comment]
> The best way to get help with these kinds of issues is to jump on to our community Slack or forum: https://www.timescale.com/community

I am pretty sure I am right, so this is more of a flagging documentation issue.
