### ISSUE TITLE
[Feedback] Page: /timescaledb/latest/tutorials/nyc-taxi-cab/dataset-nyc/

### ISSUE THREAD

**Issue by filipeamoreira** [timescale/docs#2202]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

Broken link: https://timescaledata.blob.core.windows.net/datasets/nyc_data.tar.gz

**Comment by Loquacity** [comment]
We are aware of this issue, thank you!
