### ISSUE TITLE
[Site Bug] Improve instructions on page: /quick-start/latest/python/

### ISSUE THREAD

**Issue by Sai-Kambham** [timescale/docs#2216]
# Describe the bug

Python3 is throwing below error when created a hypertable using the command mentioned in the page:

function create_hypertable(unknown, unknown) does not exist
LINE 1: SELECT create_hypertable('idrac10.unique_voltagereading', 't...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

current transaction is aborted, commands ignored until end of transaction block

## What do the docs say now?

query_create_sensordata_hypertable = "SELECT create_hypertable('sensor_data', 'time');"

This code helps create a hypertable, but it does not.

## What should the docs say?

Modify the code mentioned above.

# Page affected

https://docs.timescale.com/quick-start/latest/python/#create-a-hypertable

# Screenshots

<img width="625" alt="image" src="https://user-images.githubusercontent.com/108426158/229054644-9d37818f-338c-4c7c-a008-bf758594fc40.png">

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
@zseta Are you able to help out here?

**Comment by Loquacity** [comment]
@jonatas Are you able to help out here?

**Comment by jonatas** [comment]
Hi @Sai-Kambham, can you confirm that you have the extension installed?

I'd love if you could bring the source code you're using here and also the command you're running.

If you're on psql, try the follow commands and paste the output here:

1. Confirm you have the  extension installed

```sql
\dx
```

2. Confirm you have the function available in your search path.

```sql
\df create_hypertable
```

3. Confirm the table exists:

```sql
\d+ idrac10.unique_voltagereading
```
