### ISSUE TITLE
[Site Bug] Issue with the page: /tutorials/latest/nyc-taxi-cab/dataset-nyc/ 

### ISSUE THREAD

**Issue by editaxha** [timescale/docs#2219]
_Use this template for reporting bugs in the docs._

# Describe the bug
Can't Download nyc_data.tar.gz file for the datas
https://timescaledata.blob.core.windows.net/datasets/nyc_data.tar.gz

## What should the docs say?

# Page affected

[Provide the URL to the page you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
We are aware of this issue, thank you.
