### ISSUE TITLE
[Feedback] Update title of page: /use-timescale/latest/compression/manually-compress-chunks/

### ISSUE THREAD

**Issue by rpuncel** [timescale/docs#2221]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

It looks to me like the instructions to manually compress chunks using `select compress_chunk(...)` may have been removed from this page - I remember it being there. As of right now, there is only instructions on how to set a compression policy.

https://docs.timescale.com/use-timescale/latest/compression/manually-compress-chunks/

**Comment by Loquacity** [comment]
Thanks for letting us know. Is this the information you're looking for? https://docs.timescale.com/self-hosted/latest/compression/manual-compression/

**Comment by Loquacity** [comment]
Docs team: let's change the name of the page in the Use Timescale section.
