### ISSUE TITLE
[Docs RFC] Update pg_dump document for timescale

### ISSUE THREAD

**Issue by lkshminarayanan** [timescale/docs#2226]
# Describe change in content, appearance, or functionality

PR timescale/timescaledb#5218 restricts the permissions to the `_timescaledb_internal.job_errors` table so that the users can only view the job errors log through the view `timescaledb_information.job_errors`. Due to this change, when a non superuser tries to take a backup using pg_dump, they will get the following error (emphasis mine) :

$ pg_dump -U testuser -v testdb
pg_dump: last built-in OID is 16383
pg_dump: reading extensions
pg_dump: identifying extension members
pg_dump: reading schemas
pg_dump: reading user-defined tables
pg_dump: error: **query failed: ERROR:  permission denied for table job_errors**
pg_dump: detail: **Query was: LOCK TABLE _timescaledb_internal.job_errors IN ACCESS SHARE MODE**

pg_dump tool tries to acquire lock on the job_errors table but the user doesn't have the required SELECT permission leading to the above mentioned error.

More details on the issue at timescale/timescaledb#5449. 

This is most likely a bug in the pg_dump tool and we are trying to get it fixed upstream - [link](https://www.postgresql.org/message-id/flat/00d46a48-3324-d9a0-49bf-e7f0f11d1038%40timescale.com).

Meanwhile, we should inform the users to use the workaround mentioned [here](https://github.com/timescale/timescaledb/issues/5449#issuecomment-1494404742). (i.e.) a superuser should grant the necessary permission to the user that needs to take the backup using pg_dump.  Even if we get this bug fixed in recent PG versions, the older versions will still have this bug. So it is necessary to get this documented.

# Subject matter expert (SME)

@mkindahl 

# Deadline

Sooner the better as we have already published a release (2.10.0) with this change.

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Rajakavitha1** [comment]
Hi @lkshminarayanan !!! I need some clarifications about the update that needs to be made.
My understanding is that in Timescale Cloud : ```The tsdbadmin user is the owner of the database, but is not a superuser. You cannot access the postgres user. There is no superuser access to Timescale Cloud databases.```. The update needs to be made to https://docs.timescale.com/self-hosted/latest/troubleshooting/ with the error message and the work around that you suggested right?

**Comment by lkshminarayanan** [comment]
Hi @Rajakavitha1,

This does not affect Cloud and MST users as we have fixes in place already to grant the required access to them. This only affects the on-prem/open source users.

Regarding where to make the update, there is also this section - https://docs.timescale.com/self-hosted/latest/backup-and-restore/pg-dump-and-restore/ - we can put this new content either here or at the section you mentioned. 

Thank you for looking into this!
