### ISSUE TITLE
[Site Bug] Windows Compiled Binaries are not Accessible

### ISSUE THREAD

**Issue by DeltaSignalAB** [timescale/docs#2237]
_Use this template for reporting bugs in the docs._

# Describe the bug

The download links of the Windows binaries are not working, the following page is shown:

![image](https://user-images.githubusercontent.com/83111697/230151699-eef09395-d25b-422b-baa0-d6395367abc9.png)

## What do the docs say now?
The docs say that you can download the binaries.

## What should the docs say?
The docs are correct but the binaries are not accessible.

# Page affected

**Windows Installation Page** (https://docs.timescale.com/self-hosted/latest/install/installation-windows/#windows-releases) with the following links:

* https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-14_latest-windows-amd64.zip
* https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-15_latest-windows-amd64.zip
* https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-13_latest-windows-amd64.zip
* https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-12_latest-windows-amd64.zip

# Subject matter expert (SME)
Sadly I am quite new to this project so don't know no one here who would be responsible for this.

# Screenshots

![image](https://user-images.githubusercontent.com/83111697/230151699-eef09395-d25b-422b-baa0-d6395367abc9.png)

# Any further info

According to the error message the Microsoft hosted account was disabled for some reason.

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by charislam** [comment]
Thanks for the report!

The hosting problem is a temporary issue that we're aware of. For now, you can download the latest Windows binaries from our GitHub release page: https://github.com/timescale/timescaledb/releases
