### ISSUE TITLE
[Site Bug] Issue with the page: /self-hosted/latest/install/installation-windows/

### ISSUE THREAD

**Issue by devgauravjava** [timescale/docs#2265]
_Use this template for reporting bugs in the docs._

# Describe the bug

Windows releases for timescaleDB is not downloadable from the given link 

## What should the docs say?

# Page affected

https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-15_latest-windows-amd64.zip

# Subject matter expert (SME)

Don't know

# Screenshots

![image](https://user-images.githubusercontent.com/96240922/232164191-3f69eccf-f5c2-4f8c-8fe4-c396938f156e.png)

# Any further info

https://docs.timescale.com/self-hosted/latest/install/installation-windows/

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
Thanks, we're aware of the issue 👍

**Comment by devgauravjava** [comment]
I have built it from the source. Thanks for looking into it.
