### ISSUE TITLE
[Feedback] Page: /tutorials/latest/ingest-real-time-websocket-data/

### ISSUE THREAD

**Issue by abraxxa** [timescale/docs#2286]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

The Python code example at https://docs.timescale.com/tutorials/latest/ingest-real-time-websocket-data/#implement-batching-with-psycopg2 has an error.
Line 25 `execute_values(cursor, sql, data)` should use `current_batch`, not `data`. Please check if `execute_values`  can be passed the `current_batch` array directly before updating the docs as I'm not familiar with it.

**Comment by Rajakavitha1** [comment]
Hi @abraxxa ! the guide was validated and updated and here is the latest documentation: https://docs.timescale.com/tutorials/latest/ingest-real-time-websocket-data/. Closing this issue for now. Please let us know if any other issues needs to be addressed in the document.
