### ISSUE TITLE
[Site Bug] Issue with the page: /use-timescale/latest/ha-replicas/read-scaling/

### ISSUE THREAD

**Issue by DmitriiAn** [timescale/docs#2301]
_Use this template for reporting bugs in the docs._

# Describe the bug

At the bottom of the page appeared "[read-only-role]:" 
It looks like a bug. 

## What should the docs say?

# Page affected

https://docs.timescale.com/use-timescale/latest/ha-replicas/read-scaling/

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

![Screenshot 2023-04-21 at 11 00 21](https://user-images.githubusercontent.com/34400483/233594016-6881f21e-75bb-4992-9ef3-1fe13479e7a6.png)

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by akhil27styles** [comment]
could you assign me this issue?

**Comment by Loquacity** [comment]
> could you assign me this issue?

Feel free to open a PR with the fix, if you want to! Details on how to contribute are here: https://docs.timescale.com/about/latest/contribute-to-docs/

**Comment by Rajakavitha1** [comment]
Just checked the page and it appears okay.
<img width="770" alt="Screenshot 2023-05-15 at 10 58 17 AM" src="https://github.com/timescale/docs/assets/37059749/032f300f-5342-4998-acb6-bbf203b0d160">
@DmitriiAn  marking this issue as closed. Please feel free to reopen if any other issue needs to be addressed in the docs.
