### ISSUE TITLE
[Feedback] Page: /api/latest/continuous-aggregates/refresh_continuous_aggregate/

### ISSUE THREAD

**Issue by danielbtrontal** [timescale/docs#2303]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

In the required arguments section, type column, there is a typo: `TIMESTAMPZ` is written instead of `TIMESTAMPTZ`.

**Comment by Rajakavitha1** [comment]
fixed in https://github.com/timescale/docs/pull/2369
