### ISSUE TITLE
[Site Bug] Issue with the page: /api/latest/continuous-aggregates/refresh_continuous_aggregate/

### ISSUE THREAD

**Issue by marcvanR** [timescale/docs#2305]
When I call an incremental refresh of a continuous aggregate it fails when it hits a window where it should actually do a refresh. 

[Provide as much detail as you can]

I run as per example (but changed to fit my data)
```
DO
$$
DECLARE
  refresh_interval INTERVAL = '12h'::INTERVAL;
  start_timestamp TIMESTAMPTZ = '2023-03-01T00:00:00Z';
  end_timestamp TIMESTAMPTZ = start_timestamp + refresh_interval;
BEGIN
  WHILE start_timestamp < '2023-04-21T00:00:00Z' LOOP
    CALL refresh_continuous_aggregate('my_continuous_aggregate', start_timestamp, end_timestamp);
    RAISE NOTICE 'finished with timestamp %', end_timestamp;
    start_timestamp = end_timestamp;
    end_timestamp = end_timestamp + refresh_interval;
  END LOOP;
END
$$;
```

But when it hits the timewindow which has not been materialized yet it states:

```
ERROR:  procedure refresh_continuous_aggregate(unknown, timestamp with time zone, timestamp with time zone) does not exist
LINE 1: CALL refresh_continuous_aggregate('my_continuo..
             ^
HINT:  No procedure matches the given name and argument types. You might need to add explicit type casts.
QUERY:  CALL refresh_continuous_aggregate('my_continuous_aggregate', start_timestamp, end_timestamp)
CONTEXT:  PL/pgSQL function inline_code_block line 8 at CALL
```

Which follows the example exactly so I don't understand whats going wrong here. If I perform the Call by hand for that timeframe it finishes as expected.

https://docs.timescale.com/api/latest/continuous-aggregates/refresh_continuous_aggregate/

# Subject matter expert (SME)

# Screenshots

# Any further info

I'm running 
timescaledb 2.10.1 
postgresql 14.7
on Ubuntu 14.7-1.pgdg20.04+1

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
Hi @marcvanR for help with this, you can check out our community Slack and forum: https://www.timescale.com/community/
