### ISSUE TITLE
[Feedback] Page: /self-hosted/latest/install/installation-windows/

### ISSUE THREAD

**Issue by billpieper** [timescale/docs#2309]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

When you click the link to download timescaledb:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/682286/234087660-77636ae5-67de-43f0-bc30-c993619cb44e.png">

The following is what is returned:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/682286/234087469-e6d21339-deff-4b40-9eec-ace762b538b9.png">

**Comment by Loquacity** [comment]
We are aware of the problem, and are working on it. Thanks for the report!
