### ISSUE TITLE
[Content Bug] Dead link in "Migrate schema and data separately"

### ISSUE THREAD

**Issue by Scarjit** [timescale/docs#2316]
# Describe the bug

In the [Migrate schema and data separately](https://docs.timescale.com/self-hosted/latest/migration/schema-then-data/#migrate-schema-and-data-separately) page, the link to "migrating an active database" is dead.

# Page affected

https://docs.timescale.com/self-hosted/latest/migration/schema-then-data/

# Screenshots

![image](https://user-images.githubusercontent.com/6317420/234507212-268dc9d1-0799-4468-9b87-56d9d06fcf8b.png)

![image](https://user-images.githubusercontent.com/6317420/234508050-e437014b-542d-4c8a-a151-4472b465f403.png)

# Any further info

This was not catched by the markdown checker.
https://github.com/timescale/docs/actions/runs/4802984123/jobs/8547030013#step:4:3217

**Comment by Rajakavitha1** [comment]
fixed in https://github.com/timescale/docs/pull/2369
