### ISSUE TITLE
[Feedback] Page: /api/latest/compression/add_compression_policy

### ISSUE THREAD

**Issue by Petwag** [timescale/docs#2335]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

This page doesn't contain the schedule_interval parameter

**Comment by jonatas** [comment]
Hi @Petwag, thanks for reporting.

@Loquacity we need to also document [this param](https://github.com/timescale/timescaledb/blob/8ae2da6260c7de68808db918371f8aacafce8332/sql/policy_api.sql#L50C9-L50C9) and as we can assume it's a schedule interval and will be recurring as as a background action it's configured. Similar to the one in the add_retention_policy.
