### ISSUE TITLE
[Feedback] Page: /tutorials/latest/telegraf-output-plugin/

### ISSUE THREAD

**Issue by londondaintta** [timescale/docs#2336]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

The deprecation warning on this page is confusing and no longer valid. Either I suggest it is removed or the page re-directs to https://docs.timescale.com/use-timescale/latest/ingest-data/ingest-telegraf/.

**Comment by Rajakavitha1** [comment]
Hi @londondaintta This has now been addressed in https://github.com/timescale/docs/pull/2353/files. Marking this issue as closed. Please feel free to reopen if any other issues needs to be addressed in the docs. 
PR 2353 :```This removes the tutorials that contain links to the content that is no longer accessible. Content is still in the repo, just renamed and removed from the nav (in case we decide to resurrect them).```
