### ISSUE TITLE
[Feedback] Add information about ingesting message queue data to Python Quick Start. Page: /quick-start/latest/python/

### ISSUE THREAD

**Issue by tubakhan0415** [timescale/docs#2365]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

Please also give the information regarding the integration of data from mqtt platform

**Comment by Loquacity** [comment]
@jonatas Not sure if this is something we can actually do. What do you think?

**Comment by jonatas** [comment]
Hi @tubakhan0415 , thanks for the suggestion.

Our quick starts are really to be quick and just to show the shortest path to put the information.

If you're going to use mqtt or other technologies, it's a matter of mixing the info with what you already have in places. Our objective in the quick start is just bring the minimal setup to allow you to get started and not get deep into the content about building more complex environments like message queue.

We have a few tutorials that can also help you to get there but we don't have anything with mqtt which is just one protocol. The closest one I guess is from [websockets](https://docs.timescale.com/tutorials/latest/ingest-real-time-websocket-data/).

Here are a few resources available on github that are doing it. They can serve you as a starting point as well. Example:

https://github.com/tobymurray/mqtt-to-timescaledb
https://github.com/alphonse82/mqtt-to-sql can optionally use Timescaledb.
https://github.com/lordspacehog/correly

I'm closing this issue and will check with @contentana to put it on track of next content to develop inside our tutorials or blogs.

**Comment by tubakhan0415** [comment]
Sir/Ma'am
I want to ingest Hivemq received data in timescale db via python .Please
help me ASAP
I have an urgent project

**Comment by jonatas** [comment]
Hi @tubakhan0415, if you have some urgency, please, [announce a Job](https://www.timescale.com/forum/c/conversation-community/jobs/9) in our forum, maybe you can find some freelance to help you.
