### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/connecting/psql/

### ISSUE THREAD

**Issue by midito** [timescale/docs#2366]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

On [this specific line](https://github.com/timescale/docs/blob/75bbf6179f195887cc4e070c1346476a0e03f17c/use-timescale/connecting/psql.md?plain=1#LL66C7-L66C7), the code attached doesn't seem to work for me.

```
Warning: No available formula with the name "postgres". Did you mean postgrest or postgis?
postgresql breaks existing databases on upgrade without human intervention.

See a more specific version to install with:
  brew formulae | grep postgresql@
```

In the documentation, the code shown is: 
`brew install postgres`

What works for me is:
`brew install postgresql`

**Comment by Rajakavitha1** [comment]
Fixed in https://github.com/timescale/docs/pull/2369
