### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/ingest-data/ingest-prometheus/

### ISSUE THREAD

**Issue by gvelez17** [timescale/docs#2378]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

uh this has no details on how to get data scraped from a prometheus compatible endpoint into timescaledb.  it just says what prometheus is

**Comment by Loquacity** [comment]
@jonatas We have this same kind of stub for the Kafka one as well. I know @Rajakavitha1 updated the Telegraf one fairly recently. Who could we talk to for information to update these ones as well?

**Comment by jonatas** [comment]
Sorry for being late here. I'm not sure how exactly are we going to handle due to the deprecation of Promscale. I'm not sure if we're going to maintain such page as promscale was doing the ingestion before.

@ramonguiu is probably the right person to talk about this here.

**Comment by Loquacity** [comment]
> Sorry for being late here. I'm not sure how exactly are we going to handle due to the deprecation of Promscale. I'm not sure if we're going to maintain such page as promscale was doing the ingestion before.
> 
> @ramonguiu is probably the right person to talk about this here.

I was thinking you would say that 😉 It might be that we just drop these pages with the new integrations content ...
