### ISSUE TITLE
[Feedback] Page: /quick-start/latest/ruby/

### ISSUE THREAD

**Issue by jeromepl** [timescale/docs#2393]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Step 6 of "Connecting to TimescaleDB" contains the wrong database migration code.

It currently says
```rb
class AddTimescale < ActiveRecord::Migration[7.0]
  def change
   create_table :page_loads, id: false do |t|
      t.string :user_agent

      t.timestamps
   end
  end
end
```

but that is the migration code for creating a page_loads table, corresponding to step 2 of the "Creating a relational database" part of the guide

**Comment by Loquacity** [comment]
@jonatas I believe the Ruby one is your baby? 😉

**Comment by Rajakavitha1** [comment]
Hi @jeromepl  I checked the docs and the my app folder that I had created when validating this guide.

The step 6 in  "Connecting to TimescaleDB" in 
<migration-datetime>_add_timescale.rb is:
```
class AddTimescale < ActiveRecord::Migration[7.0]
  def change
   create_table :page_loads, id: false do |t|
      t.string :user_agent


      t.timestamps
   end
  end
 end
```
and the step 2 in "Creating a relational table in <migration-datetime>_create_page_loads.rb is:
```
class CreatePageLoads < ActiveRecord::Migration[7.0]
  def change
    create_table :page_loads, id: false do |t|
      t.string :user_agent

      t.timestamps
    end
  end
end
```
