### ISSUE TITLE
[Feedback] Page: /self-hosted/latest/upgrades/upgrade-docker/

### ISSUE THREAD

**Issue by hexxone** [timescale/docs#2401]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Hi there,
I am trying to get rid of the following notices, which get printed quite frequently.

```
2023-05-24 18:42:01 global_postgres  | 2023-05-24 16:42:01.917 UTC [28596] LOG:  the "timescaledb" extension is not up-to-date
2023-05-24 18:42:01 global_postgres  | 2023-05-24 16:42:01.917 UTC [28596] HINT:  The most up-to-date version is 2.11.0, the installed version is 2.10.2.
```

Even when using the freshly pulled "latest" `timescale/timescaledb-ha:pg14-latest` docker image I noticed the message directly appears after starting.

Even when using a complete fresh image and postgres data.

Also

The "Note":
```
If you have multiple databases, you need to update each database separately.
```

is not really clear to me.

I have multiple Databases and Users, and each User gets granted Permissions on his own "dedicated" database.

The initial_setup script looks something like this:
```bash
#...

# create specified database, User and Access Permission to database for User.
for user_record in $POSTGRES_EXTRA_USERS; do
    user_name=$(echo $user_record | cut -d':' -f1)
    user_password=$(echo $user_record | cut -d':' -f2)
    database_name=$(echo $user_record | cut -d':' -f3)

    db_exists=$(psql -tAc "SELECT 1 FROM pg_database WHERE datname='$database_name'" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB")
    user_exists=$(psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$user_name'" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB")

    if [[ -z "$db_exists" ]]; then
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE DATABASE "$database_name";
EOSQL
		echo "Created DB '$database_name'"
    fi

    if [[ -z "$user_exists" ]]; then
        # Create the user if it doesn't exist
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE USER "$user_name" WITH PASSWORD '$user_password';
EOSQL
		echo "Created User '$user_name'"
    fi

    # Grant privileges on the database to the user
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        GRANT ALL PRIVILEGES ON DATABASE "$database_name" TO "$user_name";
EOSQL
	echo "Granted User '$user_name' permissions on DB '$database_name'"
done

#...
```

While I assume that's not the problem I am not 100% sure about it.

Do I manually have to install / update the timescale extension even on freshly created Databases?

e.g. after `CREATE DATABASE foobar` do something like: 
`CREATE EXTENSION IF NOT EXISTS timescaledb_toolkit ON <foobar>; 
ALTER EXTENSION timescaledb_toolkit UPDATE on <foobar>;` ?

Or is there any other way to get rid of this message?

Thanks in advance.

**Comment by Rajakavitha1** [comment]
@jonatas can you help us with query.

**Comment by jonatas** [comment]
Hi @hexxone, thanks for the feedback. I'm not sure I understood how it's related to docker here as I see you used it in the table.

Interesting to see that you have a very customized scenario. The message `If you have multiple databases, you need to update each database separately.` means that you need to run the `ALTER EXTENSION timescaledb UPDATE' and `ALTER EXTENSION timescaledb_toolkit UPDATE' for each database you have. 

I cannot run your script here and it seems it would be a too specific section to be part of the upgrade-docker documentation or maybe I'm missing something. If this is not related to docker, it would be awesome if we can come up with a new section about how to handle multiple databases on upgrades in general and even your scripts would be useful to show a small real scenario example as a convenience.

**Comment by jonatas** [comment]
@Rajakavitha1 I'm not sure if we can come up with a single query and @hexxone already showed how to build a simple recursive system to navigate in the multiple databases. I like that we received the feedback and probably more people are needing the same.

**Comment by hexxone** [comment]
Hi and thanks for the reply!

> I'm not sure I understood how it's related to docker here as I see you used it in the table.

To clarify, my main question was if the "verion outdated" message gets printed because

- A: the docker-included timescale version was outdated from the latest "release upstream" or
- B: if its just an issue because I have multiple databases and need to update them by hand ^^

but it seems the answer to that is `B` ?

> Interesting to see that you have a very customized scenario. The message `If you have multiple databases, you need to update each database separately.` means that you need to run the `ALTER EXTENSION timescaledb UPDATE' and `ALTER EXTENSION timescaledb_toolkit UPDATE' for each database you have.

Yes, thanks for the info.

But is there a way to do this updating from "outside" of the targeted Database using some special Syntax like e.g. ` ON NewDatabase` ?

E.g. can I do this: ?
```bash
    if [[ -z "$db_exists" ]]; then
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE DATABASE "$database_name";
            ALTER EXTENSION timescaledb UPDATE ON "$database_name";
            ALTER EXTENSION timescaledb_toolkit UPDATE ON "$database_name";
EOSQL
		echo "Created DB '$database_name'"
    fi
```

or do I have to be explicitly connected on the correct Database seperately? like so:

```bash
    if [[ -z "$db_exists" ]]; then
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE DATABASE "$database_name";
EOSQL

        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$database_name" <<-EOSQL
            ALTER EXTENSION timescaledb UPDATE;
            ALTER EXTENSION timescaledb_toolkit UPDATE;
EOSQL
		echo "Created DB '$database_name'"
    fi
```

This was my 2nd question ^^

> I cannot run your script here and it seems it would be a too specific section to be part of the upgrade-docker documentation or maybe I'm missing something. If this is not related to docker, it would be awesome if we can come up with a new section about how to handle multiple databases on upgrades in general and even your scripts would be useful to show a small real scenario example as a convenience.

I am mounting the script inside of the timesclae docker container like so using compose.
It then runs only once on the initial "pgdata" setup of the db.

```
services:
  db:
    container_name: global_postgres
    hostname: global_postgres
    image: timescale/timescaledb-ha:pg14-latest
    ports: # for local dev
       - "5432:5432"
    environment:
       POSTGRES_DB=global_postgres_db
       POSTGRES_USER=postgres
       POSTGRES_PASSWORD=somecomplicatedpassword
       POSTGRES_EXTRA_USERS="user1:password1:db1,user2:password2:db2,user3:password3:db3"
    volumes:
      - ./initial_setup.sh:/docker-entrypoint-initdb.d/initial_setup.sh
      - data_volume:/home/postgres/pgdata/data
```

I'll gladly provide more information or an complete example :)

Thanks in advance!

**Comment by jonatas** [comment]
OMG, I just missed the notifications for this thread. Sorry for that.

I think you need to be explicit connected to the DB to be able to alter the extension.

I'd do a small script to navigate on all dbs and then execute the command sequentially or parallelize it. I'm not aware of any way to make it from a single database as the database is a part of the connection information. So, you need to exchange connection info. Maybe using FDW you could be able to connect into other dbs from the same host but I never tried it too.

**Comment by Rajakavitha1** [comment]
@jonatas  and @hexxone I am marking this issue as closed for now because this seems more like an enhancement request. Please feel free to open a PR with the details of the enhancement . The Docs team is more than happy to review and merge the PR if this is an enhancement that many would like to have.

**Comment by hexxone** [comment]
> I think you need to be explicit connected to the DB to be able to alter the extension.

Ok no problem, thanks for the explanation :)
