### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/ingest-data/ingest-telegraf/

### ISSUE THREAD

**Issue by bradleynohreiter** [timescale/docs#2407]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Is the final code box in the "[Configuring the PostgreSQL output plugin](https://docs.timescale.com/use-timescale/latest/ingest-data/ingest-telegraf/#configuring-the-postgresql-output-plugin)" section correct? The whole section is commented out, but I get the following error when I try to uncomment it - `E! error loading config file /etc/telegraf/telegraf.conf: error parsing data: line 211: invalid TOML syntax`
I get the following error when I replace the backticks with quotes - `error loading config file /etc/telegraf/telegraf.conf: plugin outputs.postgresql: line 168: configuration specified the fields ["table_template"], but they weren't used`

**Comment by Rajakavitha1** [comment]
Hi @bradleynohreiter !!! This has been addressed in https://github.com/timescale/docs/pull/2394. Here is the preview of the updates that were made to the documentation: https://docs-dev.timescale.com/docs-telegraf-update-rajie/use-timescale/telegraf-update-rajie/ingest-data/ingest-telegraf/. These updates will be live on the website after the PR is merged. Hope you find this helpful. Closing this issue for now. Please feel free to reopen if any other issue persists.
