### ISSUE TITLE
[Feedback] Page: /quick-start/latest/node/

### ISSUE THREAD

**Issue by samlaf** [timescale/docs#2415]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

The section [create-a-relational-table](https://docs.timescale.com/quick-start/latest/node/#create-a-relational-table) jumps directly to generating a model, without having initialized the sequelize cli or defined the model... this results in
```
ERROR: Unable to find models path (...). Did you run sequelize init?
```

One only has to follow the error message and run `npx sequelize init`, but this just brings up a lot of questions as a new-time sequelize user: "I've already used sequelize above, why is it not initialized? How have I been able to even use it without initializing it? etc". Would help to have a bit of explanation to explain the difference between using the sequelize library in code, and the sequelize-cli and its related folder structure.

EDIT: continuing through the tutorial, there's actually a bunch of other errors that creep up. Seems like the tutorial is just out-of-date with the newest sequelize version (6.6.0).

For example, next error is when running `npx sequelize db:migrate`:
```
ERROR: Please install mysql2 package manually
```
One needs to go in the config.json file and change the dialect from mysql to postgres, but this config.json file was nowhere mentioned up to this point. One basically ends up needing to go and read the sequelize docs, which is not ideal for a short self-contained tutorial.

**Comment by Loquacity** [comment]
@noctarius I'm fairly certain we discussed this as being one of the problems with this quick start when worked on it earlier in the year. Is there anything we can do to improve this particularly, or are you still of the mind that we need to completely redo this one?
