### ISSUE TITLE
[Content Bug] VPC not all caps in console docs

### ISSUE THREAD

**Issue by solugebefola** [timescale/docs#2417]
# Describe the bug
"VPC" is capital case instead of all caps in the title page for the console section of the docs.  It's an initialism for "Virtual Private Cloud", so it should be all caps (and _is_ all caps elsewhere in the console docs).

# Page affected
https://docs.timescale.com/console/

# Screenshots
![image](https://github.com/timescale/docs/assets/12288273/a14b13d1-beea-4f7f-8e3f-f340557f58ab)

**Comment by Loquacity** [comment]
@charislam I think this one might be for you?
