### ISSUE TITLE
[Docs RFC] Improve random usage from quick starts

### ISSUE THREAD

**Issue by jonatas** [timescale/docs#2424]
This is a feedback from a office hours session and we also have [this thread](https://timescaledb.slack.com/archives/C4GT3N90X/p1681892714990569?thread_ts=1681834450.199699&cid=C4GT3N90X) on Slack.

# Subject matter expert (SME)

@jonatas @noctarius 

The numbers are related to temperature and other measurements that have a very limited precision in the decimals. The problem is that we have temperatures like:

2.31238131728371273
50.192839128391283

The feedback that Francesco brought is that exporting this numbers he have a big csv when what he wants is something rounding the numbers like:

2.31
50.19

In our examples we use several columns that are for metrics that are all fake values, but when people are trying the tutorials they also build experiments like exporting or visualizing the data. Rounding  decimals will help in both cases.

Examples of how we can resolve the problem:

```
 SELECT random() FROM generate_series(1,5) i;
┌─────────────────────┐
│       random        │
├─────────────────────┤
│   0.045653177538167 │
│  0.1306235101773794 │
│  0.4238928747791597 │
│  0.6574247272019278 │
│ 0.05654559145508742 │
└─────────────────────┘
(5 rows)
```

Use `::numeric(6,2)` to limit the value as rounded.

```sql
playground=# SELECT random()::numeric(6,2) FROM generate_series(1,5) i;
┌────────┐
│ random │
├────────┤
│   0.47 │
│   0.69 │
│   0.94 │
│   0.54 │
│   0.35 │
└────────┘
(5 rows)

```

Fast searching in the command line I see the following files that could be improved:

```
use-timescale/distributed-hypertables/about-distributed-hypertables.md
198:    non-immutable function is [`random()`][random-func], which depends on the

quick-start/python.md
284:                                random()*100 AS temperature,
285:                                random() AS cpu;
330:                                    random()*100 AS temperature,
331:                                    random() AS cpu;

quick-start/java.md
358:                floor(random() * 4 + 1)::INTEGER,
359:                random()
520:                    floor(random() * 4 + 1)::INTEGER,
521:                    random()
611:                    floor(random() * 4 + 1)::INTEGER,
612:                    random()

quick-start/golang.md
431:            floor(random() * (3) + 1)::int as sensor_id,
432:            random()*100 AS temperature,
433:            random() AS cpu
542:            floor(random() * (3) + 1)::int as sensor_id,
543:            random()*100 AS temperature,
544:            random() AS cpu
656:            floor(random() * (3) + 1)::int as sensor_id,
657:            random()*100 AS temperature,
658:            random() AS cpu

tutorials/simulate-iot-sensor-data.md
114:  random() AS cpu,
115:  random()*100 AS temperature

tutorials/custom-timescaledb-dashboards.md
285:  SELECT time, (random()*30)::int, random()*80 - 40
```

I removed some items of this list, so maybe we should verify again all the calls.

**Comment by Loquacity** [comment]
This appears to have been fixed when we re-did the Quick Starts
