### ISSUE TITLE
[Site Bug] Issue with the page: /use-timescale/latest/metrics-logging/integrations/

### ISSUE THREAD

**Issue by everhardt** [timescale/docs#2448]
_Use this template for reporting bugs in the docs._

# Describe the bug

This page is missing information on which IAM policy is required for the exporter user.

## What do the docs say now?
Nothing

## What should the docs say?
An example like:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:DescribeLogStreams",
                "logs:CreateLogGroup",
                "logs:PutLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:[region]:[accountid]:log-group:[loggroupname]:log-stream:[streamname]",
                "arn:aws:logs:[region]:[accountid]:log-group:[loggroupname]"
            ]
        }
    ]
}
```

I did try this out just now, but I think my policy is incorrect.

# Page affected

https://docs.timescale.com/use-timescale/latest/metrics-logging/integrations/

**Comment by Rajakavitha1** [comment]
Hi @everhardt !!! Thank you for the feedback. There is a link to the official documentation to create IAM user. https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html#id_users_create_console. Also there is an optional step that reads: "Define an IAM role to use for uploading metrics. Having a dedicated role with only CloudWatch permissions is a recommended security practice." Closing this issue for now. Please feel free to reopen if any other details needs to be updated in the documentation.

**Comment by everhardt** [comment]
Hi @Rajakavitha1, I don't want to give the exporter access to all CloudWatch resources, which is why I specified them in the IAM policy above. Unfortunately this does not seem to be working, as I still have not received any Timescale logs. An example IAM with limited access would be highly appreciated and I think also something to include in the docs as best practice.

**Comment by Rajakavitha1** [comment]
Thank you for the additional information @everhardt. I just reopened the issue so that the documentation team can address it.

**Comment by srieding** [comment]
Hi @Rajakavitha1 any news on this?

**Comment by Loquacity** [comment]
> Hi @Rajakavitha1 any news on this?

Hi @srieding This issue queue is for requesting changes in the docs, and this issue has been prioritised in our backlog, and is waiting for additional feedback. If you need support, I suggest you start with the [Timescale Community](https://www.timescale.com/community/).

**Comment by everhardt** [comment]
@Loquacity why did you close this ticket?

**Comment by Loquacity** [comment]
> @Loquacity why did you close this ticket?

If you need support, I suggest you start with the the [Timescale Community](https://www.timescale.com/community/). As it is, we don't have the resources or the capability to add this additional content in to the documentation at this time.
