### ISSUE TITLE
[Site Bug] Issue with the page: /all

### ISSUE THREAD

**Issue by Banzaika** [timescale/docs#2453]
## please, make sure that value of your code window is not translated by google translate

```[tasklist]
### Tasks
```

**Comment by Loquacity** [comment]
Thanks for this report. Are you able to share a screenshot of what is happening?

**Comment by Banzaika** [comment]
just try to translate the page where there is a window with the code into Russian

**Comment by Loquacity** [comment]
Yes, I see it:

![image](https://github.com/timescale/docs/assets/3914967/aa828368-1cd9-49ad-8dc8-eb2710f9705d)

I'm not sure if there's anything we can do to force Google to not translate those bits. But I'll put this in the docs engineering queue, perhaps they can come up with something clever 😉

**Comment by shahriarpshuvo** [comment]
This issue has been resolved now!
Thank you for the report.
