### ISSUE TITLE
[Feedback] Page: /self-hosted/latest/compression/

### ISSUE THREAD

**Issue by bencoppock** [timescale/docs#2498]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

> Due to the nature of the compression mechanism, they cannot effectively ingest data while compressed

I'm thinking this may be out of date. From what I understand, version 2.10 and 2.11 greatly improve backfilling into compressed chunks.

**Comment by Rajakavitha1** [comment]
@iroussos could you please help us rewrite the issue reported so that it is technically accurate.

**Comment by Loquacity** [comment]
> @iroussos could you please help us rewrite the issue reported so that it is technically accurate.

The info you need is here, I think: https://docs.timescale.com/use-timescale/latest/compression/modify-compressed-data/

**Comment by iroussos** [comment]
The link Lana provided is correct, but may be missing some information. For newly introduced features, remember to always check the [Product enablement page](https://timescale.slab.com/posts/product-enablement-smwtqbg4) for relevant enablement documents, presentations and recording of sessions. 

Quick links for reference: 
- [[Enablement] - Mutable Compression](https://docs.google.com/document/d/1vwz4UmjwUFlKk3ORDCeyX2vczrIGOWREmNu0y1oM-Ec/edit)
- [Mutable Compression - Enablement Session](https://docs.google.com/presentation/d/1ykMlhV355bJIoU1YunnImTiBafIfLvJ_cUmBbXnDtIQ/edit) presentation [(recording)](https://timescale.zoom.us/rec/share/WZwOeZ1ng3D5OeLI9FVVMwPvAqMb4JAKwYRPuzU-Vss6JF8Ytb8_PxvoxhLKZnUf.nQzWAvyivCY3K0X8?pwd=uPTvxEjlJmw_hShNHKn6n2woURE7CnXe)

**Comment by Rajakavitha1** [comment]
Hi @bencoppock !!! The issue that you reported does not exist in our latest updated docs anymore.
<img width="700" alt="Screenshot 2023-07-15 at 5 32 43 PM" src="https://github.com/timescale/docs/assets/37059749/77cc59ec-c5db-43cd-ac83-677665918dbd">

The doc does provide information about 2.10  and 2.11 and how ingestion works. Making this issue as closed now. Please feel free to reopen if any other issue needs to be addressed.
