### ISSUE TITLE
[Site Bug] Issue with the page: /tutorials/latest/energy-data/dataset-energy/ Typo

### ISSUE THREAD

**Issue by gina-alioto** [timescale/docs#2500]
_Use this template for reporting bugs in the docs._

# Describe the bug
typo

[Provide as much detail as you can]

## What do the docs say now?
This tutorial uses the enegry consumption data for over a year in a typical household. 

## What should the docs say?
This tutorial uses the energy consumption data for over a year in a typical household. 

# Page affected
/tutorials/latest/energy-data/dataset-energy/

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Rajakavitha1** [comment]
Fixed
