### ISSUE TITLE
[Content Bug] TS for connecting to Timescale

### ISSUE THREAD

**Issue by Rajakavitha1** [timescale/docs#2503]
_Use this template for reporting bugs in the docs._

# Describe the bug

The link to https://docs.timescale.com/use-timescale/latest/integrations/query-admin/troubleshooting/ results in a 403. The troubleshooting sections are picked from the partials and they don't seem to be working.

## What should the docs say?

# Page affected

[Provide the URL to the page you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by charislam** [comment]
Hey Rajie! Which troubleshooting items are supposed to show up on this page?

I think the problem is that they're supposed to have `query admin` set under `topics` in frontmatter, but I just grepped the repo and didn't find any with that topic. You can see an example here of how to set it up for continuous aggregates: https://github.com/timescale/docs/blob/4c8126c1e716ae6f5e2ea2f5a04b180e8d753ef8/_troubleshooting/cagg-watermark-in-future.md?plain=1#L5

**Comment by Rajakavitha1** [comment]
> Hey Rajie! Which troubleshooting items are supposed to show up on this page?
> 
> I think the problem is that they're supposed to have `query admin` set under `topics` in frontmatter, but I just grepped the repo and didn't find any with that topic. You can see an example here of how to set it up for continuous aggregates:
> 
> https://github.com/timescale/docs/blob/4c8126c1e716ae6f5e2ea2f5a04b180e8d753ef8/_troubleshooting/cagg-watermark-in-future.md?plain=1#L5

Hi @charislam I set 'query admin` and `intergrations` under topics in the front matter, it still does not appear. My guess is that we have it nested under integrations/query-admin/.

**Comment by charislam** [comment]
Ah yes, you're right. It should be `integrations/query admin` then

**Comment by Rajakavitha1** [comment]
> Ah yes, you're right. It should be `integrations/query admin` then

Thank you @charislam `integrations/query admin' worked!!!!!
