### ISSUE TITLE
[Site Bug] Issue with the page: /tutorials/latest/blockchain-query/beginner-blockchain-query/

### ISSUE THREAD

**Issue by JohnSweeney85** [timescale/docs#2518]
_Use this template for reporting bugs in the docs._

The bitcoin dataset: https://assets.timescale.com/docs/downloads/bitcoin-blockchain/bitcoin_sample.zip
All rows in tutorial_bitcoin_sample.csv column:
  is_coinbase = FALSE 

The rest of the queries will not work since they are based on is_coinbase. 

https://docs.timescale.com/tutorials/latest/blockchain-query/beginner-blockchain-query/.  

The docs should add an extra query 

"UPDATE transactions 
SET is_coinbase = true 
WHERE fee_usd = 0 ;"

# Page affected

/tutorials/latest/blockchain-query/beginner-blockchain-query/

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
Whenever you download the dataset, you get updated data, so I suspect that it's mostly just bad luck that when you downloaded it, that there were no coinbase transactions. I suggest trying again in a few days. This is the problem with live data!
