### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/compression/compress-chunks/

### ISSUE THREAD

**Issue by maartenderie** [timescale/docs#2519]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

I can't find the 'create policies' button as describe in this documentation. Could the docs be outdated? Thanks!

**Comment by Rajakavitha1** [comment]
Hi @maartenderie !!! Thank you for the feedback. The Compression section under Use Timescale refers to the Compression explorer which was a beta feature that is no longer available or has been discontinued. You can find the updated docs here: https://docs.timescale.com/use-timescale/latest/compression/. Closing this issue for now. Please feel free to reopen if any other issues needs to be addressed in the documentation.
