### ISSUE TITLE
[Docs RFC] Add shortcut for uploading tutorial data for Mac and Linux

### ISSUE THREAD

**Issue by charislam** [timescale/docs#2524]
# Describe change in content, appearance, or functionality

Uploading data to start our tutorials can take anywhere from 15-20 minutes, even on a fast connection. The blocker is the size of the data + upload speed.

There is a proposal to upload the data in chunks, so users can start querying faster (the first queries do not require the full dataset). There is a quick way to do this via shell script in Mac and Linux, as investigated and documented by @joelshet: https://iobeam.slack.com/archives/C020ABTATCJ/p1688162362585339 (We don't currently have a Windows equivalent, but this will help a large chunk of our users as a first step. Also, WSL exists...? 😉)

Let's:
1. Independently test and validate the steps on Mac and Linux. (Just to be triple sure since tutorial bugs are annoying and turn away readers.)
2. Add this available shortcut as a callout in the "upload data" step of our tutorials.

# Subject matter expert (SME)

@joelshet 

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to suggest a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
I believe this has been resolved in a different way.
