### ISSUE TITLE
[Feedback] Page: /mst/latest/vpc-peering/vpc-peering-azure/

### ISSUE THREAD

**Issue by supernice-mm** [timescale/docs#2554]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

The CLI tool used in the documentation is outdated since years and at least the "--available-to-other-tenants" is not available anymore

**Comment by Rajakavitha1** [comment]
@vishaldhiman Please help us with this.

**Comment by Loquacity** [comment]
> @vishaldhiman Please help us with this.

We'll need to find a new SME for this.

**Comment by vishaldhiman** [comment]
Hi Lana,
   I’m no longer at timescale. You can use the timescale MST account to try
and recreate the steps. Choose Azure while doing it. Alternatively, work
with Jason Hepp at Aiven to get a new account.

Vishal

**Comment by Rajakavitha1** [comment]
@Loquacity ^^^^
