### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/continuous-aggregates/time/

### ISSUE THREAD

**Issue by eldercasey** [timescale/docs#2586]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

I found exactly what I wanted, and the instruction are clear, but they seem to be incorrect.

I am trying to create a continuous aggregation based on a hypertable with a bigint time dimension. The value is epoch time in milliseconds.

The first minor confusion was the example raw table has the following field and comment
  "time BIGINT,        -- Time in minutes since epoch"

epoch time is generally second or milliseconds since epoch time, so this example seems like it's already an aggregated time, but it's not really wrong, just odd.

Then the page correctly states that a continuous aggregate on a hypertable with a integer time dimension needs a custom time function. This is the issue that brought me to the page, looking to solve this error:

ERROR:  custom time function required on hypertable "mytable"
DETAIL:  An integer-based hypertable requires a custom time function to support continuous aggregates.
HINT:  Set a custom time function on the hypertable.

The issue here is that the suggested custom time function has incorrect syntax and cannot be created. I was able to hack it a bit (I think) with this:

CREATE FUNCTION current_epoch() RETURNS BIGINT AS $$
   SELECT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::bigint
$$ LANGUAGE SQL STABLE;

But my final issue is that I am still getting an error creating the continuous aggregation:

ERROR:  continuous aggregate view must include a valid time bucket function

The time_bucket function I am trying to use is:

time_bucket('60000', _timestamp) AS bucket -- _timestamp is millisecond since epoch time

I have also tried converting the bucket to TIMESTAMP in several different ways, but always get the same error when creating the continuous aggregate.

So here are the commands I'm running:

CREATE TABLE IF NOT EXISTS fa_networkquality
(
_timestamp                          bigint,
...

select create_hypertable('fa_networkquality', '_timestamp', chunk_time_interval => 86400000);

CREATE FUNCTION current_epoch() RETURNS BIGINT AS $$
   SELECT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::bigint
$$ LANGUAGE SQL STABLE;

SELECT set_integer_now_func('fa_networkquality', 'current_epoch');

CREATE MATERIALIZED VIEW fa_networkquality_hourly
WITH (timescaledb.continuous) AS
SELECT 
   time_bucket('60000', _timestamp) AS _timestamp,
...

And I get the this error every time

ERROR:  continuous aggregate view must include a valid time bucket function

I don't need immediate response (just doing preliminary investigation for continuous aggregations, and I'll probably sort it out tomorrow), but I do think someone should check the instruction on this page against a hypertable with integer time dimension.

Thank you,
Casey

**Comment by eldercasey** [comment]
I think I hit this issue: https://github.com/timescale/timescaledb/issues/5185 linked to this https://github.com/timescale/timescaledb/issues/5171#issuecomment-1384409336 and marked "not a bug".

My time in the raw data is '_timestamp' and I tried to use the same name in the aggregate so queries to the aggregate (just a time rollup) closely match queries to the raw data.

**Comment by Loquacity** [comment]
@jonatas Can you help with this one?
