### ISSUE TITLE
[Feedback] Debian 12 bookworm

### ISSUE THREAD

**Issue by pvergain** [timescale/docs#2599]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

When will the timescaledb extension be ready for the Debian 12 bookworm version ?

**Comment by Rajakavitha1** [comment]
Hi @pvergain . The Timescale development team is working on it. You may want to track this issue for updates: https://github.com/timescale/timescaledb/issues/5728

**Comment by Loquacity** [comment]
Debian 12 packages are available now. Reopening so we can update the docs.

**Comment by jflambert** [comment]
@Loquacity @svenklemm 
`timescaledb` is on bookworm, but not the standalone `timescaledb_toolkit` extension, which I need :(

**Comment by svenklemm** [comment]
toolkit packages for debian 12 amd64 are available now

**Comment by jflambert** [comment]
Great! Thanks!
