### ISSUE TITLE
Timescale 1.7.* documentation

### ISSUE THREAD

**Issue by amCap1712** [timescale/docs#26]
Hi! I am not sure this is the right place to ask, kindly forgive me and point me to the correct forum if it isn't. I am looking for Timescale 1.7.* docs but I only found v2.* documentation at https://docs.timescale.com/ .

**Comment by amCap1712** [comment]
My query was answered in the TImescaleDB Slack. The docs for older versions should be up in a few days on the new platform. Hence, closing.

**Comment by Loquacity** [comment]
Thanks for the report! For the benefit of anyone finding this later on, the 1.7 docs can be found at https://legacy-docs.timescale.com/v1.7/main
