### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/configuration/

### ISSUE THREAD

**Issue by Pk13055** [timescale/docs#2601]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

There are no instructions on this page.

**Comment by Loquacity** [comment]
Hi, thanks for the feedback. The page you're looking at is an index page, the instructions are nested underneath it. You can navigate to them using the left menu, or the prev/next buttons at the bottom of the page. The instructions you want are probably here: https://docs.timescale.com/use-timescale/latest/configuration/customize-configuration/
