### ISSUE TITLE
[Feedback] Upgrade guide doesn't mention template1

### ISSUE THREAD

**Issue by tkirill** [timescale/docs#2603]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Recently I did my first upgrade of my TimescaleDB instance. It went great, [corresponding guide](https://docs.timescale.com/self-hosted/latest/upgrades/upgrade-docker/) has clear instructions. However, the guide doesn't mention that I should update TimescaleDB extension in template1 database too or new databases will still be created with old version of TimescaleDB. Being new user to PostgreSQL I didn't knew that template1 even exists and it took a lot of time to understand what is happening.

Mentioning template1 database in upgrade guide may be helpful.

**Comment by Rajakavitha1** [comment]
Hi @tkirill Does this happen even when you connect using the X flag? " Connect to the upgraded instance using psql with the -X flag" . This prevents any .psqlrc commands from accidentally triggering the load of a previous TimescaleDB version on session startup. I recently tested the upgrade instructions for Docker and I did not encounter this issue. Closing this issue for now. Please feel free to reopen if any other issue needs to be fixed.
