### ISSUE TITLE
[Site Bug] Issue with the page: /tutorials/latest/financial-ingest-real-time/financial-ingest-query/

### ISSUE THREAD

**Issue by tomcyr** [timescale/docs#2604]
_Use this template for reporting bugs in the docs._

# Describe the bug

There is an error in the function for calculating day_volume - used LAST instead of SUM.

## What do the docs say now?

```
CREATE MATERIALIZED VIEW one_hour_candle
WITH (timescaledb.continuous) AS
    SELECT
        time_bucket('1 hour', time) AS bucket,
        symbol,
        FIRST(price, time) AS "open",
        MAX(price) AS high,
        MIN(price) AS low,
        LAST(price, time) AS "close",
        LAST(day_volume, time) AS day_volume
    FROM stocks_real_time
    GROUP BY bucket, symbol;
```

## What should the docs say?

```
CREATE MATERIALIZED VIEW one_hour_candle
WITH (timescaledb.continuous) AS
    SELECT
        time_bucket('1 hour', time) AS bucket,
        symbol,
        FIRST(price, time) AS "open",
        MAX(price) AS high,
        MIN(price) AS low,
        LAST(price, time) AS "close",
        SUM(day_volume) AS day_volume
    FROM stocks_real_time
    GROUP BY bucket, symbol;
```

# Page affected

[https://docs.timescale.com/tutorials/latest/financial-ingest-real-time/financial-ingest-query/]

# Subject matter expert (SME)

# Screenshots

# Any further info

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Rajakavitha1** [comment]
Hi @tomcyr The function that is used in LAST is a Timescale hyperfunction and it is an aggregate. Please see https://docs.timescale.com/api/latest/hyperfunctions/last/ for more information. Closing this issue for now. Please feel free to reopen if any other changes needs to be made.
