### ISSUE TITLE
[Site Bug] Issue with the page: /use-timescale/latest/continuous-aggregates/create-a-continuous-aggregate/

### ISSUE THREAD

**Issue by frakhlystov** [timescale/docs#2611]
[Using the WITH NO DATA option](https://docs.timescale.com/use-timescale/latest/continuous-aggregates/create-a-continuous-aggregate/#using-the-with-no-data-option)
By default, when you create a view for the first time, it is populated with data. This is so that the aggregates can be computed across the entire hypertable. If you don't want this to happen, for example if the table is very large, or if new data is being continuously added, you can control the order in which the data is refreshed. You can do this by adding a manual refresh with your continuous aggregate policy using the WITH NO DATA option.

This is wrong if I create mat view with NO DATA policy it still aggregates all the historical data!

**Comment by Loquacity** [comment]
@jonatas Are you able to comment here?

**Comment by Rajakavitha1** [comment]
Hi @frakhlystov does it happen even after you manually refresh the history? ``` If you have historical data that is older than the start_offset interval, you need to manually refresh the history up to the current start_offset to allow real-time queries to run efficiently.```

**Comment by jonatas** [comment]
> This is wrong if I create mat view with NO DATA policy it still aggregates all the historical data!

@frakhlystov, thanks for reporting, can you share a minimal reproducible example with us?

If a cagg creation with data even if you specify `WITH NO DATA` we have a bug in the extension. Please, share more details about what versions of PG and the version of timescaledb extension you have.

 Feel free to create an issue in the official timescaledb extension repository or we can transfer it later.
