### ISSUE TITLE
[Site Bug] Issue with the page: /use-timescale/latest/regions/ - only AWS listed

### ISSUE THREAD

**Issue by Greg-Smulko** [timescale/docs#2623]
# Describe the bug

Based on https://docs.timescale.com/use-timescale/latest/regions/, it looks like only AWS is supported.

This is in odds with other pages that suggest that also Google Cloud and Azure are supported (e.g. https://docs.timescale.com/mst/latest/installation-mst/#create-your-first-service)

## What do the docs say now?

Only AWS, see above.

## What should the docs say?

List also GCP and Azure, as I assume they're supported?

# Page affected

https://docs.timescale.com/use-timescale/latest/regions/

# Subject matter expert (SME)

?

# Screenshots

![image](https://github.com/timescale/docs/assets/26791344/31b5167c-b7d0-4a7c-ba9b-278c548f179d)

![image](https://github.com/timescale/docs/assets/26791344/530e3eb1-97b1-4a9c-b23d-af3fdab28ac0)

# Any further info

n/a

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by Loquacity** [comment]
Hi there, the screenshot you've shown is for Managed Service for TimescaleDB, whereas the page you're looking at showing only AWS is referring to our flagship product.
