### ISSUE TITLE
[Feedback] Page: /tutorials/latest/blockchain-analyze/analyze-blockchain-query/

### ISSUE THREAD

**Issue by wotuzu17** [timescale/docs#2624]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

I am exploring timescaledb by trying to reproduce the tutorials on my local installation on Ubuntu 22.04.

psql (15.4 (Ubuntu 15.4-1.pgdg22.04+1), server 14.9 (Ubuntu 14.9-1.pgdg22.04+1))

Instructions are very clear, but on my installation none of the views on can be created due to the stats_agg clause (a error is thrown: function stats_agg does not exists. It works when the stats_agg line is commented out. 

Is it just me/my installation?

**Comment by Loquacity** [comment]
Hi @wotuzu17 Thanks for the feedback on the tutorials! stats_agg is a Toolkit function. If you're using Timescale, then it's included by default, but if you're self-hosting, you'll need to install the Toolkit package to get access to the function: https://docs.timescale.com/self-hosted/latest/tooling/install-toolkit/
