### ISSUE TITLE
[Content Bug] Update or delete of compressed data only works for PG14 or later

### ISSUE THREAD

**Issue by mkindahl** [timescale/docs#2639]
# Describe the bug

Documentation states that any 2.11 and later is able to handle delete and update, but it requires PG14 or later to be able to delete or update rows in compressed tables.

## What do the docs say now?

> In TimescaleDB 2.11 and later, you can insert data into compressed chunks. This works even if the data you are inserting has unique constraints, and those constraints are preserved during the insert operation. This is done by using a PostgreSQL function that decompresses relevant data during the insert to check if the new data breaks unique checks. This means that any time you insert data into a compressed chunk, a small amount of data is decompressed to allow a speculative insertion, and block any inserts which could violate constraints.

## What should the docs say?

> For TimescaleDB 2.11 and later, you can insert data into compressed chunks on PostgreSQL 14 or later. This works even if the data you are inserting has unique constraints, and those constraints are preserved during the insert operation. This is done by using a PostgreSQL function that decompresses relevant data during the insert to check if the new data breaks unique checks. This means that any time you insert data into a compressed chunk, a small amount of data is decompressed to allow a speculative insertion, and block any inserts which could violate constraints.
> Note that it is not possible to update or delete data if you are using PG13 or earlier.

# Page affected

https://docs.timescale.com/use-timescale/latest/compression/modify-compressed-data/

**Comment by aarondglover** [comment]
it should be more prominent than suggested change.

**Comment by Rajakavitha1** [comment]
Addressed in https://github.com/timescale/docs/pull/2638
