### ISSUE TITLE
How to download community edition

### ISSUE THREAD

**Issue by vanimesh** [timescale/docs#2642]
Hi team,

How can i download the community edition of timescale?

**Comment by Rajakavitha1** [comment]
Hi @vanimesh Please check out these instructions: https://docs-dev.timescale.com/docs-space-dimensions-rajie/self-hosted/space-dimensions-rajie/install/

**Comment by vanimesh** [comment]
Thank you @Rajakavitha1 , but how can i download RPMs ?  We dont have internet connectivity from our boxes.

**Comment by Loquacity** [comment]
You can also install from source, if that helps: https://docs.timescale.com/self-hosted/latest/install/installation-source/
