### ISSUE TITLE
Where can i find RHEL and timescale compatability martix

### ISSUE THREAD

**Issue by vanimesh** [timescale/docs#2643]
Where can i find RHEL version and timescale versions compatability martix?

**Comment by Rajakavitha1** [comment]
Hi @vanimesh  you might want checkout https://docs.timescale.com/self-hosted/latest/upgrades/upgrade-pg/ that list the PostgreSQL and TimescaleDB compatibility matrix. You can find the PostgreSQL and RHEL compatibility matrix here: https://www.postgresql.org/download/linux/redhat/

**Comment by vanimesh** [comment]
Thank you @Rajakavitha1 . May I know the answer for my previous ask?

**Comment by Loquacity** [comment]
Hi @vanimesh This repo is used to track docs issues. For help, check out our [Community](https://www.timescale.com/community/) instead. If you discover that we need to do a docs update, you can open an issue with the details, or use the `:docs-update-needed:` reactji in Slack.
