### ISSUE TITLE
[Site Bug] Issue with the page: /api/latest/hypertable/create_hypertable/

### ISSUE THREAD

**Issue by caiski** [timescale/docs#266]
_Use this template for reporting bugs in the docs._

# Describe the bug

[Provide as much detail as you can]

## What do the docs say now?
It says how to create hypertable with supported column types.

## What should the docs say?

It did not say how to find the partition column after the hypertable is created. Since when it's difficult to recall what column was used to create hypertable, we should be able to check the hypertable definition afterwards.

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/create/

# Version affected

# Subject matter expert (SME)

# Screenshots

# Any further info

**Comment by Loquacity** [comment]
After some research, the answer here seems to be to use the general PostgreSQL commands `\d` and \`d+`. You could also use `\s` to see your command history. I don't think there's anything for us to document here.
