### ISSUE TITLE
[Feedback] Page: /getting-started/latest/queries/

### ISSUE THREAD

**Issue by hydrohiester** [timescale/docs#2679]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

The queries don't work (?)

**Comment by Loquacity** [comment]
We're looking into this now, thanks for the feedback!

**Comment by Rajakavitha1** [comment]
Hi @hydrohiester . This has now been addressed. Closing this issue for now please feel free to reopen if any other issue needs to be addressed.
<img width="484" alt="Screenshot 2023-09-13 at 8 37 51 AM" src="https://github.com/timescale/docs/assets/37059749/13727769-41a1-4bc6-a3a1-e334de7599f6">
