### ISSUE TITLE
[Docs RFC] Document compression params

### ISSUE THREAD

**Issue by jonatas** [timescale/docs#2685]
# Document compression configuration settings

Some community member come up with the following comment:

> We've been running into memory issues with our Postgres connections (managed by the Elixir "Ecto" library). We're opening connections in a pool and keeping them open. The connections seem to be using more and more memory and not releasing it (or not releasing it aggressively enough), and our instance is running out of memory.
It's easy to make this happen when we test our migration of data from the old platform into Timescale. While my DBA thinks we should cycle our connections every X minutes (i.e. close and reopen them), that seems like a fragile approach to me, and I'd prefer to not. After suggesting it might be related to the number of chunks Timescale is holding in memory, my DBA found `timescaledb.max_open_chunks_per_insert` and `timescaledb.max_cached_chunks_per_hypertable` and those seemed to help—but we also couldn't find any documentation for them, so this seems super sketchy!

# Subject matter expert (SME)

@RafiaSabih or @fabriziomello can help us with the details here.

**Comment by jamessewell** [comment]
[Ecto has a disconnect_all setting ](https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.html#disconnect_all/3)to manage this in a nice way.

My understanding is that you schedule the call and then after a randomised time per connection it will reconnect (unless it's doing work, which which case after the transaction completes). 

Having massively long running connections is an anti-pattern (although point taken on the growing memory, we still investigate) and I think for you this is a great solution.
