### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/schema-management/about-indexing/

### ISSUE THREAD

**Issue by jackRoark** [timescale/docs#2694]
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

Following the instructions on this page helped me reduce the times on my queries from about 2 minutes down to less than 1 second!

**Comment by jamessewell** [comment]
This is great to hear! Thanks for the feedback Jack (and feel free to come and chat about it in Slack if you'd like ❤️)
