### ISSUE TITLE
[Site Bug] Issue with the page: /self-hosted/latest/install/installation-linux/

### ISSUE THREAD

**Issue by chenwang07** [timescale/docs#2695]
_Use this template for reporting bugs in the docs._

# Describe the bug

[Provide as much detail as you can]

## What do the docs say now?

Followed the instruction:
[Installing self-hosted TimescaleDB on Red Hat-based systems](https://docs.timescale.com/self-hosted/latest/install/installation-linux/#installing-self-hosted-timescaledb-on-red-hat-based-systems)

And at step 3, **update your local repository list**:
_yum update_

Shows the error:

Errors during downloading metadata for repository 'pgdg-common':
  - Status code: 404 for https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-3-x86_64/repodata/repomd.xml (IP: 147.75.85.69)
Error: Failed to download metadata for repo 'pgdg-common': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

try clean cache:
 _dnf clean all_
but didn't help

## What should the docs say?

# Page affected

https://docs.timescale.com/self-hosted/latest/install/installation-linux/#installing-self-hosted-timescaledb-on-red-hat-based-systems

**Comment by jamessewell** [comment]
Wow, you're using [Redhat 3](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#RHEL_3)!

This was released 20 (!!!!) years ago and came out of Redhat extended support in 2014. 

I'm sorry to say, but we can't support this 😅

What you can do is compile your own [version](https://docs.timescale.com/self-hosted/latest/install/installation-source/), although I do wonder if you'll have issues getting recent versions of the build toolchain as well.

If you'd like some more support feel free to come to our [Slack](https://slack.timescale.com/) channel.
