### ISSUE TITLE
[Content Bug] pg_dump and pg_restore page 404

### ISSUE THREAD

**Issue by irWME** [timescale/docs#2706]
_Use this template for reporting bugs in the docs._

# pg_dump and pg_restore page 404?
last week, this page https://docs.timescale.com/use-timescale/latest/migration/pg-dump-and-restore/ was working, nicely explaining how to do an online backup using pg_dump. Now it isnt anymore, 404! Does this mean that pg_dump is not supported anymore? 

## What do the docs say now?
404

## What should the docs say?
Something like this but for the latest version: https://legacy-docs.timescale.com/v1.7/using-timescaledb/backup

# Page affected

https://docs.timescale.com/use-timescale/latest/migration/pg-dump-and-restore/ 

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

![image](https://github.com/timescale/docs/assets/1053085/6c0a25eb-5c4b-4d00-ad70-ccb1b13cf6f6)

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by JamesGuthrie** [comment]
Hi @irWME thanks for opening this issue. I am the one responsible for making this page disappear. The motivation behind it disappearing is that we reworked the migration content significantly (and moved it to its own top-level section: https://docs.timescale.com/migrate/latest/). That page didn't belong with the new migration content, so it was removed.

I believe that the following page contains the same information as the now missing page: https://docs.timescale.com/self-hosted/latest/migration/entire-database/.

In general if you're using Timescale (our cloud offering), you don't need to worry about making manual backups as the platform handles this for you automatically.

If you're running TimescaleDB yourself, and looking for a backup solution, then maybe this page will be more useful: https://docs.timescale.com/self-hosted/latest/backup-and-restore/. pg_dump and pg_restore are not true backup solutions, instead you would probably want to use a tool like [pgbackrest](https://pgbackrest.org/).

**Comment by irWME** [comment]
Hi,

Ok clear, thanks. We are using it self-hosted and and we do have
host machine volume snapshots, but we also want some extra per db backups
by using pg_dump. Should I use pgbackrest instead?

Op di 26 sep 2023 om 13:15 schreef James Guthrie ***@***.***>:

**Comment by JamesGuthrie** [comment]
In general it depends on what you wish to achieve with your backup solution. The solution which gives you the most safety is a combination of basebackups and WAL archiving for point-in-time restore. pgbackrest supports this (and other) setups, and is well documented.
