### ISSUE TITLE
[Site Bug] Issue with the page: /self-hosted/latest/install/installation-docker/

### ISSUE THREAD

**Issue by qrlt** [timescale/docs#2735]
In the documentation regarding usage of volumes, the data mount point, `/home/postgres/pgdata/data` is incorrect.

The whole code example on the page:
```
docker run -d --name timescaledb -p 5432:5432 \
-v /your/data/dir:/home/postgres/pgdata/data \
-e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg14-latest
```

When trying out the image `image: timescale/timescaledb:latest-pg14`, the correct mount point would be `/home/postgres/pgdata/data`.

**Comment by youyi218** [comment]
I believe the mount point is different for `timescaldb-ha` and `timescaledb`, noticing that on the code example the image is `timescaledb-ha` and you are using `timescaledb`, and for my experience the mount point should be at `/var/lib/postgresql/data` for image `timescaledb`

**Comment by paavohuhtala** [comment]
I ran into the same issue with a self-hosted database for sensor data from Home Assistant.
