### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/backup-restore-cloud/

### ISSUE THREAD

**Issue by mnbf9rca** [timescale/docs#2736]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

tell me how to manage backups on timescale self hosted...

**Comment by JamesGuthrie** [comment]
@mnbf9rca The page you're looking for is here: https://docs.timescale.com/self-hosted/latest/backup-and-restore/

**Comment by mnbf9rca** [comment]
I mean, not really though? Nothing like the scale of documentation about migrating, which is basically the same thing. Why not just refer people to that?

**Comment by JamesGuthrie** [comment]
Migration is not the same thing as backup/restore, so I don't think that it would be correct to point users to migration documentation for backup/restore.

**Comment by mnbf9rca** [comment]
But the steps - how to execute a backup, how to prepare for recovery in case of disaster and the need to rebuild a new instance etc are basically the same, aren’t they? It’s just up to the reader to schedule the backups.

**Comment by JamesGuthrie** [comment]
No, they're not the same. It's important to clarify here that using `pg_dump` and `pg_restore` is not really a backup solution. You're right that if your backup solution would be solely based on pg_dump/pg_restore, the steps would be similar to the migration steps.

A proper backup solution would use Postgres' basebackup and wal replay facilities. The best approach would be to use either [barman](https://pgbarman.org/) or [pgbackrest](https://pgbackrest.org/).

**Comment by mnbf9rca** [comment]
Thanks for clarifying. Pgbackuprest is quite complex - but barman looks viable.
