### ISSUE TITLE
[Site Bug] Issue with the page: /self-hosted/latest/configuration/about-configuration/

### ISSUE THREAD

**Issue by abeep** [timescale/docs#2745]
_Use this template for reporting bugs in the docs._

# Describe the bug

[Provide as much detail as you can]

## What should the docs say?

# Page affected

[Provide the URL to the page you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by jamessewell** [comment]
@abeep I'm closing this one as I can't see any obvious issues, feel free to re-open if you have more details though 😀
