### ISSUE TITLE
[Content Bug]: Connection pooling code block

### ISSUE THREAD

**Issue by solugebefola** [timescale/docs#2750]
_Use this template for reporting bugs in the docs._

# Describe the bug

The code block doesn't contain all of the code in step 4 of the connection pooling docs

## What should the docs say?

# Page affected

https://docs.timescale.com/use-timescale/latest/services/connection-pooling/

# Subject matter expert (SME)

@ggodeke 

# Screenshots

![image](https://github.com/timescale/docs/assets/12288273/2db8b1a6-2192-4c0f-ad85-db448b868d1d)

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by jamessewell** [comment]
This looks like it's been fixed 😀
