### ISSUE TITLE
[Site Bug] Can't use any keyboard keys to scroll pages

### ISSUE THREAD

**Issue by JonathanLydall** [timescale/docs#3027]
I'm using the latest Microsoft Edge on Windows 11 and no default browser keyboard shortcut keys for scrolling seem to work, for example all of the following:

- Up key
- Down key
- Space bar
- Page up
- Page down

Although my mouse wheel works fine, the lack of typical keyboard shortcuts makes for an immediately frustrating experience when using your docs.

I expect all Chromium browsers would have the same issue.

**Comment by billy-the-fish** [comment]
@shahriarpshuvo, this is also true for Firefox.

**Comment by shahriarpshuvo** [comment]
This issue has been fixed now.
Thank you for reporting.
