### ISSUE TITLE
Failing link check 

### ISSUE THREAD

**Issue by billy-the-fish** [timescale/docs#3098]
In https://docs.timescale.com/api/latest/, the links in the Hyperfunctions: gapfilling section are not working. However, in https://docs.timescale.com/api/latest/hyperfunctions/gapfilling/time_bucket_gapfill/, the links in [Functions in this group](https://docs.timescale.com/api/latest/hyperfunctions/gapfilling/time_bucket_gapfill/#functions-in-this-group), generated from the same source files are correct. This is true for all links that use   `bucket_function: time_bucket_gapfill()`.

The source file for these links is in https://github.com/timescale/docs/tree/latest/api/_hyperfunctions/time_bucket_gapfill.

**Comment by billy-the-fish** [comment]
@shahriarpshuvo is there any chance you could have a quick look at this. I can't see why these links are incorrectly generated on the landing page.

**Comment by shahriarpshuvo** [comment]
This issue has been resolved.
