### ISSUE TITLE
[Bug/Typo] The :pg_version: entity is not expanding in Installation sections (was: Windows exe link broken)

### ISSUE THREAD

**Issue by pfried** [timescale/docs#31]
**Add the appropriate label(s) -->**

**Describe the bug**

The Link for downloading the windows version of timescale does not work, the variable substitution seems broken:

`https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-:pg_version:_x.y.z-windows-amd64.zip`

**Location**

https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/windows/installation-windows/

**Screenshots**

**Device and browser**
Desktop

**Comment by Loquacity** [comment]
Thanks for reporting this. I'm having trouble reproducing the issue, the link looks fine to me on my browser. We just refreshed the docs, perhaps there's a caching issue? Can you take another look for me please?

![image](https://user-images.githubusercontent.com/3914967/117223397-e2c35180-ae50-11eb-801b-48b71085da1b.png)

**Comment by pfried** [comment]
![image](https://user-images.githubusercontent.com/1744875/117244302-17c3aa00-ae39-11eb-81c5-41fcc5fbe4b3.png)

yes the issue is gone, but you still seem to have problems with interpolation of placeholders, see marking in your screenshot (same for my view)

**Comment by Loquacity** [comment]
You are absolutely correct, the `:pg_version:` entity looks broken throughout. Thanks!
