### ISSUE TITLE
[Docs RFC] Forge maintenance window docs

### ISSUE THREAD

**Issue by clarkbw** [timescale/docs#311]
# Describe change in content, appearance, or functionality

There doesn't seem to be any docs related to managing maintenance windows, the feature can be seen at URLs looking like this: `https://console.forge.timescale.com/dashboard/services/SERVICE_ID/operations/maintenance`.

- Default maintenance window
  - Zero downtime minor version upgrades will reset connections
  - How to change your maintenance window
- Upcoming scheduled maintenance

I'm not sure yet where this goes in the sidebar. I guess Cloud has a Maintenance section of its own at the bottom so that might be the right case here. 

The specific impetus for opening this issue is that the new zero downtime minor version upgrades will have no downtime affect however it will end up reseting database connections. If a system was performing a long running query that query could be interrupted. As well if the connecting application didn't automatically retry connections there will be issues, however almost every application knows to automatically retry the database connection.

# Subject matter expert (SME)

@clarkbw 

# Deadline

With our zero downtime project rolling out next week, this would be good to have documented soon but does not have to make it next week. Apologies for not having this filed already.

**Comment by Loquacity** [comment]
Base this content on the Cloud/MST content here: https://docs.timescale.com/timescale-cloud/latest/maintenance/

**Comment by Loquacity** [comment]
Also include this: https://github.com/timescale/docs/issues/331
