### ISSUE TITLE
[Content Bug] Download link is outdated

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#316]
# Describe the bug

The download links on https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/windows/installation-windows/#installation-windows are still pointing to 2.3.0

## What should the docs say?

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/windows/installation-windows/

# Version affected

Current

# Subject matter expert (SME)

@svenklemm 

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
@svenklemm What is the correct download link, so I can update?

**Comment by svenklemm** [comment]
https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-12_2.4.1-windows-amd64.zip
https://timescalereleases.blob.core.windows.net/windows/timescaledb-postgresql-13_2.4.1-windows-amd64.zip

**Comment by Loquacity** [comment]
@jacobprall Sven tells me this used to be automated somehow? Can you look into that for me when you're back? In the meantime, I'll update these manually.
