### ISSUE TITLE
[Content Bug]

### ISSUE THREAD

**Issue by basaran** [timescale/docs#3195]
_Use this template for reporting bugs in the docs._

# Describe the bug
https://tsdb.co/GitHubTimescalePostgresMigrate redirecting to wrong URL.

https://docs.timescale.com/use-timescale/latest/migration/ is 404

## What do the docs say now?
https://tsdb.co/GitHubTimescalePostgresMigrate

## What should the docs say?
https://tsdb.co/GitHubTimescalePostgresMigrate should _probably_ redirect to https://docs.timescale.com/migrate/latest/.

# Page affected

README.md

**Comment by billy-the-fish** [comment]
Hi @basaran, thanks for the heads up, really appreciate it. We have fixed the link: https://github.com/timescale/timescaledb.
