### ISSUE TITLE
[Docs RFC] Point to the docs in the Promscale repo for additional information

### ISSUE THREAD

**Issue by ramonguiu** [timescale/docs#324]
# Describe change in content, appearance, or functionality

I would add a link to the docs in the Github repo for Promscale in the Promscale page in the docs. I would make it highly visible. The documentation we have at the moment is minimal and users would be confused and wondering were to get additional information. If the are willing to make the effort, they may join our Slack community but not providing clear instructions on where to find additional docs adds friction to the initial onboarding for new users.

# Subject matter expert (SME)

NA

# Deadline

No hard deadline, but users going to docs for Promscale may be a bit lost.

# Any further info

NA

**Comment by Loquacity** [comment]
This is addressed in https://github.com/timescale/docs/pull/82 which has merged, but is not yet visible, because we're waiting on some backend stuff.
