### ISSUE TITLE
[Docs RFC] Update the readme in the TimescaleDB github repo to match the pgai docs

### ISSUE THREAD

**Issue by billy-the-fish** [timescale/docs#3269]
Update https://github.com/timescale/timescaledb to match https://github.com/timescale/pgai

**Comment by iroussos** [comment]
@billy-the-fish just discussed about this with Philip on the database offsite - on top of approaching the readme in a better way, we have a few dead links as well in there. Let's think how we can move this effort forward

**Comment by billy-the-fish** [comment]
Let's use https://github.com/timescale/pgai/blob/main/README.md as a template and update.
