### ISSUE TITLE
Renaming of services is functional

### ISSUE THREAD

**Issue by Nelate** [timescale/docs#3281]
The docs state that the renaming of services is not possible yet it is currently working. The section which is marked as important may need to be reviewed. Crosscheck https://docs-dev.timescale.com/docs-216-docs-rfcupdate-existing-mst-docs-with-links-to-connect-to-mst-console/mst/216-docs-rfcupdate-existing-mst-docs-with-links-to-connect-to-mst-console/about-mst/#projects

**Comment by billy-the-fish** [comment]
Hi there Nelson,  thanks for going over this doc. I can see how to change the project name in MTS, but not the service name. Could you tell me how this is done please. Thanks in advance, Iain.
