### ISSUE TITLE
Entire Install TimescaleDB Section is broken on all browsers

### ISSUE THREAD

**Issue by elucidsoft** [timescale/docs#3377]
_Use this template for reporting bugs in the docs._

# Describe the bug

When you goto any of the pages under the Install TimescaleDB section it briefly flashes the content and then just shows a white screen. I tried it on Firefox, Edge, Chrome, InPrivate, etc.  

## What do the docs say now?

(blank screen)

## What should the docs say?

The stuff

# Page affected

https://docs.timescale.com/self-hosted/latest/install/installation-linux/
https://docs.timescale.com/self-hosted/latest/install/installation-macos/
https://docs.timescale.com/self-hosted/latest/install/installation-source/

[Provide the URL to the page you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by billy-the-fish** [comment]
Hi @elucidsoft , thanks for the heads up. We have updated the site and these pages should render correctly now. Cheers, Iain.
