### ISSUE TITLE
[Docs RFC] Clean up the redirects. 

### ISSUE THREAD

**Issue by billy-the-fish** [timescale/docs#3407]
There are a billion and one redirects in https://github.com/timescale/docs/blob/latest/.data/redirects.js. Please remove redirects to non-existent pages,  redirects to redirects, redirects that do not work. I don't think there is a way to see which ones are not used externally. Maybe ask @robsoncoelho if there is a tool to test the redirects. 

To make it more fun, there is also https://github.com/timescale/web-documentation/blob/production-v3/lambda/redirects.js. Not sure if these redirects are live. Once again, Robson will know.

**Comment by robsoncoelho** [comment]
hey there,

Unfortunately it's hard to know which redirects are not used externally, I believe the best approach is just remove redirects to non-existent pages, redirects to redirects and redirects that do not work, like @billy-the-fish mentioned above.

As you mentioned, there are two redirects.js files, but only the second link is being used AFAIK https://github.com/timescale/web-documentation/blob/production-v3/lambda/redirects.js. 

We had all redirects implemented via Cloudflare dashboard, but we decided to move it to Lambda function to make it easy to maintain, just updating the `redirects.js` file.

Regarding the first redirects.js link you shared above, I believe that no changes there persists in prod (outdated file)

**Comment by atovpeko** [comment]
@robsoncoelho can we get rid of the obsolete file? Will definitely lead to a lot of confusion, having the two of them at the same time.

**Comment by robsoncoelho** [comment]
We definitely do. I didn't even know this file existed :)

All Docs redirects need to be applied using this one https://github.com/timescale/web-documentation/blob/production-v3/lambda/redirects.js.

**Comment by atovpeko** [comment]
https://docs.google.com/spreadsheets/d/1u7vwf5kAtP3wBb6HZ5mM1fF65Wmp2EEj0KbgMDiXaWc/edit?gid=531793436#gid=531793436
