### ISSUE TITLE
[Site Bug] Issue with the page: /self-hosted/latest/install/installation-linux/

### ISSUE THREAD

**Issue by Chentesitoz** [timescale/docs#3415]
_Use this template for reporting bugs in the docs._

# Describe the bug

https://packagecloud.io/timescale/timescaledb/debian jammy Release
  404  Not Found [IP: 52.8.136.162 443]

## What should the docs say?

# Page affected

https://docs.timescale.com/self-hosted/latest/install/installation-linux/

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by billy-the-fish** [comment]
Hi @Chentesitoz , thanks for signalling this issue.  I've done a bit of research and found out that Jammy is a Ubuntu release. To add the timescaleDB package to your sources.list for Ubuntu you need to run:

`echo "deb https://packagecloud.io/timescale/timescaledb/ubuntu/ $(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/timescaledb.list`


To add the package for a Debian installation, run:

`echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/timescaledb.list`
