### ISSUE TITLE
[Site Bug] Issue with the page: /self-hosted/latest/install/installation-linux/

### ISSUE THREAD

**Issue by NateFreyBDI** [timescale/docs#3426]
_Use this template for reporting bugs in the docs._

# Describe the bug

Step by step instructions for PostgreSQL installation have disappeared since earlier this week.  Now says Job jobbed at the end.

## What do the docs say now?
![image](https://github.com/user-attachments/assets/67d2314d-7341-4a0c-980b-396f51656d27)
## What should the docs say?
Docs should give some copy and paste commands for setting up postgresql
# Page affected
[affected page](https://docs.timescale.com/self-hosted/latest/install/installation-linux/)

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

![image](https://github.com/user-attachments/assets/67d2314d-7341-4a0c-980b-396f51656d27)

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by NateFreyBDI** [comment]
This is showing up on Edge browser as a problem.  Chrome looks correct.

**Comment by robsoncoelho** [comment]
@NateFreyBDI, can you tell us which version of Edge you are testing? Also, is this happening when accessing it with an anonymous tab?
