### ISSUE TITLE
[Feedback] Page: /use-timescale/latest/backup-restore/point-in-time-recovery/

### ISSUE THREAD

**Issue by basFriday** [timescale/docs#3458]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

Why only restore to the last 3 days?
that doesn't make sense at all!
especially if you guys have the backups.
what if I want to restore point in time 4 days ago? or 2 months ago?
so confused, you guys manage it, so manage more than 3 days of backups ....

**Comment by billy-the-fish** [comment]
Update https://docs.timescale.com/use-timescale/latest/backup-restore/ to say that PITR depends on the pricing plan: https://docs.timescale.com/about/latest/pricing-and-account-management/, Scale and Enterprise offer 14 day recovery.
