### ISSUE TITLE
[Feedback] Page: /getting-started/latest/services/

### ISSUE THREAD

**Issue by SpikedPunchVictim** [timescale/docs#3463]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Hardly anything is explained here. Not sure What these functions are doing. Are they creating another table? If so, where? How does it relate to the table we created before this? So many questions.

**Comment by billy-the-fish** [comment]
Hi there @SpikedPunchVictim, can you have a look at https://docs-dev.timescale.com/docs-3463-feedback-page-getting-startedlatestservices/getting-started/3463-feedback-page-getting-startedlatestservices/services/ and tell me if these updates make things a big clearer. Please add any comments in https://github.com/timescale/docs/pull/3490.
