### ISSUE TITLE
[Content Bug] Create Hypertable on timestamp (non-tz column). Supported?

### ISSUE THREAD

**Issue by swiffer** [timescale/docs#3482]
_Use this template for reporting bugs in the docs._

# Describe the bug

Is partitioning by timestamp supported?

## What do the docs say now?

timestamp is supported / not supported. Depends on where you are looking at?

_not supported_
https://docs.timescale.com/use-timescale/latest/hypertables/create/#create-a-hypertable

`This can be a timestamptz, date, or integer. Ensure that you set the datatype for the time column as timestamptz and not timestamp.`

_supported_
https://docs.timescale.com/api/latest/hypertable/dimension_info/#notes

## What should the docs say?

consistent guidenance on what column types are supported.

# Page affected
https://docs.timescale.com/use-timescale/latest/hypertables/create/#create-a-hypertable
https://docs.timescale.com/api/latest/hypertable/dimension_info/#notes

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by swiffer** [comment]
Thanks for calrifying that!

**Comment by atovpeko** [comment]
@swiffer thank you for reporting :-)
