### ISSUE TITLE
[Content Bug] Limitation Foreign Key to Hypertable still existing?

### ISSUE THREAD

**Issue by swiffer** [timescale/docs#3483]
_Use this template for reporting bugs in the docs._

# Describe the bug

Are Foreign Keys to Hypertables supported?

## What do the docs say now?

https://docs.timescale.com/use-timescale/latest/limitations/

The Docs mention the Limitation: `Foreign key constraints referencing a hypertable are not supported.`

## What should the docs say?

According to Release Notes of 2.16.0 this is supported now?

# Page affected

https://docs.timescale.com/use-timescale/latest/limitations/

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

## Contributing to documentation

We welcome documentation contributions!

*   For information about how to propose a change, see the [contributing guide](https://github.com/timescale/docs/blob/latest/CONTRIBUTING.md) in our GitHub repository.
*   For information on style and word usage, see the [style guide](https://docs.timescale.com/about/latest/contribute-to-docs)

**Comment by atovpeko** [comment]
@iroussos I will remove this limitation from the doc, correct?

**Comment by iroussos** [comment]
> @iroussos I will remove this limitation from the doc, correct?

Thank you @swiffer for reporting. Yes, @atovpeko let's remove this (and any similar references that remain) from the docs. Referencing a hypertable from a regular table is supported in 2.16 and we somehow missed to update this page

We should move at the end of the list and change the wording:

```diff
-* Foreign key constraints referencing a hypertable are not supported.
( .. other restrictions ..)
+* Foreign key constraints from a hypertable referencing another hypertable are not supported.
```
