### ISSUE TITLE
`apt-key` deprecation

### ISSUE THREAD

**Issue by feikesteenbergen** [timescale/docs#350]
# Describe change in content, appearance, or functionality

`apt-key` is to be deprecated in future Ubuntu/Debian releases.

I ran into this trying to give Ubuntu 21.10 a run, which failed.

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/ubuntu/installation-apt-ubuntu/

For example needs to have this changed at least:

```diff
- echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -c -s)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
- wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  sudo apt-get update
+ echo "deb [signed-by=/usr/share/keyrings/postgresql.keyring] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -c -s)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
+ wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc |  gpg --dearmor > /usr/share/keyrings/postgresql.keyring
  sudo apt-get update
```

> Use of apt-key is deprecated, except for the use of apt-key del in maintainer scripts to remove existing keys from the main keyring. 

https://manpages.debian.org/unstable/apt/apt-key.8.en.html

**Comment by camscale** [comment]
I've fixed one of the paths in the description: /usr/share/keyring -> /usr/share/keyrings (mentioning in case it has been copied somewhere else already).

But I would suggest for locally installed keyrings for apt, they should probably not go into `/usr/share/keyrings` - that directory is "owned" by the system and may clash with something installed from a package. Locally added stuff should either go into /usr/local/share/keyrings (does not exist by default), or somewhere in /etc. I was going to suggest /etc/apt/trusted.gpg.d as that is where keyrings are placed now, but I'm not sure if that perpetuates the security issue that deprecated apt-key in the first place.

I'm still trying to find definitive info on the deprecation of apt-key.

**Comment by camscale** [comment]
This message: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990521#37 suggests /usr/local/share/keyrings - I think this is better than /etc/apt/trusted.gpg.d

**Comment by Loquacity** [comment]
Reopening so we can apply the same edits to the Debian install instructions, as per https://github.com/timescale/docs/pull/359#pullrequestreview-751299982
