### ISSUE TITLE
[Docs RFC] Reorg tiering policy sections into Manage tiering

### ISSUE THREAD

**Issue by gayyappan** [timescale/docs#3508]
Ticket for following up on this one:

> How about we combine https://docs-dev.timescale.com/docs-upd2/use-timescale/upd2/data-tiering/enabling-data-tiering/, https://docs-dev.timescale.com/docs-upd2/use-timescale/upd2/data-tiering/creating-data-tiering-policy/ and this doc into one page called Manage data tiering or some such like?

`
https://github.com/timescale/docs/pull/3496#issuecomment-2405058858

**Comment by atovpeko** [comment]
@gayyappan I would suggest also adding the following to this page, for a more comprehensive doc: 

- https://docs.timescale.com/use-timescale/latest/data-tiering/manual-tier-chunk/
- https://docs.timescale.com/use-timescale/latest/data-tiering/untier-data/ and 
- https://docs.timescale.com/use-timescale/latest/data-tiering/disabling-data-tiering/

Does this work?

**Comment by billy-the-fish** [comment]
Love it, let's turn this into a workflow.
