### ISSUE TITLE
[Docs RFC] Add documentation about using MERGE for Continuous Aggregate refresh

### ISSUE THREAD

**Issue by billy-the-fish** [timescale/docs#3513]
Maybe a note in https://docs.timescale.com/api/latest/continuous-aggregates/refresh_continuous_aggregate/. Don't think we need anything in https://docs.timescale.com/api/latest/continuous-aggregates/refresh_continuous_aggregate/.

@fabriziomello , what do you think?

**Comment by fabriziomello** [comment]
> Maybe a note in https://docs.timescale.com/api/latest/continuous-aggregates/refresh_continuous_aggregate/. Don't think we need anything in https://docs.timescale.com/api/latest/continuous-aggregates/refresh_continuous_aggregate/.
> 
Both links are the same... what's the other part you really meant?

We can add a note in the API section and need to mention that the behavior is turned OFF by default and need to be turned on by setting the GUC `timescaledb.enable_merge_on_cagg_refresh` and a warning to start using on 2.17.1 that include an important fix in this area.

**Comment by billy-the-fish** [comment]
Sorry, meant https://docs.timescale.com/use-timescale/latest/continuous-aggregates/refresh-policies/ 

Thanks for the info.
