### ISSUE TITLE
[Docs RFC] Can we upgrade postgresql when we have compressed TimescaleDB data?

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#352]
# Describe change in content, appearance, or functionality

Is compression a consideration when upgrading postgres. Felt that it should be said somewhere if you can/can't easily upgrade PG. Even a table on upgrades. Not sure what! 

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

 CC @greenweeds for visibility

**Comment by Loquacity** [comment]
@NunoFilipeSantos Do you know who would be a good SME for this content?

**Comment by NunoFilipeSantos** [comment]
@gayyappan or @mkindahl could probably answer this.

**Comment by mkindahl** [comment]
We haven't tested this, but since an upgrade does not change any contents of the tables, it should work.

If if does not work, I would consider it a bug.

**Comment by Loquacity** [comment]
> We haven't tested this, but since an upgrade does not change any contents of the tables, it should work.
> 
> If if does not work, I would consider it a bug.

**Comment by Loquacity** [comment]
Based on Mats' comment above, I'm closing this as a no-op for docs.
