### ISSUE TITLE
[Feedback] Page: /self-hosted/latest/upgrades/minor-upgrade/

### ISSUE THREAD

**Issue by gabrieloshiro** [timescale/docs#3579]
### Is it easy to find the information you need?

No

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

Hello,

The article presents no solution for the most common error message:

```
# psql $SOURCE -c "ALTER EXTENSION timescaledb UPDATE TO '2.16.1';"
ERROR:  extension "timescaledb" has no update path from version "2.11.0" to version "2.16.1"
# psql $SOURCE -c "ALTER EXTENSION timescaledb UPDATE;"
ERROR:  extension "timescaledb" has no update path from version "2.11.0" to version "2.17.1"
```

Thank you in advance

**Comment by billy-the-fish** [comment]
Hi @gabrieloshiro , you raise a fair point. I've updated these docs so people clearly see that you have to upgrade within compatibility guidelines: https://docs-dev.timescale.com/docs-3579-feedback-page-self-hostedlatestupgradesminor-upgrade/self-hosted/3579-feedback-page-self-hostedlatestupgradesminor-upgrade/upgrades/. Any comments in https://github.com/timescale/docs/pull/3630/files please.
