### ISSUE TITLE
[Feedback] Page: /migrate/latest/live-migration/

### ISSUE THREAD

**Issue by gabrieloshiro** [timescale/docs#3580]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

The command 

```
psql -X -d $SOURCE -c 'alter system set wal_sender_timeout=30m'
```

Throws the following error

```
ERROR:  trailing junk after numeric literal at or near "30m"
LINE 1: alter system set wal_sender_timeout=30m
```

I believe the correct command is

```
psql -X -d $SOURCE -c 'alter system set wal_sender_timeout=30'
```

**Comment by atovpeko** [comment]
It is actually `psql -X -d $SOURCE -c "alter system set wal_sender_timeout='30min'"`

Now fixed. Thanks for reporting!
