### ISSUE TITLE
[Feedback] Improve data tiering examples

### ISSUE THREAD

**Issue by jonatas** [timescale/docs#3590]
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

Community user asking clarity about data tiering using non timestamp columns:

https://www.timescale.com/forum/t/interval-type-for-add-tiering-policy/2826/3

I think it worth to add more data tiering examples using unix time to make it easy for future users to see how they can configure it properly and specially casting the intervals maybe challenging, depending on the data type.

**Comment by atovpeko** [comment]
@jonatas this seems like a part of the API reference for data tiering, which is already on the roadmap: https://github.com/timescale/docs/issues/3573 Do you mind if I close this ticket in favor of the API one?

**Comment by jonatas** [comment]
For sure.
