### ISSUE TITLE
[Feedback] Page: /getting-started/latest/tables-hypertables/

### ISSUE THREAD

**Issue by miguelvalente** [timescale/docs#3607]
### Is it easy to find the information you need?

None

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

do i need to use timestamp data type?

**Comment by billy-the-fish** [comment]
Hi @miguelvalente , thanks for the feedback.  best practice is to use timestamptz. You can see a bit more about it here: https://docs.timescale.com/use-timescale/latest/hypertables/create/#create-a-hypertable.
