### ISSUE TITLE
[Feedback] Page: /self-hosted/latest/configuration/postgres-config/

### ISSUE THREAD

**Issue by ann8ty** [timescale/docs#3619]
### Is it easy to find the information you need?

No

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

They tell me how to get the location of the config file as /home/postgres/pgdata/data/postgresql.conf and then what?  Do I have access to this file somehow?

**Comment by billy-the-fish** [comment]
Hi @ann8ty , thanks for the feedback. Can you have a quick look at https://github.com/timescale/docs/pull/3624/files and tell me if these updates make things clearer.
