### ISSUE TITLE
[Feedback] Page: /api/latest/hypertable/create_hypertable_old/

### ISSUE THREAD

**Issue by deefdragon** [timescale/docs#3628]
### Is it easy to find the information you need?

No

### Are the instructions clear?

None

### How could we improve the Timescale documentation site?

The [hypertable create documentation under use timescale](https://docs.timescale.com/use-timescale/latest/hypertables/create/) links to the old api for creating a hypertable in a big note, but I cant find on the page anywhere it links to the new documentation. 

The old documentation page then has no reference where to go for the new documentation. It took me 20 minutes of bumbling back and forth reading other pages to finally see the `create_hypertable` above the `create_hypertable (old interface)` in the sidebar.

The create hypertables example should link to the API docs somewhere (probably in the note that references the old variant so both can be found easily), and the old api docs and new api docs should cross link to make discovering the opposite variant easier.

**Comment by billy-the-fish** [comment]
Hi @deefdragon , good point. Can you have a look at https://github.com/timescale/docs/pull/3636/files and add any comments please.
