### ISSUE TITLE
[Content Bug] Missing Python in stocks tutorial

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#378]
# Describe the bug

Message: https://docs.timescale.com/timescaledb/latest/tutorials/analyze-intraday-stocks/explore-stocks-data/#install-plotly-and-pandas
This guide has some issues.
You are missing this line from the python code:
import plotly.express as px
Also this line:
WHERE time < now() - INTERVAL '{bucket}'
should probably be:
WHERE time > now() - INTERVAL '{bucket}'

**Comment by jacobprall** [comment]
Resolved
