### ISSUE TITLE
[Site Bug] Issue with the page: /api/latest/informational-views/license/

### ISSUE THREAD

**Issue by erimatnor** [timescale/docs#387]
# Describe the bug

The `timescaledb.license` setting is a GUC (settings variable) and not an informational view as implied by the section.

## What do the docs say now?

That timescaledb.license is an informational view.

## What should the docs say?

That the timescaledb.licence is a settings variable (GUC).

# Page affected
https://docs.timescale.com/api/latest/informational-views/license/

# Version affected

latest

**Comment by Loquacity** [comment]
@erimatnor which section do you think it should be moved to?

**Comment by erimatnor** [comment]
Since it is a configuration variable, it makes sense to move it to the configuration page:  https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/timescaledb-config/

Also note that, currently, the navigation pane says:
`timescaledb_information.license` (which doesn't exist) while the actual page says `timescaledb.license`. The latter is the correct fully qualified name of this settings variable.
