### ISSUE TITLE
[Docs RFC] Update "create service" flow

### ISSUE THREAD

**Issue by lukas-bernert** [timescale/docs#399]
# Describe change in content, appearance, or functionality

The flow for "creating a service" has changed. Now, when clicking on "create service" a modal opens.
The modal has two tabs: 
1) Create a service with demo data (starts Demo tutorial)
2) Create a service without demo data.
 2.1) Advanced Options

For new signups, the (1) tab is open by default. 
If a user already has a service running (2) tab will be open by default.

# Subject matter expert (SME)

@lukas-bernert 

# Deadline

It's live on prod. Whenever someone has time to fix it.

# Any further info

<img width="1440" alt="Screenshot 2021-09-14 at 15 51 13" src="https://user-images.githubusercontent.com/23032575/133280816-aa706583-8d93-4922-8b4e-d89b6cb48843.png">
<img width="1440" alt="Screenshot 2021-09-14 at 15 51 46" src="https://user-images.githubusercontent.com/23032575/133280825-7251df55-ebf8-48f8-85dd-3d4109ad7f4a.png">
<img width="1440" alt="Screenshot 2021-09-14 at 15 51 53" src="https://user-images.githubusercontent.com/23032575/133280835-7f546846-9db5-4030-a5e1-9b263a7a8168.png">

**Comment by minkimipt** [comment]
@lukas-bernert, I've recently created an issue https://github.com/timescale/web-cloud/issues/1653 related to this. Just FYI.
