### ISSUE TITLE
[Docs RFC] add subsection for renaming a service name

### ISSUE THREAD

**Issue by clarkbw** [timescale/docs#400]
# Describe change in content, appearance, or functionality

With the new simplified service creation flow there's no opportunity to name the service you create, instead each service is given a generated name in the format `db-NNNN`. While the advanced service creation view allows for naming a service we'll shortly be removing this option once we've finalized a new simplified system for renaming services which will work for services created through either flow.

This has yet to be implemented on the front end but here are screenshots of the mockups which will likely be very close to the final version.

![Screen Shot 2021-09-14 at 7 51 16 AM](https://user-images.githubusercontent.com/2134/133280739-0b9b230e-d6f1-4739-b9a8-b792af7eee7d.png)

![Screen Shot 2021-09-14 at 7 51 30 AM](https://user-images.githubusercontent.com/2134/133280750-3ebf8019-fbce-4ecb-8eaf-855526894331.png)

I believe a small subsection after the service create https://docs.timescale.com/timescale-forge/latest/create-a-service/#create-a-timescale-forge-account for how to rename would work well.

# Subject matter expert (SME)

@clarkbw 

# Deadline

End of Sept 2021

# Any further info

[Anything else you want to add, or further links]

**Comment by clarkbw** [comment]
This has gone live in production now.  Here are some screenshots and a quick video of it

![Screen Shot 2021-10-04 at 9 24 13 AM](https://user-images.githubusercontent.com/2134/135888414-3c2fdc34-42c9-49b1-a8c2-92b45e385f2c.png)

![Screen Shot 2021-10-04 at 9 24 23 AM](https://user-images.githubusercontent.com/2134/135888421-481e5c56-8211-4e9d-b1ed-9d30d5154d78.png)

https://user-images.githubusercontent.com/2134/135888381-6f7ea8ff-fb23-4672-b61d-4da07ea56a9a.mov

**Comment by Loquacity** [comment]
Now that the rename is done, I'm going to go back through and do these 👍  Thanks for the patience!
