### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/getting-started/create-hypertable/

### ISSUE THREAD

**Issue by danielbprice** [timescale/docs#413]
# Describe the bug

Overall I think the Timescale documentation is excellent, and I really appreciate it.   This page is useful.  That said, I am technical user but I didn't find the TIP on this page to be helpful:

> TIP
For technically interested readers, the value of the Hypertable is how data is partitioned on disk. The index value is automatically augmented by the time dependency of the data to allow more focused use of memory and query planning resources. While in PostgreSQL (and other Relational Database Management Systems) you can build indexes on one or more values, the data must still be retrieved. Retrieval is in most cases, from portions of the physical layer (memory or disk), which doesn't always result in effective use of memory and disk resources. By automatically partitioning on time, transparently, Hypertables improve the resource usages grouping data into smaller chunks based on time, so that queries and data-stores are much more efficient with time-series data.

The last sentence, in particular, seems to repeat itself and chase its own tail.  Maybe it would be better to point technically inclined users to a more complete dive into hypertables, such as https://docs.timescale.com/timescaledb/latest/overview/core-concepts/hypertables-and-chunks/ ?  I don't know.

**Comment by Loquacity** [comment]
Thanks! I'll get that updated 👍
