### ISSUE TITLE
[Docs RFC] Document about Indexing json fields contains duplicated "are"

### ISSUE THREAD

**Issue by bulb4saur** [timescale/docs#440]
# Describe change in content, appearance, or functionality

The docs at https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/json/#indexing-json-fields currently have duplicated `are` in the 2nd point of JSON field usage.

2. We use the JSONB data type (that is, JSON stored in a binary format) and not the JSON data type. JSONB data types are `are` more efficient in both storage overhead and lookup performance.

Expected changed results:

2. We use the JSONB data type (that is, JSON stored in a binary format) and not the JSON data type. JSONB data types are more efficient in both storage overhead and lookup performance.

**Comment by knaitas** [comment]
very nice find!
