### ISSUE TITLE
[Docs RFC] Add Auto-scaling on Cloud to Disk Management section

### ISSUE THREAD

**Issue by jacobprall** [timescale/docs#452]
# Describe change in content, appearance, or functionality

CSMs have requested documentation on Autoscaling feature on Forge.

# Subject matter expert (SME)

@lukas-bernert 

# Deadline

ASAP

**Comment by Loquacity** [comment]
This was done in https://github.com/timescale/docs/pull/221 is there further content required?

**Comment by mfreed** [comment]
I think the section "Disk management" should also be updated to include autoscale storing references.
