### ISSUE TITLE
[Docs RFC] Revamp 'Forge' Landing page

### ISSUE THREAD

**Issue by jacobprall** [timescale/docs#483]
# Describe change in content, appearance, or functionality

Revamp 'Forge' landing page to focus more on what makes Forge unique as opposed to just TimescaleDB.
Content to be written by Carlota with Avthar and approved by Prashant and Mike.

# Subject matter expert (SME)

@avthars @carlotas19 

# Deadline

End of October

# Any further info

**Comment by Loquacity** [comment]
Outdated.
