### ISSUE TITLE
[Docs RFC] Compression updates

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#489]
# Describe change in content, appearance, or functionality

We don't currently currently cover this topic well. Use the blog as source, especially this bit:

> When you insert a new row into a chunk that has been compressed, we compress this single row and save it in compressed form in the internal chunk. This is why inserting into a compressed chunk has a very small performance penalty compared to inserts to uncompressed chunks: because we are compressing these new rows in a row-by-row manner as they are written. (Thus, if you are doing a bulk backfill of a large amount of historical data, we still recommend our existing backfill approach for higher ingest performance.)

Also address https://github.com/timescale/docs/issues/619

Ping @ryanbooz for his compression Twitch stream recording from 2021-11-23

# Subject matter expert (SME)

@gayyappan @tylerfontaine @ryanbooz 

# Deadline

[When does this need to be addressed]

# Any further info

https://blog.timescale.com/blog/timescaledb-2-3-improving-columnar-compression-for-time-series-on-postgresql/

**Comment by charislam** [comment]
Also include Ryan's explanation of `compress_after` and `schedule_interval` from the forum: https://www.timescale.com/forum/t/compress-inactive-chunks-immediately/279/3

- How they work
- How you would set these to achieve the desired effect
- Potential pitfalls when choosing compression parameters

**Comment by charislam** [comment]
Address #1005 at the same time

**Comment by Loquacity** [comment]
We'll address this in a new issue.
