### ISSUE TITLE
[Docs RFC] Update advanced analytics section to include skip scan feature

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#511]
# Describe change in content, appearance, or functionality

> was i supposed to also insert each device id into a separate table for speed? i think i might be looking for something like https://docs.timescale.com/timescaledb/latest/how-to-guides/query-data/advanced-analytic-queries/#last-point
> 
> nope, easy to store them all in the same place. Actually, we need to update those docs.  A few versions ago added “skip scan” functionality, such that the instructions there ar emuch less neede.d  Thanks!

# Subject matter expert (SME)

@svenklemm 

# Deadline

[When does this need to be addressed]

# Any further info

Community Slack thread: https://timescaledb.slack.com/archives/C4GT3N90X/p1633799534188400?thread_ts=1633799169.187200&cid=C4GT3N90X

**Comment by Loquacity** [comment]
@NunoFilipeSantos Who is our skipscan expert?

**Comment by NunoFilipeSantos** [comment]
@svenklemm is our SME on Skipscan.

**Comment by Loquacity** [comment]
@svenklemm Do we have any source content anywhere on skipscan that we can get into the docs?

**Comment by svenklemm** [comment]
There is
- https://blog.timescale.com/blog/how-we-made-distinct-queries-up-to-8000x-faster-on-postgresql/
- https://github.com/timescale/timescaledb/blob/master/tsl/src/nodes/skip_scan/README.md
