### ISSUE TITLE
[Site Bug] Update RHEL Install docs: /docs-tutorial-aws-lambda/timescaledb/tutorial-aws-lambda/how-to-guides/install-timescaledb/self-hosted/rhel-centos/installation-yum/

### ISSUE THREAD

**Issue by NickMRamirez** [timescale/docs#513]
_Use this template for reporting bugs in the docs._

# Describe the bug

On RHEL 8, I get an error when installing the TimescaleDB package: 

```
$ sudo yum install -y timescaledb-2-postgresql-13
Last metadata expiration check: 0:04:21 ago on Mon 11 Oct 2021 10:26:59 PM UTC.
Error: 
 Problem: package timescaledb-2-postgresql-13-2.4.2-0.el8.x86_64 requires postgresql13-server >= 13.4, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides libicui18n.so.60()(64bit) needed by postgresql13-server-13.4-1PGDG.rhel8.x86_64
  - nothing provides libicuuc.so.60()(64bit) needed by postgresql13-server-13.4-1PGDG.rhel8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages
```

Note that the same procedure worked for me on CentOS 8.

The exact commands I am running are this (encapsulated in a Bash function): 

```
yum_install_timescaledb() {
  echo "Adding PostgreSQL package repository"
  yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-$(rpm -E %{rhel})-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  if [ $? -ne 0 ]; then
    echo "Failed to add PostgreSQL package repository."
    exit 1
  fi

  echo "Adding TimescaleDB package repository"
  curl -s https://packagecloud.io/install/repositories/timescale/timescaledb/script.rpm.sh | bash
  if [ $? -ne 0 ]; then
    echo "Failed to add TimescaleDB package repository."
    exit 1
  fi
  
  # disable builtin postgres packages on CentOS 8
  if command -v dnf; then dnf -qy module disable postgresql; fi

  echo "Installing TimescaleDB"
  yum install -y timescaledb-2-postgresql-13
  if [ $? -ne 0 ]; then
    echo "Failed to install TimescaleDB."
    exit 1
  fi

  /usr/pgsql-13/bin/postgresql-13-setup initdb
  timescaledb-tune -yes --pg-config=/usr/pgsql-13/bin/pg_config
  
  echo "Restarting PostgreSQL service"
  systemctl enable postgresql-13
  systemctl restart postgresql-13
}
```

## What do the docs say now?

I followed this install procedure for CentOS/RHEL: https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/rhel-centos/installation-yum/#installation-yum

## What should the docs say?

If there are extra steps for RHEL, those should be documented.

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/rhel-centos/installation-yum/#installation-yum

# Version affected

current version

**Comment by NickMRamirez** [comment]
Just checking back on this. TimescaleDB is supported on RHEL, isn't it? Is  this a documentation issue? Or a packaging issue?

**Comment by Loquacity** [comment]
> Just checking back on this. TimescaleDB is supported on RHEL, isn't it? Is this a documentation issue? Or a packaging issue?

Hi Nick, yes, this is a documentation issue, I believe.

**Comment by Loquacity** [comment]
> It seems to be only a problem with my Vagrant box. On RHEL 8 on AWS, it works fine. So, this is probably a non-issue.

Thanks for the info. I'm about to go through all the install docs and re-test them, so I'll look them over anyway.
