### ISSUE TITLE
[Docs RFC] Specify that `migrate_data` isn't supported for distributed hypertables

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#538]
# Describe change in content, appearance, or functionality

> It looks like we should update to fix to make clear this option is not supported. 

# Subject matter expert (SME)

@NunoFilipeSantos 

# Deadline

[When does this need to be addressed]

# Any further info

Community Slack thread: https://timescaledb.slack.com/archives/C0174FLJBEZ/p1633975775173100

**Comment by Loquacity** [comment]
@NunoFilipeSantos I'm not sure this is still true, since the API doc for `api/create_distributed_hypertable.md` lists `migrate_data` as an optional argument. Can you please confirm?

In the meantime, I did a little tidying up in the migration index.

**Comment by NunoFilipeSantos** [comment]
@erimatnor can you please confirm?

**Comment by erimatnor** [comment]
Confirmed:
```sql
postgres=# select create_distributed_hypertable('simple', 'id', 'device_name', migrate_data=>true);
ERROR:  cannot migrate data for distributed hypertable
```

**Comment by Loquacity** [comment]
> Confirmed:
> 
> ```sql
> postgres=# select create_distributed_hypertable('simple', 'id', 'device_name', migrate_data=>true);
> ERROR:  cannot migrate data for distributed hypertable
> ```

So, I think we need to remove the option from the API doc, and also mention this in the How To? Correct?
