### ISSUE TITLE
Clarify gapfilling for multiple columns in example

### ISSUE THREAD

**Issue by mfreed** [timescale/docs#540]
See question here:  https://stackoverflow.com/questions/60254902/gap-filling-ohlcv-in-timescaledb/60254977#60254977

**Comment by Loquacity** [comment]
SME: @svenklemm

**Comment by Loquacity** [comment]
> @Loquacity where do you want to see this added?

https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/gapfilling-interpolation/ ?

**Comment by Loquacity** [comment]
These pages were updated as part of the hyperfunctions release late last year, so I think we can probably call this done. Please feel free to reopen if there is something missing.
