### ISSUE TITLE
[Content Bug] toolkit installation page does not mention available packages

### ISSUE THREAD

**Issue by svenklemm** [timescale/docs#541]
toolkit installation page does not mention available packages

## What do the docs say now?
Nothing

## What should the docs say?
Packages are available for Debian, Ubuntu, RedHat

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/#install-timescaledb-toolkit

# Version affected
1.3.0
[Which version of the site you noticed the bug on]

# Subject matter expert (SME)
@svenklemm

**Comment by Loquacity** [comment]
The instructions currently say to use Cargo to install from source, AFAICT. Is that not, in fact, the best way to do it? Can you please point me to some more info?

**Comment by svenklemm** [comment]
It is not the best way to do it since we offer packages. Unfortunately this has never been documented but we build RPM, Debian and Ubuntu packages. So installing those is much more convenient then building from source.
https://packagecloud.io/app/timescale/timescaledb/search?page=2&q=toolkit
