### ISSUE TITLE
[Content Bug] Missing location field in Python quick start guide

### ISSUE THREAD

**Issue by lukas-bernert** [timescale/docs#552]
_Use this template for reporting bugs in the docs._

# Describe the bug

Followed the Python quick start guide step by step. At the prepared statement step, after adding this block of code to my file
```# query with placeholders
cursor = conn.cursor()
query = """
           SELECT time_bucket('5 minutes', time) AS five_min, avg(cpu)
           FROM sensor_data
           JOIN sensors ON sensors.id = sensor_data.sensor_id
           WHERE sensors.location = %s AND sensors.type = %s
           GROUP BY five_min
           ORDER BY five_min DESC;
           """

data = (location, sensor_type)
cursor.execute(query, data)
results = cursor.fetchall()
```

and run it, I get the following error:
`NameError: name 'location' is not defined`

The error is referring to line 12 in the code snippet.

## What should the docs say?

# Page affected

https://docs.timescale.com/timescaledb/latest/quick-start/python/#executing-queries-using-prepared-statements 

# Version affected

Latest

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
@lukas-bernert do you know what the correct code is?

**Comment by lukas-bernert** [comment]
I don't. Maybe we can find out via git blame who wrote the tutorial and ask them.

**Comment by Loquacity** [comment]
> I don't. Maybe we can find out via git blame who wrote the tutorial and ask them.

Looks like it was @zseta https://github.com/timescale/docs/commit/50a69cb7b244bdbfb24dc375088db1261f1044c4
