### ISSUE TITLE
[Docs RFC] Add cags troubleshooting for named arguments

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#568]
# Describe change in content, appearance, or functionality

> Also, could you do just toolkit_experimental.counter_agg(time, value, toolkit_experimental.time_bucket_range('15 min'::interval, time))  without bounds =>   ? That seems to be error you are getting (cannot use named arguments) .

# Subject matter expert (SME)

@ramonguiu 

# Deadline

[When does this need to be addressed]

# Any further info

Community Slack thread: https://timescaledb.slack.com/archives/C4GT3N90X/p1635305238080800

**Comment by Loquacity** [comment]
> @davidkohn88 said he was going to make the changes, I believe.

@davidkohn88 do you have a PR open?

**Comment by davidkohn88** [comment]
Already merged-
https://github.com/timescale/docs/pull/565
Unless I missed something.
