### ISSUE TITLE
[Docs RFC] Update caggs docs to explain different retention policies

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#579]
# Describe change in content, appearance, or functionality

> If I have a table/hypertable with a retention policy of a week, but have the continuous aggregations retention policy being a month... is that going to be OK?

> Yes. It mean your raw data will be around for a week while continuous aggregates will be around for a month.

# Subject matter expert (SME)

@jonatas 

# Deadline

[When does this need to be addressed]

# Any further info

Link to Community Slack thread: https://timescaledb.slack.com/archives/C4GT3N90X/p1635806655175900

**Comment by jonatas** [comment]
Double-checking the docs now:
> This will create the conditions_summary_daily aggregate which will store the daily temperature per device from our conditions table. However, we have a problem here if we're using our 24 hour retention policy from above, as our aggregate will capture changes to the data for up to seven days. As a result, we will update the aggregate when we drop the chunk from the table, and we'll ultimately end up with no data in our conditions_summary_daily table.

Should we make this part a warning?

**Comment by Loquacity** [comment]
> Double-checking the docs now:
> 
> > This will create the conditions_summary_daily aggregate which will store the daily temperature per device from our conditions table. However, we have a problem here if we're using our 24 hour retention policy from above, as our aggregate will capture changes to the data for up to seven days. As a result, we will update the aggregate when we drop the chunk from the table, and we'll ultimately end up with no data in our conditions_summary_daily table.
> 
> Should we make this part a warning? Or maybe introduce a FAQ with the first question?

I was thinking a troubleshooting entry, personally, but there's no harm in having it as an admonition, then linking to a troubleshooting entry.
