### ISSUE TITLE
[Content Bug] Missing an Image

### ISSUE THREAD

**Issue by jacobprall** [timescale/docs#589]
# Describe the bug
Missing image in multi-node page - references non-existent diagram.
https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/about-multinode/#partitioning-methods
# Screenshots

<img width="681" alt="Screenshot 2021-11-05 at 11 56 47" src="https://user-images.githubusercontent.com/60765576/140551776-59f6dc24-5901-437f-b792-60c6a112caec.png">

**Comment by Loquacity** [comment]
Something went wrong with the image upload to S3. I've re-uploaded it and the URL should be working OK now: https://s3.amazonaws.com/assets.timescale.com/docs/images/multi-node-arch.png (No PR, as the doc is fine, it was the target that had a problem).
