### ISSUE TITLE
[Docs RFC] High-level copy-edit of all How To pages

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#60]
# Describe change in content, appearance, or functionality

The current How To pages (https://docs.timescale.com/timescaledb/latest/how-to-guides/) lack consistency. This issue tracks a high level review of these docs to bring them up to standard in terms of wording, writing style, syntax, etc. In preparation for a more comprehensive review of the structure later on.

# Subject matter expert (SME)

@Loquacity for writing guidance

**Comment by charislam** [comment]
Finished!
