### ISSUE TITLE
[Site Bug] Backup/restore instructions problem [Issue with the page: /timescaledb/latest/how-to-guides/backup-and-restore/timescaledb-backup/]

### ISSUE THREAD

**Issue by snspinn** [timescale/docs#629]
_Use this template for reporting bugs in the docs._

# Describe the bug

The `go get` command for installing `timescaledb-backup` appears to be broken. The command returns with a `can't load package` error.

### Full output:
```
ubuntu@ip-x-x-x-x:~$ go get github.com/timescale/timescaledb-backup/
can't load package: package github.com/timescale/timescaledb-backup: no Go files in /home/ubuntu/go/src/github.com/timescale/timescaledb-backup
```

This error is occuring on an AWS instance running Ubuntu 20.04 LTS. 
Go installed with: `apt get install golang-go`
Version:
 ```
ubuntu@ip-x-x-x-x:~$ go version
go version go1.13.8 linux/amd64
```

## What do the docs say now?

> Install timescaledb-backup:
> ```
> $ go get github.com/timescale/timescaledb-backup/
> ```

## What should the docs say?
I don't know.

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/timescaledb-backup/#installing-timescaledb-backup

# Version affected

**_latest_**

# Subject matter expert (SME)

na

# Screenshots

na

# Any further info

na

**Comment by Loquacity** [comment]
@jacobprall can you find me an SME for this?

**Comment by snspinn** [comment]
> @jacobprall can you find me an SME for this?

Unfortunately, not at this time. I have linked it to a related issue in the source repository here: https://github.com/timescale/timescaledb-backup/issues/41

As I mention there, I found what worked on Ubuntu Linux (20.04) was:
```
# Get the files
go get github.com/timescale/timescaledb-backup/

# Build and "install" ts-dump
cd ~/go/src/github.com/timescale/timescaledb-backup/cmd/ts-dump
go build
sudo mv ts-dump /usr/share/

# Build and "install" ts-restore
cd ~/go/src/github.com/timescale/timescaledb-backup/cmd/ts-restore
go build
sudo mv ts-restore /usr/share/
```

I am not familiar enough with Go to suggest an alternate method. Most linux/unix distros probably have similar workflows. However, this is arguably not succint or general enough to be suitable for the docs. I'll see if I can get an SME to bite on the other repo.
