### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/hypertables/create/

### ISSUE THREAD

**Issue by CliveDent** [timescale/docs#636]
Starting with timescaledb, here is what already confused me:

1) There is  `CREATE TABLE TABLE_NAME ...` as an example query and right below is `SELECT create_hypertable('conditions', ...` while there is no explanation for where did the 'conditions' come from. Same with the next example.

2) Link to `create_hypertable()` function documentation is missing. Also, the same example is used there but without table definition that is at this page.

Thank you.

**Comment by Rajakavitha1** [comment]
Hi @Loquacity Please let me know if the PR [ ](https://github.com/timescale/docs/pull/643) addresses the issues mentioned in this issue.

**Comment by Rajakavitha1** [comment]
> > Hi @Loquacity Please let me know if the PR [ ](https://github.com/timescale/docs/pull/643) addresses the issues mentioned in this issue.
> 
> Which PR?

Here's the PR: [ ](https://github.com/timescale/docs/pull/643)

**Comment by Loquacity** [comment]
> > > Hi @Loquacity Please let me know if the PR [ ](https://github.com/timescale/docs/pull/643) addresses the issues mentioned in this issue.
> > 
> > 
> > Which PR?
> 
> Here's the PR: #643

That PR only addresses point 1, from what I can see ... ?

**Comment by Loquacity** [comment]
Closed as duplicate of https://github.com/timescale/docs/issues/642
