### ISSUE TITLE
Broken formatting of the console output in the promscale docs

### ISSUE THREAD

**Issue by itroot** [timescale/docs#637]
# Describe the bug

Promscale docs have broken formatting in SQL examples , looks like text is not properly aligned.

## What should the docs say?

# Page affected

https://docs.timescale.com/timescaledb/latest/tutorials/promscale/promscale-run-queries/#querying-metric

# Version affected

# Subject matter expert (SME)

# Screenshots

![Screenshot from 2021-12-02 17-26-11](https://user-images.githubusercontent.com/141308/144441033-37538ea3-2b77-43f2-bc18-de2cf06f41a8.png)

# Any further info

cc @VineethReddy02 as I noticed that on the demo meeting

**Comment by VineethReddy02** [comment]
Thanks for pointing this out @itroot, Just to confirm you are pointing to the tabular output format that is not aligning with column names right?

**Comment by itroot** [comment]
> Thanks for pointing this out @itroot, Just to confirm you are pointing to the tabular output format that is not aligning with column names right?

@VineethReddy02 yup, that is correct.

**Comment by Loquacity** [comment]
Is this in the docs repo or in the promscale repo?
