### ISSUE TITLE
Horizontal scrolling on tables is awkward

### ISSUE THREAD

**Issue by arp242** [timescale/docs#641]
For example on this page, as well as some other API docs: https://docs.timescale.com/api/latest/hypertable/create_hypertable/#optional-arguments

The "Optional Arguments" table scrolls horizontally; to read this I need to keep scrolling to the left and right since the display width isn't enough to contain a full line of text in the "Description" column. I find this very awkward and difficult to use, and IMHO it would be much better if the "Description" column would just wrap so you can read the lot without scrolling horizontally:

![cap-2021-12-04T11:51:31](https://user-images.githubusercontent.com/1032692/144706875-bfec7b94-144d-460c-826a-4790d3852f48.png)

This occurs in both Firefox and Chromium, and looking at the CSS it seems intentional and not a browser-specific iissue – wasn't able to come up with some CSS to fix it in 2 minutes of mucking about with the inspector though.

**Comment by arp242** [comment]
Ah, it seems to be the `white-space: nowrap` on the `td` in the first row:

    .table table tr:first-child td { white-space: nowrap; }

This fixes it in my usercss for now:

    .table table tr:first-child td { white-space: inherit; }

**Comment by Loquacity** [comment]
Yeah, quite a few of the tables in the API Guide have issues. I'm working through them 👍

**Comment by Loquacity** [comment]
Looking at the source, the md is technically correct. I'm going to flick this issue back over to @jacobprall and maybe he can play with the rendering.

**Comment by arp242** [comment]
Seems this is fixed now.
