### ISSUE TITLE
Hypertable example commands are inconsistent

### ISSUE THREAD

**Issue by duncan-tsdb** [timescale/docs#642]
On https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/create/#creating-a-hypertable
sdf
`CREATE TABLE TABLE_NAME (
   time        TIMESTAMPTZ       NOT NULL,
   location    TEXT              NOT NULL,
   temperature DOUBLE PRECISION  NULL
);`
and
`SELECT create_hypertable('conditions', 'time');`

I believe the create table statement should use conditions instead of TABLE_NAME.

Same thing w/ distributed hypertables at https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/create/#creating-a-distributed-hypertable

`CREATE TABLE TABLE_NAME (
  time        TIMESTAMPTZ       NOT NULL,
  location    TEXT              NOT NULL,
  temperature DOUBLE PRECISION  NULL,
  humidity    DOUBLE PRECISION  NULL
);`

Also note the difference in schema. This causes problems when following the examples on https://docs.timescale.com/timescaledb/latest/how-to-guides/write-data/insert/ for inserting data.
`INSERT INTO conditions(time, location, temperature, humidity)
  VALUES (NOW(), 'office', 70.0, 50.0);`

**Comment by Loquacity** [comment]
PR #643 only addresses the table names in https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/create/#creating-a-hypertable Also needs to be done for https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/create/#creating-a-distributed-hypertable (and I suspect there are others, too ...)

**Comment by Loquacity** [comment]
@duncan-tsdb Heya, just trying to work out what needs to change here, and having some trouble. It looks like perhaps my recent updates to this page could have unexpectedly fixed the issue. Can you please clear your cache and take another look for me? 💖

**Comment by duncan-tsdb** [comment]
@Loquacity I looked over the pages seems as if everything is consistent and fixed now :)
