### ISSUE TITLE
[Site Bug] Add custom agg example  [Issue with the page: /api/latest/continuous-aggregates/create_materialized_view/]

### ISSUE THREAD

**Issue by chrissnell** [timescale/docs#663]
_Use this template for reporting bugs in the docs._

# Describe the bug

Documentation could be more clear about the parallelization requirements for a custom aggregate function.   Specifically, the need for this function to have a **combine function**, in addition to `PARALLEL = SAFE` set.  

The requirement for `PARALLEL = SAFE` is pretty obvious in the documentation for `CREATE AGGREGATE`, but the requirement for the combine function only gets a one-sentence mention, [buried in the documentation here](https://www.postgresql.org/docs/current/parallel-plans.html#PARALLEL-AGGREGATION).  

This caused me a lot of confusion and many wasted hours today.  It would be awesome if the docs could include an example custom aggregate function that is parallelizable and works with materialized views.

I offer up my function as an example, if you want to use it.  
https://gist.github.com/chrissnell/bcb1ce1bc15b49fd6c5b901e984060b7

## What do the docs say now?

Buried in the **Notes** section is a link to a PostgreSQL document that makes mention of the combiner function in a sentence buried in the page.  It's not at all obvious.

## What should the docs say?

The docs should have an example of a custom aggregate function that can be used with Timescale's materialzied views.  This would have saved me many hours!

# Page affected

https://docs.timescale.com/api/latest/continuous-aggregates/create_materialized_view/

**Comment by Loquacity** [comment]
@ryanbooz Do you want to be SME for this, or can you recommend someone?

**Comment by Loquacity** [comment]
These docs have been significantly revised since this was filed.
