### ISSUE TITLE
Missing design-doc link in tobs about page [Content Bug]

### ISSUE THREAD

**Issue by jacobprall** [timescale/docs#698]
_Use this template for reporting bugs in the docs._
design-doc is not defined in the file, leading to no link generated.

# Describe the bug

[Provide as much detail as you can]

## What do the docs say now?
[design doc][design-doc]
## What should the docs say?
design doc <--(link)
# Page affected

[Link](https://docs.timescale.com/promscale/latest/tobs/about/#about-the-observability-stack-tobs-for-kubernetes)

# Version affected

[Which version of the site you noticed the bug on]

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
@jacobprall Please don't assign anyone to issues in the backlog, so that we can keep track of what's available to be worked on and what isn't. The person who picks it up from the backlog will assign themselves to it when they start work.

**Comment by Loquacity** [comment]
This has been fixed organically with recent edits.
