### ISSUE TITLE
[Docs RFC] Documentation for MST to Cloud migrations

### ISSUE THREAD

**Issue by lukas-bernert** [timescale/docs#699]
# Describe change in content, appearance, or functionality

The docs currently offer "How to guides" for migrating data to/from TimescaleDB. However, there's no tailored documentation for MST to Cloud migrations.
Trying to migrate with the traditional `pg_dump` / `pg_restore` method users get stuck because they don't set the necessary flags. To improve the user experience for MST to Cloud migrations a guide with the correct commands should be added to the Timescale documentation.

What is needed?

- [ ] A dedicated guide "Migrate from MST to Cloud" 
    - See[ outline](https://docs.google.com/document/d/1FH_lC8h-rrUIqXiJDRXDHs6zHSGCSjYo5IwcGTp9p0E/edit#)

# Subject matter expert (SME)

@lukas-bernert 

# Deadline

ASAP. Countless support cases were opened over the last weeks.

# Any further info

Some [research](https://github.com/timescale/product/tree/lb-mst-cloud-migration/migration-project) on the best way to migrate with currently supported tools can be found here. For these initial docs I'd propose to go forward with [V4 (pg_dump / pg_restore)](https://github.com/timescale/product/blob/lb-mst-cloud-migration/migration-project/V4-pg_dump-AND-pg_restore_w_CAGGs_AND_compression.md).

A note should be added saying, that some warning might come up during the dump/restore process, however, they can be ignored ([See log files for more info](https://github.com/timescale/product/tree/lb-mst-cloud-migration/migration-project/logs)) 
e.g.: `pg_dump: warning: there are circular foreign-key constraints on this table:`
`pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied`
`pg_restore: WARNING:  no privileges were granted for "_timescaledb_cache"`

**Comment by lukas-bernert** [comment]
@Loquacity can you give a rough estimate of when the docs team could start working on this?

**Comment by Loquacity** [comment]
> @Loquacity can you give a rough estimate of when the docs team could start working on this?

@charislam is this something you might be interested in picking up? If not, let me know, and I'll pick it up in the next week or two.

**Comment by charislam** [comment]
@Loquacity yes I can pick this up! @lukas-bernert I will be in touch shortly to get more info.

**Comment by charislam** [comment]
# Outstanding info

- [ ] Add parallel-copy method
- [ ] Migration method for CAGGs with deleted underlying data
- [ ] Parallel ingest to avoid data loss for active databases
