### ISSUE TITLE
[Docs RFC] Install docs - version information

### ISSUE THREAD

**Issue by lucieva** [timescale/docs#718]
# Describe change in content, appearance, or functionality

This feedback was received through the Contact us form.

Hello,
I am following your instructions at:
https://docs.timescale.com/install/latest/self-hosted/installation-debian/#setting-up-the-timescaledb-extension
to install timescale within the official postgres Docker image.

Your step 5 reads:
apt install timescaledb-2-postgresql-14
That is helpful, but I am wondering is there some more specific version information I can specify so that I can lock to a specific version of timescale, e.g. version 2.5.1  The way this line reads currently, I imagine that I would be installing the latest release of version 2, which might be 2.5.2 or 2.3 etc, for example.

I was able to find a package list at:
https://packagecloud.io/timescale/timescaledb
But it is not clear to me how to use the info at that page to produce a better input to apt install, because I did not find "timescaledb-2-postgresql-14" in that list.

Best,
Ian

# Subject matter expert (SME)

@svenklemm 

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
@NunoFilipeSantos Who would be a good SME for this?

**Comment by NunoFilipeSantos** [comment]
@svenklemm is the SME. He was responsible for the entire new package repository for debian / Ubuntu.

**Comment by svenklemm** [comment]
You can either do: `sudo apt-get install timescaledb-2-2.6.0-postgresql-12` or `sudo apt-get install timescaledb-2-postgresql-14=2.6.0~debian11`. The first option will always stay that version while the 2nd command will be affected by `apt-get update`.
