### ISSUE TITLE
[Content Bug] Error when creating a hypertable via Sequelize

### ISSUE THREAD

**Issue by mscott5861** [timescale/docs#719]
_Use this template for reporting bugs in the docs._

# Describe the bug

Creating a hypertable using Sequelize by following the documentation results in the error:

```
ERROR: cannot create a unique index without the column "time" (used in partitioning)
```

This Issue has already been raised [Issue 551](https://github.com/timescale/docs/issues/551) and was marked as having been addressed in [PR #605](https://github.com/timescale/docs/pull/605). Nevertheless, following the tutorial as written following the additions of PR #605 still generates the error above.

## What do the docs say now?

The offending query:

```
return queryInterface.sequelize.query("SELECT create_hypertable('page_loads', 'time');");
```

## What should the docs say?

I'm not sure. I've been using the docs to try to learn Timescale, and pretty quickly ran into this roadblock. This error doesn't make any sense to me, and none of the explanations puported to resolve it (e.g., "delete the primary key") have any effect. Composite primary keys make no difference, either.

[Provide the URL to the page you noticed the bug on]
https://docs.timescale.com/timescaledb/latest/quick-start/node/#create_hypertable

**Comment by Loquacity** [comment]
@jonatas Are you able to look into this, please?

**Comment by jonatas** [comment]
Sure @Loquacity! I was double checking what I have here and it continue working.


Just sharing what I have in my configs. Using timescale locally on my mac M1.

```bash
⋊> ~/c/t/t/node-example cat config/config.json                                                                               17:47:30
{
  "development": {
    "username": "jonatasdp",
    "password": "",
    "database": "node-example",
    "host": "localhost",
    "port": "5432",
    "dialect": "postgres",
    "protocol": "postgres"
  }
}
```

Creating the database:

```bash
npx sequelize db:create                                                                              17:47:01

Sequelize CLI [Node: 12.22.1, CLI: 6.3.0, ORM: 6.9.0]

Loaded configuration file "config/config.json".
Using environment "development".
Database node-example created.
```

Migrating the data:
```bash
⋊> ~/c/t/t/node-example npx sequelize db:migrate                                                                             17:47:03

Sequelize CLI [Node: 12.22.1, CLI: 6.3.0, ORM: 6.9.0]

Loaded configuration file "config/config.json".
Using environment "development".
== 20211117120932-add_tsdb_extension: migrating =======
== 20211117120932-add_tsdb_extension: migrated (0.224s)

== 20211117121024-create-page-loads: migrating =======
== 20211117121024-create-page-loads: migrated (0.011s)

== 20211117122623-add_hypertable: migrating =======
== 20211117122623-add_hypertable: migrated (0.017s)
```

Just double checking the versions:
```
⋊> ~/c/t/t/node-example node -v                                                                                              17:47:09
v12.22.1
⋊> ~/c/t/t/node-example npx -v                                                                                               17:47:26
6.14.12
```
Hey @mscott5861, can you share a bit more context of your machine and the workflow and versions you're using?

**Comment by Loquacity** [comment]
Outdated.
