### ISSUE TITLE
[Content Bug] Outdated code example

### ISSUE THREAD

**Issue by charislam** [timescale/docs#745]
_Use this template for reporting bugs in the docs._

# Describe the bug

SQL query no longer returns any rows because there is no data within the previous 6 months. (Newest data in the dataset is from 2021-04-27.)

## What do the docs say now?

```sql
SELECT time_bucket('15 days', time) as "bucket"
   ,city_name, avg(temp_c)
   FROM weather_metrics
   WHERE time > now() - (6* INTERVAL '1 month')
   GROUP BY bucket, city_name
   ORDER BY bucket DESC;
```

## What should the docs say?

# Page affected

[Getting started > Query your data](https://docs.timescale.com/timescaledb/latest/getting-started/query-data/#time-bucket)

# Version affected

latest

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by charislam** [comment]
This could be fixed temporarily by replacing `6* INTERVAL '1 month'` with `12 * INTERVAL '1 month'`, but that creates maintenance friction.

Is there any pedagogical reason not to set an explicit time interval rather than offsetting the queried interval from the current time?

(This also applies to the other queries on this page, which will eventually go out of date. Timescales: 1 year, 2 years, 5 years)

**Comment by 1u0** [comment]
Hi, just my 2 cents.
I think the main "root cause" in the `Getting started` tutorial is the static data set used as the example.
It has fixed timestamps that gradually becoming "far in the past":

> ...
> The dataset contains weather metrics for each city from 1 January 1979 to 27 April 2021.

I think "a proper fix" would be rewriting the tutorial by using either some synthetically generated data (the generation would happen as part of the tutorial steps to setup the demo environment). Or, by using some data source (from some remote service) that will provide such data.

**Comment by Loquacity** [comment]
The Getting Started Guide is due to be re-written soon, with a whole new dataset that (at least in part) will resolve this problem. Absolutely happy for it to have a copyedit for now, but don't spend too much time on it.

**Comment by charislam** [comment]
Sounds good! I put in a temporary fix for this problem and will stop thinking about it until the rewrite. :)
