### ISSUE TITLE
[Docs RFC] Add info about starting background workers

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#748]
# Describe change in content, appearance, or functionality

> Hello experts, the timescale scheduler died in our Crunchy operator (not sure how). So scheduled jobs are not running anymore. Is there a way to restart the scheduler without restarting the db/switching pod? 

> Managed to get them running using SELECT _timescaledb_internal.start_background_workers();

# Subject matter expert (SME)

@svenklemm 

# Deadline

[When does this need to be addressed]

# Any further info

- Link to bug that references solution: https://github.com/timescale/timescaledb/issues/3950
- Link to community Slack thread: https://timescaledb.slack.com/archives/C4GT3N90X/p1642672713409400

**Comment by Loquacity** [comment]
@svenklemm Looking at the docs, I think this is going to require a whole scheduling How To. Do we have any kind of source content for this, that you know of? Maybe something in the blog?

**Comment by svenklemm** [comment]
@Loquacity Hmm I guess a starting point would be https://docs.timescale.com/api/latest/actions/ but I dont think we have the internal functions mentioned in this ticket documented anywhere.
