### ISSUE TITLE
[Site Bug] Error in Ruby Code Quick Start [Issue with the page: /timescaledb/latest/quick-start/ruby/]

### ISSUE THREAD

**Issue by scomma** [timescale/docs#752]
Additional documentation regarding testing

# Describe the bug

After migrating to timescale I found that all my Rails tests would not run. Every test would fail with the same error:

> Foreign key violations found in your fixture data. Ensure you aren't referring to labels that don't exist on associations.

Turns out this is caused by timescale's internal foreign keys.

## What do the docs say now?

The docs didn't cover Rails testing. Extensive Google search couldn't find anything about it, but isolating the changes to just the database instance revealed the issue.

## What should the docs say?

In `config/environments/test.rb`, add:

```
  config.active_record.verify_foreign_keys_for_fixtures = false
```

# Page affected

https://docs.timescale.com/timescaledb/latest/quick-start/ruby/#goal

# Version affected

Latest

# Subject matter expert (SME)

Not known

# Screenshots

-

# Any further info

-

**Comment by Rajakavitha1** [comment]
Closing this issue for now because this has been addressed in https://github.com/timescale/docs/pull/953
