### ISSUE TITLE
[Content Bug] Broken links in the new documentation

### ISSUE THREAD

**Issue by noctarius** [timescale/docs#76]
# Describe the bug

The two links marked in the screenshot are broken and result in a 404 page.

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/rhel-centos/installation-yum/##yum-installation

# Version affected

latest

# Screenshots

![Screen Shot 2021-05-21 at 12 17 56](https://user-images.githubusercontent.com/1142801/119175247-e0284500-ba69-11eb-88ca-b5c1f7645c49.png)

**Comment by Loquacity** [comment]
Thanks for the report! I'll get this fixed up :)

**Comment by Loquacity** [comment]
This was fixed in a different PR.
