### ISSUE TITLE
[Content Bug] How-to Guides > Ingestion data from other sources page, Kafka source: is the information correct?

### ISSUE THREAD

**Issue by 1u0** [timescale/docs#763]
# Describe the bug

The documentation about Kafka as a data source for TimescaleDB has mixed information.
Specifically, there might be mix of information:
 * Feeding data into TimescaleDB as target storage system from Kafka as data source (vs. using TimescaleDB as data source for Kafka).
 * Kafka JDBC Sink connector vs. Debezium PostgreSQL connector (source connector).

## What do the docs say now?

Snippet from the documentation (emphasis mine):

> You can ingest data into TimescaleDB using the Kafka Connect JDBC Sink connector. The connector is deployed to a Kafka Connect runtime service, and ingests change events **from** PostgreSQL databases, such as TimescaleDB.
>
> The deployed connector monitors one or more schemas within a TimescaleDB server and **writes all change events to Kafka topics**, which can be independently consumed by one or more clients. ...
>
> You can also use the PostgreSQL connector as a library without Kafka, which allows applications and services to **connect directly to TimescaleDB and retrieve change events**.

Also this paragraph links to Debezium documentation (instead of the mentioned Kafka JDBC connector):

> For more information about the Kafka Connect JDBC Sink connector, see the **Kafka connector GitHub page**.

## What should the docs say?

I think the more interesting case would be: how to _ingest_ data from Kafka into some TimescaleDB hypertables (with additional continuous aggregates).
This is a system setup, where Kafka is used as some message bus across multiple services, and TimescaleDB is used as "eventual" secondary storage to provide metrics data (aggregates).

Suggestion to structure (rephrase) the corresponding docs section to mainly focus on data ingestion part (into TimescaleDB).
In particular, it might be interesting to know, the differences in the following setups:
 * `JDBC compatible source --(Kafka JDBC source connector)--> Kafka --(Kafka JDBC sink connector)--> TimescaleDB`
 * `Postgres ----> Debezium ----> Kafka --(Kafka JDBC sink connector)--> TimescaleDB`

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/ingest-data/#postgresql-kafka-connector

# Version affected

Latest.

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]
Might be relevant, some clarifying information https://stackoverflow.com/a/60908892.

# Screenshots

[Attach images of screenshots showing the bug]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
This merged recently, does it solve the problem: https://github.com/timescale/docs/pull/747 ?

**Comment by 1u0** [comment]
I believe the ambiguity is still there.
The whole page is under `Ingest data from other sources`, however the Kafka section contains (semantically) mixed technical information if TimescaleDB is used as a data source or as a data sink.

**Comment by Loquacity** [comment]
We're planning some major docs updates around various integrations in the future, so for now I've just removed the misleading/confused content, and updated the link.
