### ISSUE TITLE
[Docs RFC] Add Cloud regions

### ISSUE THREAD

**Issue by charislam** [timescale/docs#775]
# Describe change in content, appearance, or functionality

Docs mention [MST regions](https://docs.timescale.com/timescaledb/latest/overview/faq/faq-products/#is-timescaledb-currently-being-used-in-production) but not cloud regions. Add cloud regions.

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
Duplicate of https://github.com/timescale/docs-private/issues/23
