### ISSUE TITLE
[Docs RFC] Update information on upgrading PostgreSQL

### ISSUE THREAD

**Issue by charislam** [timescale/docs#788]
# Describe change in content, appearance, or functionality

Add information on upgrading PostgreSQL within a managed environment. The [current docs on upgrading PostgreSQL](https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/upgrade-postgresql/) only apply to self-hosted TimescaleDB, but that is not made clear. There are [separate instructions for upgrading PostgreSQL on Managed Service for TimescaleDB](https://kb-managed.timescale.com/en/articles/5368016-perform-a-postgresql-major-version-upgrade), but those are only available on the knowledge base. (I haven't found information yet for how to do it in Cloud.)

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
Cloud info is here: https://docs.timescale.com/cloud/latest/maintenance/#upgrade-to-a-new-postgresql-version

As for getting stuff across from the MST KBase, that is a larger amount of work, that will be handled as its own project.
