### ISSUE TITLE
[Docs RFC] Standardize placeholder parameters in code

### ISSUE THREAD

**Issue by charislam** [timescale/docs#803]
# Describe change in content, appearance, or functionality

Standardize placeholder parameters in code examples to use `<PLACEHOLDER_PARAM>`.

For example, `<TABLE_NAME>`, `<NEWER_THAN>`, and `<OLDER_THAN>` in:
```
SELECT decompress_chunk(i) from show_chunks('table_name', newer_than, older_than) i;
```

Also line-wrap code where possible to minimize horizontal scrolling in code boxes.

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

## Checklist for progress in checking the docs:

- [x] Install TimescaleDB
- [x] TimescaleDB overview
- [ ] TimescaleDB Getting started
- [ ] How-to guides
- [ ] Tutorials
- [ ] Code quick starts
- [ ] Contribution guides
- [ ] API reference
- [ ] Timescale Cloud
- [ ] Managed Service for TimescaleDB
- [ ] Promscale

**Comment by charislam** [comment]
@Rajakavitha1 and @Loquacity, what do you think is the best format for this?

I've seen both `<placeholder_param>` and `<PLACEHOLDER_PARAM>` in our docs.

Also, there may be instances where it's better to give an example than just a placeholder. Such as the code example in the pull request description, where you have to guess at how `newer_than` and `older_than` should be formatted.

In those cases, should we standardize on something like:

> For example, to decompress chunks containing data between '2019-01-01' and '2020-01-01'

Doesn't have to be the exact words every time, but make it clear that the dates are an example only.

**Comment by Loquacity** [comment]
I once polled a bunch of developers on preference, and the clear answer was `<PLACEHOLDER_PARAM>` (we can re-conduct that poll, though, if you want). 

I agree that sometimes we need an example rather than a placeholder, but in that case I think I would prefer to do something like this:

```
Use this format for the command:
`command --param <PLACEHOLDER>`

For example:
`command --param filename`
```

Not always practical, though, I admit, so we should try to be flexible according to the situation.

**Comment by Rajakavitha1** [comment]
@charislam and @Loquacity  this is an awesome discussion!!!! Learning everyday with you all.

**Comment by charislam** [comment]
Awesome that you did the poll! I'm happy to go with `<PLACEHOLDER_PARAM>`. I'll add a note to the issue that we're settling on that and make a checklist to document our progress through the docs. I'll probably assign myself to it next week, but am happy to have help if either of you want a tedious task in your spare time 😉

**Comment by Rajakavitha1** [comment]
> Awesome that you did the poll! I'm happy to go with `<PLACEHOLDER_PARAM>`. I'll add a note to the issue that we're settling on that and make a checklist to document our progress through the docs. I'll probably assign myself to it next week, but am happy to have help if either of you want a tedious task in your spare time 😉

@charislam  I would love to help in the task.

**Comment by Loquacity** [comment]
Leave issues as unassigned until you're ready to start work on them. When you're ready to start work, assign yourself, and move them into the `Doing` column.
