### ISSUE TITLE
[Docs RFC] Replace metrics screenshot

### ISSUE THREAD

**Issue by lukas-bernert** [timescale/docs#821]
# Describe change in content, appearance, or functionality

Replace the metrics screenshot with the screenshot attached. The new screenshot includes the "refresh interval toggle" in the top right.

# Subject matter expert (SME)

@lukas-bernert 
# Deadline

This is live already. Anytime.

# Any further info

<img width="1186" alt="Screenshot 2022-02-16 at 14 15 53" src="https://user-images.githubusercontent.com/23032575/154339294-36e9d85f-71cd-4421-85af-5eb344370cbc.png">

**Comment by Loquacity** [comment]
SUId, and updated in AWS 👍
