### ISSUE TITLE
[Docs RFC] Influence "migration" search results

### ISSUE THREAD

**Issue by lukas-bernert** [timescale/docs#831]
# Describe change in content, appearance, or functionality

Currently, when searching for "migration" or related terms, the new "[migrate to Cloud](https://docs.timescale.com/cloud/latest/migrate-to-cloud/)" docs page doesn't show up at all. Is there a way to influence the results to show the new page above the existing migration docs? 
We'd like to promote the new "migrate to Cloud" docs over existing migration docs.

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

Anytime soon

# Any further info

<img width="1304" alt="Screenshot 2022-02-17 at 15 15 55" src="https://user-images.githubusercontent.com/23032575/154563987-ee9cdf81-0382-41b4-8c9c-2bc3ffbefb4b.png">

**Comment by jacobprall** [comment]
Updated search index.

**Comment by lukas-bernert** [comment]
@jacobprall is there any way to rank these docs above other "migrate" pages?

**Comment by lukas-bernert** [comment]
currently only #6 when searching for "migrate"

<img width="1328" alt="Screenshot 2022-02-22 at 14 42 15" src="https://user-images.githubusercontent.com/23032575/155206837-31a4549a-1dbc-4881-aa87-ce053f17f62a.png">
