### ISSUE TITLE
ABL [Docs RFC] Add section on using `pg_stat_statements` for Cloud Visibility

### ISSUE THREAD

**Issue by lukas-bernert** [timescale/docs#832]
# Describe change in content, appearance, or functionality

For Cloud docs, we need a section that describes [pg_stat_statements](https://www.postgresql.org/docs/14/pgstatstatements.html).

All Cloud services come with the extension pre-installed.
They need to connect with a Postgres Client (e.g. psql).

In order to filter out any superuser query statistics they need to add the following WHERE clause to their queries:

e.g. 
`SELECT * FROM pg_stat_statements WHERE pg_get_userbyid(userid) = current_user;`

In general, this allows them to view performance statistics of their queries.
E.g. identify long running queries, I/O heavy queries, memory heave queries, etc...

Maybe as a fast follow we could recommend some queries they could run to improve DB performance?

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

Anytime

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
> @Loquacity any chance we can get this to review by end of this week?

Looks like we're pretty close! @charislam do you have an ETA?
