### ISSUE TITLE
[Docs RFC] Update Promscale deletion docs to mention delete_series_from_metric()

### ISSUE THREAD

**Issue by charislam** [timescale/docs#837]
# Describe change in content, appearance, or functionality

Docs mention deletion of series via the HTTP API but not the SQL way of running `_prom_catalog.delete_series_from_metric(name text, series_ids bigint[])`

[Relevant Slack message](https://timescaledb.slack.com/archives/C011FC0PPC5/p1645168130769889)

# Subject matter expert (SME)

@antekresic 

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Rajakavitha1** [comment]
Hi @charislam and @Loquacity !!!!
I did some research and reading about this issue. My understanding is that this needs to be updated in the https://github.com/timescale/promscale/blob/master/docs/metric_deletion_and_retention.md. Also, I do not see any references to this in https://docs.timescale.com/promscale/latest/sql-api/#sql-function-api-reference. Please let me know if the content located at https://github.com/timescale/promscale/blob/master/docs/metric_deletion_and_retention.md will be eventually moved to https://docs.timescale.com . If no, should this issue be reported under https://github.com/timescale/promscale/blob/master/docs/. If yes, do we wait and then update the content.

**Comment by Loquacity** [comment]
> Hi @charislam and @Loquacity !!!! I did some research and reading about this issue. My understanding is that this needs to be updated in the https://github.com/timescale/promscale/blob/master/docs/metric_deletion_and_retention.md. Also, I do not see any references to this in https://docs.timescale.com/promscale/latest/sql-api/#sql-function-api-reference. Please let me know if the content located at https://github.com/timescale/promscale/blob/master/docs/metric_deletion_and_retention.md will be eventually moved to https://docs.timescale.com . If no, should this issue be reported under https://github.com/timescale/promscale/blob/master/docs/. If yes, do we wait and then update the content.

Let's get it moved over.

**Comment by Rajakavitha1** [comment]
> > Hi @charislam and @Loquacity !!!! I did some research and reading about this issue. My understanding is that this needs to be updated in the https://github.com/timescale/promscale/blob/master/docs/metric_deletion_and_retention.md. Also, I do not see any references to this in https://docs.timescale.com/promscale/latest/sql-api/#sql-function-api-reference. Please let me know if the content located at https://github.com/timescale/promscale/blob/master/docs/metric_deletion_and_retention.md will be eventually moved to https://docs.timescale.com . If no, should this issue be reported under https://github.com/timescale/promscale/blob/master/docs/. If yes, do we wait and then update the content.
> 
> Let's get it moved over.

Thank you @Loquacity  I will move the content to https://docs.timescale.com/promscale and update the content with delete_series_from_metric()
