### ISSUE TITLE
[Content Bug] Missing links where there should be linked text in documentation

### ISSUE THREAD

**Issue by jproman1** [timescale/docs#84]
_Use this template for reporting bugs in the docs._

# Describe the bug

missing links where there are brackets in the first sentence under the Compression section on docs. See attached screenshot with highlighted text that needs links.

# Page affected

https://docs.timescale.com/api/latest/compression/

# Version affected

latest

# Subject matter expert (SME)

If known, who is a good person to ask about this topic

# Screenshots
<img width="1183" alt="Screen Shot 2021-05-24 at 3 48 56 PM" src="https://user-images.githubusercontent.com/80284941/119491925-84411300-bd2c-11eb-8dfd-fcb1197d1cc8.png">

# Any further info

I'm not sure what the target URLs are for the two links being blog post and a tutorial or I'd include those on here as well.

**Comment by Loquacity** [comment]
Waiting for https://github.com/timescale/docs/pull/74 to merge first.
