### ISSUE TITLE
[Site Bug] Fix password authentication instructions for using local pass file

### ISSUE THREAD

**Issue by dhawansakshi** [timescale/docs#842]
_Use this template for reporting bugs in the docs._

# Describe the bug

I am trying to use the password authentication method explained here but not able to add data node with that

It describes password authentication method by creating a local passfile but that is not working for me

It is also mention proper details about the passfile and directory and the owner details also what errors could occur. The steps mentioned are not very clear

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-auth/#setting-up-additional-user-roles

# Version affected

timescale docs(latest v2.x)

# Subject matter expert (SME)

@erimatnor 

# Screenshots

[Capture](https://user-images.githubusercontent.com/27430299/154798660-a706868a-34ff-405b-aee2-fdd2c73f17fe.PNG)

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
@NunoFilipeSantos Can you recommend an SME for this?

**Comment by NunoFilipeSantos** [comment]
Hi @Loquacity ! @erimatnor is the MN expert overall.

**Comment by Loquacity** [comment]
Hi @erimatnor Can you point me to any discussion or existing docs we have to help me try and get a start on this?

**Comment by Loquacity** [comment]
These docs were comprehensively updated recently, and this issue is not really detailed enough to determine what, exactly, the problem with this procedure is. Closing due to lack of clarity.
