### ISSUE TITLE
[Docs RFC] Add instructions to set authentication type for Cloud service password to MD5

### ISSUE THREAD

**Issue by charislam** [timescale/docs#866]
# Describe change in content, appearance, or functionality

With self-hosted TimescaleDB, you can edit the `postgresql.conf` file to change password encryption type from SCRAM-SHA-256 to MD5. You can do the same thing on Cloud via the UI, but that is not documented yet.

# Subject matter expert (SME)

@tylerfontaine @clarkbw 

# Deadline

[When does this need to be addressed]

# Any further info

Select the service. Go to Operations -> Reset Password.
It will ask for your Timescale Cloud Account password to proceed.
Then you can set your new password and select MD5 instead of SCRAM-SHA
![image](https://user-images.githubusercontent.com/26616127/155622269-23a9fb54-e12c-431b-9149-ed3d79f26156.png)

**Comment by clarkbw** [comment]
Maybe the search needs to be updated but I don't see the new page when I search for [SCRAM](https://docs.timescale.com/search/?query=SCRAM)

**Comment by charislam** [comment]
Yep probably the crawler needs to run! Paging @jacobprall :D
