### ISSUE TITLE
[Content Bug] Broken links on docs Tutorial: Time-series forecasting page

### ISSUE THREAD

**Issue by jproman1** [timescale/docs#87]
# Describe the bug

There are multiple broken links on the [Tutorial: Time-series forecasting](https://docs.timescale.com/timescaledb/latest/tutorials/time-series-forecast/##tutorial-time-series-forecasting) page that results in 404 pages. 

I found "Hello Timescale Tutorial" linked text listed twice that lead to 404. Additional linked text  "Installed and set up PostGIS in database" leads to 404. See screenshots below for reference.

# Page affected

https://docs.timescale.com/timescaledb/latest/tutorials/time-series-forecast/#tutorial-time-series-forecasting

# Version affected

latest

# Screenshots
<img width="1277" alt="Hello Timescale Tutorial link 1" src="https://user-images.githubusercontent.com/80284941/119592826-34ebf880-bda7-11eb-9d22-d1252f037dd4.png">
<img width="1263" alt="Hello Timescale Tutorial link 2" src="https://user-images.githubusercontent.com/80284941/119592838-37e6e900-bda7-11eb-942c-8ffdc0cc86f0.png">
<img width="1270" alt="404 1" src="https://user-images.githubusercontent.com/80284941/119592852-3f0df700-bda7-11eb-8ce7-efcf5e5d76c0.png">
<img width="1266" alt="404 2" src="https://user-images.githubusercontent.com/80284941/119592855-41705100-bda7-11eb-8c79-bca0377ff531.png">
<img width="1272" alt="Installed and set up PostGIS in database link 3" src="https://user-images.githubusercontent.com/80284941/119593360-dc692b00-bda7-11eb-9cb4-2768bf325eb5.png">
<img width="1264" alt="404 3 Installed and set up PostGIS in database" src="https://user-images.githubusercontent.com/80284941/119593370-decb8500-bda7-11eb-8141-f42ae1c61ac4.png">

# Any further info

There are more links on that "Introduction to time-series forecasting" docs page that I believe are not the correct URL destination. I'll create a new ticket following this one to detail those other links I'm referring to.

**Comment by Loquacity** [comment]
> # Any further info
> There are more links on that "Introduction to time-series forecasting" docs page that I believe are not the correct URL destination. I'll create a new ticket following this one to detail those other links I'm referring to.

No need for another bug, I'll look at the entire page.

**Comment by Loquacity** [comment]
> Hey Lana! The other two links I was going to submit on GitHub on the Time-series forecasting tutorial page are “python” and  “previous section”.  I’m pretty sure those two linked text urls are not to the correct target URL’s. At least, I believe they don’t lead to the right place but I’m not 100%

**Comment by Loquacity** [comment]
This has been fixed in another PR.
