### ISSUE TITLE
[Docs RFC] Deprecate or update Telegraf plugin page

### ISSUE THREAD

**Issue by charislam** [timescale/docs#873]
# Describe change in content, appearance, or functionality

We no longer maintain the Telegraf output plugin. Either deprecate [the Telegraf plugin page](https://docs.timescale.com/timescaledb/latest/tutorials/telegraf-output-plugin/) or point readers to Patrick Hemmer's pre-release binary and update the instructions to work with that.

[Relevant Slack message](https://timescaledb.slack.com/archives/C4GT3N90X/p1645789484764599)
[Relevant forum post](https://www.timescale.com/forum/t/telegraf-plugin/118)

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
We have the deprecation notice now, so let's use it 👍
