### ISSUE TITLE
[Docs RFC] Improve code example for `compress_chunks`

### ISSUE THREAD

**Issue by charislam** [timescale/docs#903]
# Describe change in content, appearance, or functionality

Improve code example for `compress_chunks` by adding argument `if_not_compressed => true`, so the function won't fail if some chunks are already compressed.

[Suggestion comes from the Community Slack.](https://timescaledb.slack.com/archives/C02Q1LWMG3W/p1646393569916599)

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment]
We'll need to identify an SME for this one.
