### ISSUE TITLE
Add Grafana to Visualize data in Promscale

### ISSUE THREAD

**Issue by ramonguiu** [timescale/docs#923]
Update "Visualize data in Promscale" to be more generic and act as an index page for this section.

Add a Grafana page under "Visualize data in Promscale" explaining how to configure and use a Prometheus datasource, a Jaeger datasource and a SQL datasource.

## SME

@VineethReddy02 

## Links
- The "Configuring Data sources in Grafana" section in [this blog](https://www.timescale.com/blog/how-to-turn-timescale-cloud-into-an-observability-backend-with-promscale/) post has all the content we need. We will need to modify the configuration parameters to be generic. Also the url for the Jaeger data source will be different since we are adding new support for that to Promscale which won't require running Jaeger. This will be a very small change.

**Comment by Rajakavitha1** [comment]
Closing this issue because it has been addressed in the merged PR
