### ISSUE TITLE
Add Zipkin to Send data to Promscale

### ISSUE THREAD

**Issue by ramonguiu** [timescale/docs#929]
Explain how to configure Zipkin to send data to Promscale:

Configure the OTel Collector (content available in https://github.com/timescale/promscale/blob/master/docs/tracing.md#jaeger-instrumentation)
Configure Zipkin instrumentation (content available in https://github.com/timescale/promscale/blob/master/docs/tracing.md#zipkin-instrumentation)

**Comment by Rajakavitha1** [comment]
Closing this issue because they have been tracked and addressed in https://github.com/timescale/docs-private/issues/30
