### ISSUE TITLE
[Docs RFC] Zooming makes the content too narrow

### ISSUE THREAD

**Issue by arp242** [timescale/docs#946]
If I zoom in the actual content column gets more narrow; here it is at 100% zoom:

![cap-2022-03-11T15:23:33](https://user-images.githubusercontent.com/1032692/157886530-b168678d-a463-47b0-aa87-685f0dc4ba1a.png)

And here it is at 175%:

![cap-2022-03-11T15:23:22](https://user-images.githubusercontent.com/1032692/157886555-9a010f84-e056-4647-9912-0004c922ed94.png)

This makes the content harder to read at zoom levels, which isn't ideal. The "was this page helpful" column on the side takes up a lot of space.

**Comment by Rajakavitha1** [comment]
Hi @arp242 !!This has now been addressed in the new rebranded website. Marking this issue as closed.
Please feel free to reopen if any other issues needs to be addressed.[](url)

![Image](https://github.com/timescale/docs/assets/37059749/28b341f7-2ebe-4d6a-9c1c-38c45ac2e60c)
