### ISSUE TITLE
[Site Bug] Issue with the page: /latest/getting-started/installation/macos/installation-source

### ISSUE THREAD

**Issue by gelisam** [timescale/docs#981]
# Describe the bug

The URL https://docs.timescale.com/latest/getting-started/installation/macos/installation-source now redirects to https://docs.timescale.com/installlatest/self-hosted/installation-macos/ (note the missing `/` in `installlatest`), which is a 404. It should redirect to https://docs.timescale.com/install/latest/self-hosted/installation-macos/ instead.

## What do the docs say now?

"Page Not Found"

## What should the docs say?

"Install self-hosted TimescaleDB from source" [...]

# Page affected

https://docs.timescale.com/latest/getting-started/installation/macos/installation-source

I am guessing that other URLs of the form `/installation/...` might also incorrectly redirect to `/installlatest/.../`, but this is the only URL I have on hand.

# Version affected

"latest", I guess

# Subject matter expert (SME)

?

# Screenshots

Seems like a `curl` output showing the `location` header would be more useful than a screenshot of the 404 page:

```
$ curl -i https://docs.timescale.com/latest/getting-started/installation/macos/installation-source
HTTP/2 301
date: Thu, 24 Mar 2022 21:01:28 GMT
content-length: 0
location: https://docs.timescale.com/installlatest/self-hosted/installation-macos/
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=7aaH%2BsKQoNTvyeSz%2FBGSJMkQ4jMFnzEsaXKd%2Fyu%2FUQbRx5i6bVpnj9Hu%2BxrLkagi9LPZmQUazrt1L5c4kzejtssPyrWnjqEWz152jMHrU0Ovj6iPCqmysZVoGdoVL4M%2BKeC6f5M%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=15552000; includeSubDomains; preload
server: cloudflare
cf-ray: 6f12579a9f18f041-EWR
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

# Any further info

that's it!

**Comment by charislam** [comment]
Fixed by [web-documentation PR #313](https://github.com/timescale/web-documentation/pull/313)

**Comment by gelisam** [comment]
Thanks for the quick fix! Unfortunately it's even worse now, as it redirects to https://docs.timesacale.com/install/latest/self-hosted/installation-source/, which also has a typo: `timesacale` instead of `timescale`.

**Comment by charislam** [comment]
@gelisam 🤦🏼‍♀️ Thanks for the quick spot! Fixed the fix, should be live later today!
